#-*- Makefile -*-
include ../../gnuwin32/MkRules

all: makeMakedeps libz.a

SOURCES = adler32.c compress.c crc32.c deflate.c gzio.c infback.c \
  inffast.c inflate.c inftrees.c trees.c uncompr.c zutil.c
OBJECTS = $(SOURCES:.c=.o)

CFLAGS=-O3 -I../../include -DHAVE_CONFIG_H

libz.a: $(OBJECTS)

clean:
	$(RM) *.o *~ *.d Makedeps
distclean: clean
	$(RM) libz.a

# Dependencies
DEPS=$(SOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
