.TH Rdconv 1
.SH NAME
Rdconv \- conversion of R documentation files
.SH SYNOPSIS
.B Rdconv 
[
.I options
]
.I Rdfile
.br
.B Rdconv
.I --help
.LP
.B Rd2txt 
.I Rdfile
.LP
.B 
Rdindex
[
.I options
]
.I Rdfiles
.LP
.B Sd2Rd 
[
.I options
]
.I file
.SH DESCRIPTION
.B Rdconv, Rd2txt, Rdindex 
and 
.B Sd2Rd 
are helper applications of the
.BR R (1)
software package for statistical data analysis. They are used to
convert R's documentation format from/to other formats including
nroff, HTML and LaTeX. Please consult the R on-line help system or the
R manual for details. The R help system can be viewed using the
commands help() or help.start() at the R prompt.
.SH AUTHORS
Friedrich Leisch <Friedrich.Leisch@ci.tuwien.ac.at> and the R core team.
.SH SEE ALSO
.BR R (1)

