\input texinfo
@c %**start of header
@setfilename rw-FAQ.info
@settitle R for Windows FAQ
@setchapternewpage on
@set VERSION @RWVER@
@set RVERSION @RVER@
@c %**end of header

@dircategory Programming
@direntry
* R for Windows FAQ: (rw-FAQ).  The R for Windows FAQ.
@end direntry

@finalout

@macro newchap{}
@ifinfo
@sp 1
@end ifinfo
@ifhtml
@html
<p><hr>
@end html
@end ifhtml
@end macro

@titlepage
@title R for Windows FAQ
@subtitle Frequently Asked Questions on R for Windows
@subtitle Version @value{VERSION}
@author B. D. Ripley
@end titlepage

@ifinfo
R for Windows FAQ                           @*
Frequently Asked Questions on R for Windows @*
Version for @value{VERSION}                 @*
Brian Ripley                                @*

@sp 2
@end ifinfo

@ifhtml
@html
<html>
<head>
<TITLE>R for Windows FAQ</TITLE>
</head>

<body>
<h1 align="center">R for Windows FAQ</h1>
<h2>Version for <tt>@value{VERSION}</tt></h2>
<address>B. D. Ripley</address>
<p><p><hr><p>
@end html
@end ifhtml

@paragraphindent 0

@contents

@ifinfo
@sp 1
@end ifinfo


@node Top, Introduction, (dir), (dir)

@menu
* Introduction::                
* Installation and Usage::      
* Packages::                    
* Windows Features::            
* Workspaces::                  
* The R Console and Fonts::     
* Building from Source::        
@end menu


@newchap{}
@node Introduction, Installation and Usage, Top, Top
@chapter Introduction

This FAQ is for the Windows port of R: it describes features specific to
that version.  The main R FAQ can be found at

@display
@uref{http://www.ci.tuwien.ac.at/~hornik/R/R-FAQ.html}.
@end display

The information here applies only to recent versions of R for Windows,
(@code{rw1020} or later); the current version is often called something like
@code{@value{VERSION}} (although not officially).



@newchap{}
@node Installation and Usage, Packages, Introduction, Top
@chapter Installation and Usage

@menu
* Where can I find the latest version?::  
* How do I install R for Windows?::  
* How do I run it?::            
* There seems to be a limit on the memory it uses!::  
* How can I keep workspaces for different projects in different directories?::  
* How do I print from R?::      
* Can I use R BATCH?::          
* Can I use @RWVER@ with ESS and emacs?::  
* What are HOME and working directories?::  
* R can't find my file::        
* Does R use the Registry?::    
* Entering certain characters crashes Rgui.::  
@end menu


@node Where can I find the latest version?, How do I install R for Windows?, Installation and Usage, Installation and Usage
@section Where can I find the latest version?

Go to any CRAN site (see @uref{http://cran.r-project.org/mirrors.html}
for a list), navigate to the @code{bin/windows/base}
directory and collect the files you need.  There are three
possibilities.

1) @code{SetupR.exe}, is about 15Mb and gives a complete installation.

2) Directory @code{miniR} contains @code{miniR.exe} and six files
@code{miniR-?.bin}.  You can put  @code{miniR.exe} and @code{miniR-1.bin}
on one floppy and the remaining @code{miniR-?.bin} on a floppy each.

3) Via zip files in directory @code{zip}.  You will need at least the
files
@example
      @RWVER@b1.zip @RWVER@b2.zip
      @RWVER@h.zip (text help) or @RWVER@ch.zip (Compiled HTML help)
@end example
@noindent
and you may want @code{@RWVER@w.zip} (the HTML format help files),
@code{@RWVER@l.zip} (the LaTeX format help files, used for offline
printing), or @code{@RWVER@d?.zip} (the draft manuals, in PDF).


@node How do I install R for Windows?, How do I run it?, Where can I find the latest version?, Installation and Usage
@section How do I install R for Windows?

First, you need Windows 95/98/ME/NT4/2000: Windows 3.11+win32s will not
work. (Windows XP probably will.)  Your file system must allow long file
names (as is likely except perhaps for some network-mounted systems).

The simplest way is to use @code{SetupR.exe} or @code{miniR.exe}.  Just
double-click on the icon and follow the instructions.  If you installed
R this way you can uninstall it from the Control Panel or Start Menu
(unless you supressed making a group for R).

For a manual installation, choose a location and unzip the zip files
(with a tool that preserves long file names and the directory structure:
we recommend the INFO-ZIP project's @code{unzip}).  All the files will
unpack into a directory @code{@RWVER@}.

Choose a working directory for R.  Unless you used @code{SetupR.exe} or
@code{miniR.exe} (which did this for you by default), make a shortcut to
@code{@RWVER@\bin\Rgui.exe} on your desktop or somewhere on the Start
menu file tree.  Right-click the shortcut, select Properties... and
change the `Start in' field to your working directory.

You may also want to add command-line arguments at the end of the Target
field, for example @code{--sdi --max-mem-size=40M}.  You can also set
environment variables at the end of the Target field, for example
@code{R_LIBS=p:/R/library}.


@node How do I run it?, There seems to be a limit on the memory it uses!, How do I install R for Windows?, Installation and Usage
@section How do I run it?

Just double-click on the shortcut you prepared at installation.

If you want to set up another project, make a new shortcut or use the
existing one and change the `Start in' field of the Properties.


@node There seems to be a limit on the memory it uses!, How can I keep workspaces for different projects in different directories?, How do I run it?, Installation and Usage
@section There seems to be a limit on the memory it uses!

Indeed there is.  It is set by the command-line flag
@code{--max-mem-size} and defaults to the smaller of the amount of
physical RAM in the machine and 256Mb.  It can be set to any amount over
10M.  Be aware though that Windows has (in most versions) a maximum
amount of user virtual memory of 2Gb, and parts of this can be reserved
by processes but not used.  R itself reserves 256Mb on startup.  Because
of the way the memory manager works, it is possible that there will be
free memory but R will not be able to reserve it.

Use @code{?Memory} and @code{?memory.size} for information about memory
usage.

R can be compiled to use a different memory manager which may be better
at using large amounts of memory, but is substantially slower (making R
several times slower on some tasks).


@node How can I keep workspaces for different projects in different directories?, How do I print from R?, There seems to be a limit on the memory it uses!, Installation and Usage
@section How can I keep workspaces for different projects in different directories?

Create a separate shortcut for each project: see Q2.3.  All the paths to
files used by R are relative to the starting directory, so setting the
`Start in' field automatically helps separate projects.

Alternatively, start R by double-clicking on a saved @file{.RData} file
in the directory for the project you want to use, or drag-and-drop a
file with extension @file{.RData} onto an R shortcut.  In either case,
the working directory will be set to that containing the file.


@node How do I print from R?, Can I use R BATCH?, How can I keep workspaces for different projects in different directories?, Installation and Usage
@section How do I print from R?

It depends what you want to print.

@itemize @bullet
@item You can print the graphics window from its menu or by using
@code{dev.print()}.
@item You can print from the R console or pager by @code{File | Print}.
(This will print the selection if there is one,
otherwise the whole console or pager contents.)
@item You can print help files from the pager or HTML browser.
@item If you have configured @code{RHOME\bin\helpPRINT.bat} and have
LaTeX installed you can print help files by @code{help(fn_name, offline=TRUE)}.
@end itemize


@node Can I use R BATCH?, Can I use @RWVER@ with ESS and emacs?, How do I print from R?, Installation and Usage
@section Can I use @code{R BATCH}?

Yes, if you have Perl and the files for making source packages (from
@code{SetupR.exe} or @code{@RWVER@sp.zip}) installed.  The Windows
analogue is @code{Rcmd BATCH}: use @code{Rcmd BATCH --help} for full
details.

Otherwise you can set up a batch file using @code{Rterm.exe}.  A sample
batch file might contain (as one line)

@example
path_to_R\bin\Rterm.exe --no-restore --no-save < %1 > %1.out
@end example


@node Can I use @RWVER@ with ESS and emacs?, What are HOME and working directories?, Can I use R BATCH?, Installation and Usage
@section Can I use @RWVER@ with ESS and emacs?

Yes.  The latest versions of ESS (e.g. 5.1.18) come with support for this
version of R, and there is support for interrupting the R process from
ESS (by @code{C-c C-c}).

For help with ESS, please send email to @email{ESS-help@@stat.ethz.ch},
not the R mailing lists.


@node What are HOME and working directories?, R can't find my file, Can I use @RWVER@ with ESS and emacs?, Installation and Usage
@section What are HOME and working directories?

Several places in the documentation use these terms.

The working directory is the directory from which @code{Rgui} or
@code{Rterm} was launched, unless a shortcut was used when it is given
by the `Start in' field of the shortcut's properties.  You can find this
from R code by the call @code{getwd()}.

The home directory is set as follows:@*
If environment variable @code{R_USER} is set, its value is used.@*
Otherwise if environment variable @code{HOME} is set, its value is used.@*
Otherwise if environment variables @code{HOMEDRIVE} and @code{HOMEPATH}
are set, the value is @code{$@{HOMEDRIVE@}$@{HOMEPATH@}}.@*
If all of these fail, the current working directory is used.

You can find this from R code by @code{Sys.getenv("R_USER")}.


@node R can't find my file, Does R use the Registry?, What are HOME and working directories?, Installation and Usage
@section R can't find my file, but I know it is there!

How did you specify it?  Backslashes have to be doubled in R character
strings, so for example one needs
@code{"d:\\@RWVER@\\library\\xgobi\\scripts\\xgobi.bat"}.
Make life easier for yourself by using forward slashes as path
separators: they do work under Windows.

Another possible source of grief is spaces in folder names.  We have
tried to make R work on paths with spaces in, but lots of people writing
packages for Unix do not bother.  So it is worth trying the alternative
short name (something like @code{PROGRA~1}; you can get it as the
`MS-DOS name' from the Properties of the file on most versions of Windows).


@node Does R use the Registry?, Entering certain characters crashes Rgui., R can't find my file, Installation and Usage
@section Does R use the Registry?

Not itself.  

The installers set some entries to allow uninstallation.  In addition
they set a Registry key @code{LOCAL_MACHINE\Software\R-core\R} giving
the version and install path.  Again, this is not used by R itself, but
it will be used by the DCOM interface
(@uref{http://cran.r-project.org/other-software.html}).  Finally, a file
association for extension @code{.RData} is set in the Registry.

You can add the Registry entries by running @code{RSetReg.exe} in the
@code{bin} folder, and remove them by running this with argument
@code{/U}.  Note that the settings are all per machine and not per user,
and that this neither sets up nor removes the file associations.

@node Entering certain characters crashes Rgui.,  , Does R use the Registry?, Installation and Usage
@section Entering certain characters crashes Rgui.

This seems to happen occasionally, and all the occurrences we have
solved have been traced to faulty versions of @samp{msvcrt.dll}.  Try
extracting the one to be found in the self-extracting archive
@uref{ftp://ftp.microsoft.com/softlib/mslfiles/msvcrt.exe}
and put it in the @code{@RWVER@\bin} directory.  Removing
@samp{msvcrt.dll} from that directory reverts to the standard behaviour.

This fix has solved other problems too, for example incorrect results in
the date-time functions.



@newchap{}
@node Packages, Windows Features, Installation and Usage, Top
@chapter Packages


@menu
* Can I install packages (libraries) in this version?::  
* I don't have permission to write to the @RWVER@\library directory::  
* The packages I installed do not appear in the HTML help system::  
* My functions are not found by the HTML help search system.::  
* Loading a package fails.::    
* Package TclTk does not work.::  
* Hyperlinks in Compiled HTML do not work.::  
@end menu


@node Can I install packages (libraries) in this version?, I don't have permission to write to the @RWVER@\library directory, Packages, Packages
@section Can I install packages (libraries) in this version?

Yes, but you will need a lot of tools to do so, unless the author or the
maintainers of the @code{bin/windows/contrib} section on CRAN has been
kind enough to provide a pre-compiled version for Windows as a
@code{.zip} file.

You can install pre-compiled packages either from CRAN or from a local
@code{.zip} file by using @code{install.packages}: see its help page.
There are menu items on the @code{Packages} menu to provide a
point-and-click interface to package installation.

Note that the pre-compiled versions on CRAN are unsupported: see
@uref{http://cran.r-project.org/bin/windows/contrib/ReadMe}.

If there is not a pre-compiled version or that is not up-to-date or you
prefer compiling from source, get @code{@RWVER@sp.zip} from the
distribution (see Q1.1; you may already have installed this from
@code{SetupR.exe}) and unpack it in the parent of @code{@RWVER@}.  Then
read the file @file{readme.packages}.  You will need to collect and
install several tools to use this.  Once you have done so, just run
@code{Rcmd INSTALL pkgname}.  To check the package (including running
all the examples on its help pages and in its test suite, if any) use
@code{Rcmd check pkgname}: see the @emph{`Writing R Extensions'} manual.


@node I don't have permission to write to the @RWVER@\library directory, The packages I installed do not appear in the HTML help system, Can I install packages (libraries) in this version?, Packages
@section I don't have permission to write to the @file{@RWVER@\library} directory.

You can install packages anywhere and use the environment variable
@code{R_LIBS} to point to the library location(s).  You can also set the
R variable @code{.lib.loc} in your @file{.Rprofile} or when running R.

Suppose your packages are installed in @code{p:\mylibs}.  Then you can EITHER

@example
set the environment variable R_LIBS to p:\mylibs
@end example
@noindent
OR put in the @code{.Rprofile} in the working directory or your home directory

@example
.lib.loc <- c("p:/mylibs", .Library)
@end example
@noindent
OR use a package by, e.g.

@example
library(MASS, lib.loc="p:/mylibs")
@end example

How you set an environment variable is system specific: in Windows 9x
you can set them in @file{autoexec.bat} or in an MS-DOS window from
which you launch @code{Rgui} / @code{Rterm}.  Under Windows NT/2000 you
can use the control panel or the properties of `My Computer'.  Under
Windows Me you need to use the System Configuration Utility (under
Programs, Accessories, System Tools on the Start menu).  You can also
set them on the command line, for example in the shortcut you could have

@example
path_to_R\bin\Rgui.exe R_LIBS=p:/mylibs
@end example
@noindent
and you can set variables in a file @file{.Renviron} in the working directory
or your home directory, for example

@example
R_LIBS=p:/mylibs
@end example

The order of precedence for environmental variables is the command line
then @file{.Renviron} then the inherited environment.


@node The packages I installed do not appear in the HTML help system, My functions are not found by the HTML help search system., I don't have permission to write to the @RWVER@\library directory, Packages
@section The packages I installed do not appear in the HTML help system.

The HTML search only works for packages installed in
@file{@RWVER@\library}.

To update the HTML indices after you have installed a pre-compiled
package, run at the R prompt.

@example
> link.html.help()
@end example

This is done automatically when installing from the Packages menu or
by @code{install.packages()}.


@node My functions are not found by the HTML help search system., Loading a package fails., The packages I installed do not appear in the HTML help system, Packages
@section My functions are not found by the HTML help search system.

The following conditions need to hold for functions in a package you installed.

@itemize @bullet
@item the package is installed in @file{@RWVER@\library}.
@item the package contains a @file{CONTENTS} file in its top-level directory.
@item you updated the indices as described in the answer to Q3.3 after
installing the package.
@end itemize
@noindent
If those all hold true, this works for us.


@node Loading a package fails., Package TclTk does not work., My functions are not found by the HTML help search system., Packages
@section Loading a package fails.

Is the package compiled for this version of R?  Many of the packages
need to be compiled for a fairly recent version, and in particular a
substantial minority need to be re-compiled for @code{rw1020} and later.

You can tell the version the package was compiled for by looking at the
@code{Built:} line in its @file{DESCRIPTION} file or at the
@code{Version} tab of its DLL (if it has one) in the @file{libs}
directory.  (Right-click on the DLL in Windows Explorer, and select
@code{Properties} or use the @code{DLL.version} function inside R.)
If there is no @code{Built:} line or version tab, the package was
compiled too long ago.


@node Package TclTk does not work., Hyperlinks in Compiled HTML do not work., Loading a package fails., Packages
@section Package TclTk does not work.

For package @code{tcltk} to work (try @code{demo(tkdensity)} or
@code{demo(tkttest)} after @code{library(tcltk)}) you need to have Tcl
installed.  Download either ActiveTcl 8.3.3 from
@uref{http://aspn.activestate.com/ASPN/Downloads/ActiveTcl/} or
@file{tcl832.exe} from @uref{dev.scriptics.com} and install it.  (That
will put the @file{bin} directory containing the Tcl and Tk DLLs in your
path).  You then need to set the environment variable
@code{TCL_LIBRARY}, to something like @code{c:/Program
Files/Tcl/lib/tcl8.3}.  (The startup code for the package will warn you
if this is unset, and Q3.2 explains how to set them.  NB: do not quote
the path, even if as here it contains spaces. If you forget, you can set
the variable inside R by something like
@smallexample
    Sys.putenv("TCL_LIBRARY"="c:/Program Files/Tcl/lib/tcl8.3")
@end smallexample
.)


@node  Hyperlinks in Compiled HTML do not work.,  , Package TclTk does not work., Packages
@section Hyperlinks in Compiled HTML sometimes do not work.

Unfortunately, hyperlinks in compiled HTML files used from R are
interpreted relative to the current working directory of the R process,
not relative to the @code{pkg.chm} file.  This was not discovered until
@code{rw1021}: files made before that version work incorrectly.  Remake
the package to cure this.



@newchap{}
@node Windows Features, Workspaces, Packages, Top
@chapter Windows Features

@menu
* What should I expect to behave differently from the Unix version::  
* I hear about some nifty features.::  
* Circles appear as ovals on screen::  
* How do I more focus to a graphics window or the console?::  
@end menu


@node  What should I expect to behave differently from the Unix version, I hear about some nifty features., Windows Features, Windows Features
@section  What should I expect to behave differently from the Unix version of R?

@itemize @bullet
@item R commands can be interrupted by @key{Esc} in @code{Rgui.exe}
and @key{Ctrl-break} or @key{Ctrl-C} in @code{Rterm.exe}: @key{Ctrl-C}
is used for copying in the GUI version.

@item Command-line editing is always available, but is simpler than the
readline-based editing on Unix.  For @code{Rgui.exe}, the menu item `Help |
Console' will give details.  For @code{Rterm.exe} see file
@file{README.rterm}.

@item Using @code{help.start()} does not automatically send help
requests to the browser: use @code{options(htmlhelp=TRUE)} to turn this on.

@item The HTML help system can only access packages installed in the standard
place.

@item Paths to files (e.g. in @code{source()}) can be specified with
either "/" or "\\".

@item @code{system()} is slightly different: see its help page and that
of @code{shell()}.
@end itemize


@node I hear about some nifty features., Circles appear as ovals on screen, What should I expect to behave differently from the Unix version, Windows Features
@section I hear about some nifty features: please tell me about them!

You have read the @code{README}? There are file menus on the R console,
pager and graphics windows.  You can source and save from those menus,
and copy the graphics to @code{png}, @code{jpeg}, @code{bmp},
@code{postscript}, @code{PDF} or @code{metafile}.  There are right-click
menus giving shortcuts to menu items, and optionally toolbars with
buttons giving shortcuts to frequent operations.

If you resize the R console the @code{options(width=)} is automatically
set to the console width (unless disabled in the configuration file).

The graphics has a history mechanism.  As the README says:

@quotation
`The History menu allows the recording of plots.  When plots have been
recorded they can be reviewed by @key{PgUp} and @key{PgDn}, saved and
replaced.  Recording can be turned on automatically (the Recording item
on the list) or individual plots can be added (Add or the @key{INS}
key).  The whole plot history can be saved to or retrieved from an R
variable in the global environment.

There is only one graphics history shared by all the windows devices.'
@end quotation
@noindent
The R console and graphics windows have configuration files stored in
the @file{RHOME\etc} directory called @file{Rconsole} and @file{Rdevga};
you can keep personal copies in your @file{HOME} directory.  They contain
comments which should suffice for you to edit them to your
preferences.  For more details see @code{?Rconsole}.
There is a Preferences editor invoked from the @code{Edit} menu which
can be used to edit the file @file{Rconsole}.


@node Circles appear as ovals on screen, How do I more focus to a graphics window or the console?, I hear about some nifty features., Windows Features
@section Circles appear as ovals on screen

The graphics system asks Windows for the number of pixels per inch in
the X and Y directions, and uses that to size graphics (which in R are
in units of inches).  Sometimes the answer is a complete invention, and
in any case Windows will not know exactly how the horizontal and
vertical size have been set on a CRT.  You can specify correct values
either in the call to @code{windows} or as options: see @code{?windows}.
(Typically these are of the order of 80.)

On one of our systems, the screen height is reported as 240mm, and the
width as 300mm in 1280 x 1024 mode and 320mm in 1280 x 960 and 1600 x 1200
modes.  In fact it is a 21" monitor and 400mm x 300mm!

@node How do I more focus to a graphics window or the console?,  , Circles appear as ovals on screen, Windows Features
@section How do I more focus to a graphics window or the console?

You may want to do this from within a function, for example when calling
@samp{idenitfy} or @samp{readline}.  Use the function
@samp{bringToTop()}.  With its default argument it brings the active
graphics window to the top and gives it focus.  With argument @samp{-1}
it brings the console to the top and gives it focus.

This works for @samp{Rgui.exe} in MDI and SDI modes, and can be used for
graphics windows from @samp{Rterm.exe}.

@newchap{}
@node Workspaces, The R Console and Fonts, Windows Features, Top
@chapter Workspaces


@menu
* My workspace gets saved in a strange place.  How do I stop this?::  
* How do I store my workspace in a different place?::  
* Can I load workspaces saved under Unix/GNU-Linux?::  
@end menu


@node My workspace gets saved in a strange place.  How do I stop this?, How do I store my workspace in a different place?, Workspaces, Workspaces
@section My workspace gets saved in a strange place: how do I stop this?

Have you changed the working directory?: see Q5.2.


@node How do I store my workspace in a different place?, Can I load workspaces saved under Unix/GNU-Linux?, My workspace gets saved in a strange place.  How do I stop this?, Workspaces
@section How do I store my workspace in a different place?

Use the `File | Change Dir' menu item to select a new working
directory: this defaults to the last directory you loaded a file
from.  The workspace is saved in the working directory.  You can also
save a snapshot of the workspace from the `Save Workspace' menu item.

From the command line you can change the working directory by the
function @code{setwd}: see its help page.


@node Can I load workspaces saved under Unix/GNU-Linux?,  , How do I store my workspace in a different place?, Workspaces
@section Can I load workspaces saved under Unix/GNU-Linux?

Yes.  The converse (saving on Windows, loading on Unix) also works on
almost all Unix systems, and workspaces can be interchanged with the
Macintosh port too.



@newchap{}
@node The R Console and Fonts, Building from Source, Workspaces, Top
@chapter The R Console and Fonts


@menu
* I would like to be able to use Japanese fonts::  
* I don't see characters with accents at the R console::  
* The output to the console seems to be delayed::  
* Long lines seem to be truncated.::  
@end menu


@node I would like to be able to use Japanese fonts, I don't see characters with accents at the R console, The R Console and Fonts, The R Console and Fonts
@section I would like to be able to use Japanese fonts

for example, in the console and to annotate graphs.

We believe this is possible by setting suitable fonts in the Rconsole and
Rdevga configuration files (see Q4.2).  You can specify additional fonts in
Rdevga, and use them by

@example
par(font=, font.lab=, font.main=, font.sub=)
@end example

Nineteen fonts are specified (as 1 to 19) by default: you can add to these
(up to 13 more) or replace them.


@node I don't see characters with accents at the R console, The output to the console seems to be delayed, I would like to be able to use Japanese fonts, The R Console and Fonts
@section I don't see characters with accents at the R console, for example in ?text.

You need to specify a font in Rconsole (see Q4.2) that supports Latin1
encoding.  The default, @code{Courier New}, does on our systems, as does
@code{FixedSys}.  This may be a problem in other locales, especially for
non-Western European languages.


@node The output to the console seems to be delayed, Long lines seem to be truncated., I don't see characters with accents at the R console, The R Console and Fonts
@section When using Rgui the output to the console seems to be delayed.

This is deliberate: the console output is buffered and re-written in
chunks to be less distracting.  You can turn buffering off or on from
the Misc menu or the right-click menu: @key{Ctrl-W} toggles the setting.

If you are sourcing R code or writing from a function, there is another
option.  A call to the R function @code{flush.console()} will write out
the buffer and so update the console.


@node Long lines seem to be truncated.,  , The output to the console seems to be delayed, The R Console and Fonts
@section Long lines in the console or pager are truncated.

They only @strong{seem} to be truncated: that $ at the end indicates you
can scroll the window to see the rest of the message.  Use the horizontal
scrollbar or the @key{CTRL+arrow} keys to scroll horizontally.



@newchap{}
@node Building from Source,  , The R Console and Fonts, Top
@chapter Building from Source

@menu
* How can I compile R from source?::  
* How do I include compiled C code?::  
* How do I debug code that I have compiled and dyn.load-ed?::  
* How do I include C++ code?::  
* The output from my C code disappears.::  
* The output from my Fortran code disappears.::  
* The console freezes when my compiled code is running::  
* The Perl scripts don't seem to work under Windows 9x/ME::  
@end menu


@node How can I compile R from source?, How do I include compiled C code?, Building from Source, Building from Source
@section How can I compile R from source?

Get the R sources.  Suppose you want to compile R-@value{RVERSION}.
Start in a directory whose path does not contain spaces, and run

@example
tar zxvf R-@value{RVERSION}.tgz
cd R-@value{RVERSION}
cd src\gnuwin32
@end example
@noindent
Now read the @file{INSTALL} file and set up all the tools needed.  Then you
can just use @code{make}, sit back and wait.  (A complete build takes about
15 minutes on a 300MHz PII with a fast local disc.)

You may need to compile under a case-honouring file system: we found
that a @code{samba}-mounted file system (which maps all file names to lower
case) did not work.


@node  How do I include compiled C code?, How do I debug code that I have compiled and dyn.load-ed?, How can I compile R from source?, Building from Source
@section How do I include compiled C code?

We strongly encourage you to do this @emph{via} building an R package:
see the @emph{`Writing R Extensions'} manual.  In any event you should
install the parts of the R system for building R packages (in
@code{SetupR.exe} or @code{@RWVER@sp.zip}), and get and install the
tools (including Perl) and compilers mentioned in the file
@file{readme.packages} contained therein.  Then you can use
@example
...\bin\Rcmd SHLIB foo.c bar.c
@end example
@noindent
to make @code{foo.dll}.  Use @code{...\bin\Rcmd SHLIB --help} for
further options, or see @code{?SHLIB}.

If you want to use Visual C++, Borland C++ or other compilers, see the
appropriate section in @file{readme.packages}.



@node How do I debug code that I have compiled and dyn.load-ed?, How do I include C++ code?, How do I include compiled C code?, Building from Source
@section How do I debug code that I have compiled and dyn.load-ed?

First, build a version of the R system with debugging information by

@example
make clean
make DEBUG=T
@end example
@noindent

and make a debug version of your package by

@example
make pkgclean-mypkg
make DEBUG=T pkg-mypkg
@end example
@noindent

Then you can debug by

@example
gdb /path/to/@RWVER@/bin/Rgui.exe
@end example
@noindent

However, note

@itemize @bullet
@item gdb will only be able to find the source code if we run in the
location where the source was compiled (@code{@RWVER@/src/gnuwin32} for
the main system, @code{@RWVER@/src/library/mypkg/src} for a package),
unless told otherwise by the @code{directory} command.  It is most
convenient to set a list of code locations via @code{directory}
commands in the file @file{.gdbinit} in the directory from which
@code{gdb} is run.

@item It is only possible to set breakpoints in a DLL after the DLL has
been loaded.  So a way to examine the function @code{tukeyline} in
package @code{eda} might be

@example
     gdb ../../../../bin/Rgui.exe
     (gdb) break WinMain
     (gdb) run
     [ stops with R.dll loaded ]
     (gdb) break R_ReadConsole
     (gdb) continue
     [ stops with console running ]
     (gdb) continue
     Rconsole> library(eda)
     (gdb) break tukeyline
     (gdb) clear R_ReadConsole
     (gdb) continue
@end example

Fortran symbols need an underline appended.

@item Windows has little support for signals, so the usual idea of running a
program under a debugger and sending it a signal to interrupt it and
drop control back to the debugger does not work with @code{mingw32}
version of @code{gdb}.  It does often work with the @code{cygwin} version.

@item We have seen examples in debugging problems with Windows events that
the @code{cygwin gdb} was able to catch but which terminated the
@code{mingw32 gdb}.
@end itemize

If you have an X server available on the PC, there is a version of
@code{DDD} available that runs under the cygwin emulation layer (follow
the links at @uref{http://www.cygwin.com}) and provides a graphical user
interface to @code{gdb}.  Another (Windows-native) GUI for @code{gdb} is
@code{Insight}, part of the latest @code{cygwin} version of @code{gdb}.


@node  How do I include C++ code?, The output from my C code disappears., How do I debug code that I have compiled and dyn.load-ed?, Building from Source
@section  How do I include C++ code?

You need to do two things:

(a) Write a wrapper to export the symbols you want to call from R as
 @code{extern "C"}.

(b) Include the C++ libraries in the link to make the DLL.  Suppose
@file{X.cc} contains your C++ code, and @file{X_main.cc} is the wrapper,
as in the example in @emph{`Writing R Extensions'}.  Then build the DLL by
(@code{gcc})

@example
...\bin\Rcmd SHLIB X.cc X_main.cc
@end example
@noindent
or (VC++, which requires extension @code{.cpp})

@example
cl /MT /c X.cpp X_main.cpp
link /dll /out:X.dll /export:X_main X.obj X_main.obj
@end example
@noindent
or (Borland C++, which also requires extension @code{.cpp})

@example
bcc32 -u- -WDE X.cpp X_main.cpp
@end example
@noindent
and call the entry point(s) in @code{X_R}, such as @code{X_main}.
Construction of static variables will occur when the DLL is loaded, and
destruction when the DLL is unloaded, usually when R terminates.

Note that you will not see the messages from this example in the GUI
console: see the next section.

This example is in package @code{cxx_0.0-x.tar.gz} in the
@file{src/contrib/Devel} section on CRAN, and that can be compiled as a
package in the usual way on Windows.


@node  The output from my C code disappears., The output from my Fortran code disappears., How do I include C++ code?, Building from Source
@section  The output from my C code disappears.  Why?

The @code{Rgui.exe} console is a Windows application: writing to
@code{stdout} or @code{stderr} will not produce output in the
console.  (This will work with @code{Rterm.exe}.)  Use @code{Rprintf} or
@code{REprintf} instead.  These are declared in header file
@file{R_ext/PrtUtil.h}.

Note that output from the console is delayed (@pxref{The output to the
console seems to be delayed}), so that you will not normally see any
output before returning to the R prompt.


@node  The output from my Fortran code disappears., The console freezes when my compiled code is running, The output from my C code disappears., Building from Source
@section  The output from my Fortran code disappears.  Why?

Writing to Fortran output writes to a file, not the @code{Rgui} console.
Use one of the subroutines @code{dblepr}, @code{intpr} or @code{realpr}
documented in the @emph{`Writing R Extensions'} manual.


@node  The console freezes when my compiled code is running, The Perl scripts don't seem to work under Windows 9x/ME, The output from my Fortran code disappears., Building from Source
@section The console freezes when my compiled code is running.

The console, pagers and graphics window all run in the same thread
as the R engine.  To allow the console etc to respond to Windows events,
call @code{R_ProcessEvents()} periodically from your compiled code.
If you want output to be updated on the console, call
@code{R_FlushConsole()} and then @code{R_ProcessEvents()}.


@node The Perl scripts don't seem to work under Windows 9x/ME,  , The console freezes when my compiled code is running, Building from Source
@section The Perl scripts don't seem to work under Windows 9x/ME

This has been seen under some versions of Perl and Windows versions
(95/98/ME) which use a 16-bit shell.  Hopefully rw1030 and later are
more robust in this respect: it @emph{may} help to upgrade your Perl
version (5.6.1, build 628 was current at the time of writing).

@ifhtml
@html
<p><hr WIDTH="100%">
<address>
Last edited 2001 August 30 by Professor B. D. Ripley
<code><a href="mailto:ripley@@stats.ox.ac.uk">ripley@@stats.ox.ac.uk</a></code>
</address>
@end html
@end ifhtml
@ifinfo
@sp 2
Last edited 2001 August 30 by Professor B. D. Ripley <ripley@@stats.ox.ac.uk>
@end ifinfo

@bye

@c Local Variables: ***
@c mode: TeXinfo ***
@c End: ***
