#!/bin/sh
#
# ${R_HOME}/bin/LINK

args=
largs=
Largs=
rpath=

while test -n "${1}"; do
  case "${1}" in
    -avoid-version)
      ;;
    -rpath)
      rpath="${rpath} ${2}"
      shift
      ;;
    -l*)
      largs="${largs} ${1}"
      ;;
    -L*)
      Largs="${Largs} ${1}"
      arg=`echo "${1}" | sed -e 's/^-L//'`
      rpath="${rpath}:${1}"
      ;;
    *)
      args="${args} ${1}"
      ;;
  esac
  shift
done

LD_RUN_PATH="${rpath}"
export LD_RUN_PATH
exec ${args} ${Largs} ${largs}
