#!/bin/sh
pager=${PAGER-"more -s"}
## For the curious: "pager $1" doesn't work in batch, because "more" will
## eat the rest of stdin.  The no-argument version is intended for use at
## the end of a pipeline.
if [ "${1}" != "" ]; then
  exec ${pager} < ${1}
else
  exec ${pager}
fi

### Local Variables: ***
### mode: sh ***
### sh-indentation: 2 ***
### End: ***
