#! /bin/sh
#
# ${R_HOME}/bin/Rcmd

## Shell script wrapper for all R CMD commands.
## For internal use only.

R_CMD="${R_HOME}/bin/Rcmd"
export R_CMD

R_OSTYPE="unix"
export R_OSTYPE

## Add 'share/perl' to the perl library path.
if test -n "${PERL5LIB}"; then
  PERL5LIB="${R_SHARE_DIR}/perl:${PERL5LIB}"
  export PERL5LIB
else
  PERLLIB="${R_SHARE_DIR}/perl:${PERLLIB}"
  export PERLLIB
fi

## Add 'share/texmf' to TeX's input search path.
TEXINPUTS=".:${R_SHARE_DIR}/texmf:${TEXINPUTS}"
export TEXINPUTS

. "${R_HOME}/etc/Renviron"
export `sed 's/^ *#.*//; s/^\(.*\)=.*/\1/' "${R_HOME}/etc/Renviron"`

case "${1}" in
  perl)
    cmd="${PERL}" ;;
  awk)
    cmd="${AWK}"  ;;
  *)
    if test -x "${R_HOME}/bin/${1}"; then
      cmd="${R_HOME}/bin/${1}"
    else
      cmd="${1}"
    fi
    ;;
esac
shift

exec "${cmd}" "${@}"

### Local Variables: ***
### mode: sh ***
### sh-indentation: 2 ***
### End: ***
