#!/bin/sh
# Diff  ``without R version''; f1="-" means STDIN
f1=${1}
f2=${2}
exitstatus=${3}

egrepv='(^Version|^Number of.*:|^Type|^R : Copyright|^Time '
if test -n "`echo $f1 | grep primitive-funs`"; then
  egrepv=${egrepv}'|^\[1\] [19][0-9][0-9])'
else
  egrepv=${egrepv}')'
fi

tmpfile=${TMPDIR:-/tmp}/${f1}-d.${$}
(if test x${f1} = x-
 then	cat - | egrep -v "${egrepv}"
 else		egrep -v "${egrepv}" ${f1}
 fi) > ${tmpfile}
(egrep -v "${egrepv}" ${f2} | diff -bw ${tmpfile} - ) && exitstatus=0

rm -f ${tmpfile}
exit ${exitstatus}
