#   File:       Makefile.mac
#   Target:     bqtlLib
#   Created:    Jago, Nov 2002, Stefano M. Iacus
#
#   This script assumes that R binary already exists in 
#   folder 'src/macintosh/bin'
#
#   Tested with:
#
#   MPW Shell 3.6d7
#   MrC C Compiler 5.0.0d3c1
#   Universal Headers 3.4
#   CarbonLib 1.4
#   MPW release  August 2001+Updates
#
 
DLib			= bqtl
MAKEFILE        = Makefile.mac
¥MondoBuild¥    = {MAKEFILE}  # Make blank to avoid rebuilds when makefile is modified

MacF2C     		=  f2c
F2COpt	        =   -A -E -ec -!R -r8 -w66 -Nq150 -Nx200 -Ns801 -Nc20 -Nn401 -NL200 -NC99 -Nl256
F2CDir       	=  ::::macintosh:f2c:
Includes        = -i ::::include: ¶
				  -i ::::macintosh: ¶
                  -i "{F2CDir}"


Sym-PPC         = -sym off

PPCCOptions     = {Includes} {Sym-PPC} -opt off -includes unix -w 35,2,23,7,29 -shared_lib_export on -d HAVE_CONFIG_H -d Macintosh ¶
					-d TARGET_API_MAC_CARBON=1 -prefix RHeaders.h -align power -enum int
					
### Library directory ###

LibDir     		= :::::library:{DLib}:libs

### Source Files ###

SrcFiles        =  ¶
bc1wt.c ¶
condreg.c ¶
hkreg.c ¶
lapadj.c ¶
normLogLik.c ¶
swapf2.c ¶
twohkf2.c ¶
conCk.c ¶
f2wt2.c ¶
lapWHL.c ¶
llkEm.c ¶
swapbc1.c ¶
twohkbc1.c ¶
upbqtl.c

FortFiles		= 	hessup.f


### Object Files ###

ObjFiles-PPC    =  ¶
bc1wt.o ¶
condreg.o ¶
hkreg.o ¶
lapadj.o ¶
normLogLik.o ¶
swapf2.o ¶
twohkf2.o ¶
conCk.o ¶
f2wt2.o ¶
lapWHL.o ¶
llkEm.o ¶
swapbc1.o ¶
twohkbc1.o ¶
upbqtl.o ¶
hessup.o 

### Libraries ###

LibFiles-PPC    =  ¶
				  "{PPCLibraries}CarbonStdCLib.o" ¶
				  "{SharedLibraries}CarbonLib" ¶
				  "{SharedLibraries}StdCLib" ¶
				  ":::::R"  ¶
				  "{PPCLibraries}PPCCRuntime.o" 




### Default Rules ### 

.o  Ä  .c  {¥MondoBuild¥}
	{PPCC} {depDir}{default}.c -o {targDir}{default}.o {PPCCOptions}

.c Ä .f {¥MondoBuild¥} {FortFiles}
	{MacF2C} {F2COpt} {depDir}{default}.f



### Build Rules ###          

 
{DLib}Lib  ÄÄ  {ObjFiles-PPC} {LibFiles-PPC} {¥MondoBuild¥} 
#create export table
    if `Exists :expvar`
	 delete :expvar
	end
    catenate Å.x > expvar
# checks if modules directory exsists
    if ! `Exists -d "{LibDir}"`
	 echo "Creating libs directory" "{LibDir}" 
     NewFolder "{LibDir}"
    end
# Builds the library
	PPCLink ¶
		-o {LibDir}:{DLib}Lib ¶
		{ObjFiles-PPC} ¶
		{LibFiles-PPC} ¶
		{Sym-PPC} ¶
		-mf -d ¶
		-t 'shlb' ¶
		-c '????' ¶
		-xm s ¶
		-@export expvar     
	
### Required Dependencies ###
hessup.c Ä hessup.f

bc1wt.o      Ä  bc1wt.c 
condreg.o 	 Ä  condreg.c 
hkreg.o 	 Ä  hkreg.c 
lapadj.o 	 Ä  lapadj.c 
normLogLik.o Ä  normLogLik.c 
swapf2.o 	 Ä  swapf2.c 
twohkf2.o 	 Ä  twohkf2.c 
conCk.o 	 Ä  conCk.c 
f2wt2.o 	 Ä  f2wt2.c 
lapWHL.o 	 Ä  lapWHL.c 
llkEm.o 	 Ä  llkEm.c 
swapbc1.o 	 Ä  swapbc1.c 
twohkbc1.o 	 Ä  twohkbc1.c 
upbqtl.o	 Ä  upbqtl.c
hessup.o     Ä  hessup.c


### Optional Dependencies ###
### Build this target to generate "include file" dependencies. ###

Dependencies  Ä  $OutOfDate
	MakeDepend ¶
		-append {MAKEFILE} ¶
		-ignore "{CIncludes}" ¶
		-objdir ":" ¶
		-objext .o ¶
		{Includes} ¶
		{SrcFiles}




