#   File:       Makefile.mac
#   Target:     qtlLib
#   Created:    Jago, Dec 2001, Stefano M. Iacus
#   Updated:	Jago, Jan 2002
#
#   This script assumes that R binary already exists in 
#   the R root folder
#
#   Tested with:
#
#   MPW Shell 3.6d7
#   MrC C Compiler 5.0.0d3c1
#   Universal Headers 3.4
#   CarbonLib 1.4
#   MPW release  August 2001+Updates

DLib            = qtl
MAKEFILE        = Makefile.mac
¥MondoBuild¥    = {MAKEFILE}  # Make blank to avoid rebuilds when makefile is modified

Includes        = -i ::::include: ¶
				  -i ::::macintosh: ¶

Sym-PPC         = -sym off

PPCCOptions     = {Includes} {Sym-PPC} -opt off -includes unix -w 35,2,7,23 -shared_lib_export on -d HAVE_CONFIG_H -d Macintosh ¶
					-d TARGET_API_MAC_CARBON=1 -prefix RHeaders.h -align power -enum int

### Library directory ###

LibDir     		= :::::library:{DLib}:libs

### Source Files ###

SrcFiles        =  ¶
discan.c ¶
hmm_4way.c ¶
hmm_bc.c ¶
hmm_f2.c ¶
hmm_f2ss.c ¶
hmm_main.c ¶
info.c ¶
scanone_em.c ¶
scanone_em_covar.c ¶
scanone_hk.c ¶
scanone_imp.c ¶
scanone_mr.c ¶
scanone_np.c ¶
scantwo_em.c ¶
scantwo_hk.c ¶
scantwo_imp.c ¶
scantwo_mr.c ¶
util.c ¶
vbscan.c				  
				  

### Object Files ###

ObjFiles-PPC    =  ¶
discan.o ¶
hmm_4way.o ¶
hmm_bc.o ¶
hmm_f2.o ¶
hmm_f2ss.o ¶
hmm_main.o ¶
info.o ¶
scanone_em.o ¶
scanone_em_covar.o ¶
scanone_hk.o ¶
scanone_imp.o ¶
scanone_mr.o ¶
scanone_np.o ¶
scantwo_em.o ¶
scantwo_hk.o ¶
scantwo_imp.o ¶
scantwo_mr.o ¶
util.o ¶
vbscan.o				  
						  
### Libraries ###

LibFiles-PPC    =  ¶
  				  "{PPCLibraries}CarbonStdCLib.o" ¶
				  "{SharedLibraries}CarbonLib" ¶
				  "{SharedLibraries}StdCLib" ¶
				  ":::::R"  ¶
				  "{PPCLibraries}PPCCRuntime.o" 
   

### Default Rules ### 

.o  Ä  .c  {¥MondoBuild¥}
	{PPCC} {depDir}{default}.c -o {targDir}{default}.o {PPCCOptions}


### Build Rules ###


{DLib}Lib  ÄÄ  {ObjFiles-PPC} {LibFiles-PPC} {¥MondoBuild¥} 
#create export table
    if `Exists :expvar`
	 delete :expvar
	end
    catenate Å.x > expvar
# checks if modules directory exsists
    if ! `Exists -d "{LibDir}"`
	 echo "Creating libs directory" "{LibDir}" 
     NewFolder "{LibDir}"
    end
# Builds the library
	PPCLink ¶
		-o {LibDir}:{DLib}Lib ¶
		{ObjFiles-PPC} ¶
		{LibFiles-PPC} ¶
		{Sym-PPC} ¶
		-mf -d ¶
		-t 'shlb' ¶
		-c '????' ¶
		-xm s ¶
		-@export expvar     
# Removing mass
 #  Delete   ‰.x
 #	Delete   ‰.o 
 #  Delete :expvar


### Required Dependencies ###
 
discan.o Ä             discan.c
hmm_4way.o Ä		   hmm_4way.c
hmm_bc.o Ä			   hmm_bc.c
hmm_f2.o Ä			   hmm_f2.c
hmm_f2ss.o Ä		   hmm_f2ss.c
hmm_main.o Ä		   hmm_main.c
info.o Ä			   info.c
scanone_em.o Ä		   scanone_em.c
scanone_em_covar.o Ä   scanone_em_covar.c
scanone_hk.o Ä		   scanone_hk.c
scanone_imp.o Ä		   scanone_imp.c
scanone_mr.o Ä		   scanone_mr.c
scanone_np.o Ä		   scanone_np.c
scantwo_em.o Ä		   scantwo_em.c
scantwo_hk.o Ä		   scantwo_hk.c
scantwo_imp.o Ä		   scantwo_imp.c
scantwo_mr.o Ä		   scantwo_mr.c
util.o Ä			   util.c
vbscan.o Ä			   vbscan.c




### Optional Dependencies ###
### Build this target to generate "include file" dependencies. ###

Dependencies  Ä  $OutOfDate
	MakeDepend ¶
		-append {MAKEFILE} ¶
		-ignore "{CIncludes}" ¶
		-objdir ":" ¶
		-objext .o ¶
		{Includes} ¶
		{SrcFiles}



