include ../../gnuwin32/MkRules

all: makeMakedeps ga.a

CFLAGS=-I. -I../../gnuwin32 -I../../include $(OPTFLAGS) \
  -DINDLL -DR_DLL_BUILD -DENABLE_NLS=1

SOURCES=$(wildcard *.c)
OBJECTS=$(foreach i, $(SOURCES), $(basename $i).o)

ga.a: $(OBJECTS)

clean:
	$(RM) *.o *.a *~ \#*\# *.d Makedeps

# Dependencies
DEPS=$(SOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
