#-*- Makefile -*-
#
# ${R_HOME}/tests/Makefile.win

all check: test-all-basics
check-devel: check test-all-devel
check-all: check-devel test-Packages-Recommended
check-recommended: test-Packages-Recommended

# for R_PKGS_BASE
include ../src/gnuwin32/MkRules
include ../share/make/vars.mk

srcdir = .
top_srcdir = ..
top_builddir = $(RHOME)
include Makefile.common

RHOME = $(shell ../src/gnuwin32/Rpwd.exe ..)# must be absolute path
R = $(RHOME)/bin/Rterm --vanilla LC_ALL=C SRCDIR=. R_DEFAULT_PACKAGES=
R2 = $(RHOME)/bin/Rterm --vanilla SRCDIR=. R_DEFAULT_PACKAGES=
R3 = $(RHOME)/bin/Rcmd check
RDIFF = $(RHOME)/bin/R CMD Rdiff
RVAL_IF_DIFF=0
## suppress fancy quotes for diff-ing
RDCONV = LC_ALL=C $(RHOME)/bin/Rcmd Rdconv

ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
MK = $(MAKE) -f Makefile.win
TAR = tar

test-src-reg-1 = reg-tests-1.R reg-tests-2.R reg-IO.R reg-IO2.R \
  reg-plot.R reg-S4.R reg-win.R

all-basic-tests = Examples Specific Reg Internet
all-devel-tests = Docs IsAs Random Demo Primitive Regexp Segfault \
   Standalone Packages

internet.Rout2:
	-@$(R) --internet2 < internet.R > internet.Rout2 2>&1 || \
	  echo " testing --internet2 failed"

## <NOTE>
## These depend on an internet connection, and the sites being up.
## So allow this to fail: it may be slow doing so.
test-Internet:
	@$(RM) -f internet.Rout internet.Rout2
	@$(ECHO) "running tests of Internet and socket functions ..."
	@$(ECHO) "  expect some differences"
	-@$(MK) $(test-out-internet) RVAL_IF_DIFF=0 || \
	  $(ECHO) " testing standard internet connectivity failed"
	@$(MK) internet.Rout2 RVAL_IF_DIFF=0
	-@diff internet.Rout internet.Rout2

test-Standalone:
	@echo "testing building standalone Rmath"
	@$(MAKE) -C ../src/nmath/standalone -f Makefile.win all test || exit 1
	@$(MAKE) -C ../src/nmath/standalone -f Makefile.win clean


clean:
	@rm -f *.Rout *.Rout.fail internet.Rout2 Rplots.ps reg-plot.ps \
	  reg-plot-latin1.ps reg-tests-?.ps \
	  $(test-src-auto) R-exts.* R-exts_res.rc R-intro.R Makedeps
	@rm -rf *.Rcheck myTst* myLib Rprofmem.out
	@rm -f FALSE* PACKAGES* .R .tex mirrors.html Rplots*.pdf
	@rm -f testit.txt testit.html testit.tex testit-Ex.R
	@rm -f ver10.txt ver10.html ver10.tex ver10-Ex.R
	@rm -f ver11.txt ver11.html ver11.tex ver11-Ex.R
	@rm -rf Packages
	@$(MK) -C Embedding clean

distclean: clean
	@$(MK) -C Examples $@


install-tests:
	@for f in $(INSTFILES); do \
	  cp $(srcdir)/$${f} "$(INST_TO)"; \
	done
