#!/bin/sh
# Diff  ``without R version''
f1=$1
f2=$2
#$perlne="'print if /^Version|^Number of.*:/'"
#perl -ne "$perlne" $f1 ....
egrepv='(^Version|^Number of.*:|^Type|^R : Copyright'
if test -n "`grep primitive-funs $f1`"
 then egrepv=$egrepv'|^\[1\] [19][0-9][0-9])'
 else egrepv=$egrepv')'
fi

egrep -v "$egrepv" $f1 > /tmp/${f1}-d.$$
exitstatus=1
(egrep -v "$egrepv" $f2 | diff -bw /tmp/${f1}-d.$$ -) && exitstatus=0

rm /tmp/${f1}-d.$$

exit $exitstatus
