bibentry(bibtype = "Book",
         key = "R:Becker+Chambers+Wilks:1988",
         author = c(person(given = c("Richard", "A."),
                           family = "Becker"),
                    person(given = c("John", "M."),
                           family = "Chambers"),
                    person(given = c("Allan", "R."),
                           family = "Wilks")),
         title = "The New {S} Language",
         publisher = "Chapman and Hall/CRC",
         year = "1988",
         address = "London")

bibentry(bibtype = "Article",
         key = "R:Campbell:1980",
         title = "On Temme’s Algorithm for the Modified Bessel Function of the Third Kind",
         volume = "6",
         .issn = "1557-7295",
         doi = "10.1145/355921.355928",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "J. B.",
                         family = "Campbell"),
         year = "1980",
         month = "dec",
         pages = "581--586")

bibentry(bibtype = "Article",
         key = "R:Campbell:1979",
         title = "Bessel functions Jv(x) and Yv(x) of real order and real argument",
         volume = "18",
         .issn = "0010-4655",
         doi = "10.1016/0010-4655(79)90030-4",
         number = "1",
         journal = "Computer Physics Communications",
         publisher = "Elsevier BV",
         author = person(given = "J.B.",
                         family = "Campbell"),
         year = "1979",
         month = "sep",
         pages = "133--142")

bibentry(bibtype = "Book",
         key = "R:Chambers+Hastie:1992",
         author = c(person(given = c("John", "M."),
                           family = "Chambers"),
                    person(given = c("Trevor", "J."),
                           family = "Hastie")),
         title = "Statistical Models in {S}",
         publisher = "Chapman \\& Hall",
         year = "1992",
         address = "London",
         isbn = "9780412830402",
         publisherurl = "http://www.crcpress.com/product/isbn/9780412830402")

bibentry(bibtype = "Book",
         key = "R:Chambers:1998",
         author = person(given = c("John", "M."),
                         family = "Chambers"),
         title = "Programming with Data",
         publisher = "Springer",
         year = "1998",
         address = "New York",
         isbn = "978-0-387-98503-9",
         publisherurl = "https://www.springer.com/978-0-387-98503-9")

bibentry(bibtype = "Book",
         key = "R:Chambers:2008",
         author = person(given = c("John", "M."),
                         family = "Chambers"),
         title = "Software for Data Analysis: Programming with {R}",
         publisher = "Springer",
         year = "2008",
         address = "New York",
         isbn = "978-0-387-75935-7",
         url = "http://statweb.stanford.edu/~jmc4/Rbook/",
         publisherurl = "https://www.springer.com/book/978-0-387-75935-7")

bibentry(bibtype = "Article",
         key = "R:Cody:1983",
         title = "Algorithm 597: sequence of modified Bessel functions of the first kind",
         volume = "9",
         .issn = "1557-7295",
         doi = "10.1145/357456.357462",
         number = "2",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "W. J.",
                         family = "Cody"),
         year = "1983",
         month = "jun",
         pages = "242--245")

bibentry(bibtype = "Article",
         key = "R:Cody:1988",
         title = "Algorithm 665: Machar: a subroutine to dynamically determined machine parameters",
         volume = "14",
         .issn = "1557-7295",
         doi = "10.1145/50063.51907",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "W. J.",
                         family = "Cody"),
         year = "1988",
         month = "dec",
         pages = "303--311")

bibentry(bibtype = "Article",
         key = "R:Goldberg:1991",
         title = "What every computer scientist should know about floating-point arithmetic",
         volume = "23",
         .issn = "1557-7341",
         doi = "10.1145/103162.103163",
         number = "1",
         journal = "ACM Computing Surveys",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "David",
                         family = "Goldberg"),
         year = "1991",
         month = "mar",
         pages = "5--48")

bibentry(bibtype = "Article",
         key = "R:Hill+Wichmann:1982",
         title = "Algorithm AS 183: An Efficient and Portable Pseudo-Random Number Generator",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347988",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "I. D.",
                           family = "Hill"),
                    person(given = "B. A.",
                           family = "Wichmann")),
         year = "1982",
         pages = "188")

bibentry(bibtype = "Book",
         key = "R:Knuth:1998",
         title = "The Art of Computer Programming, Volume 3: Sorting and Searching",
         author = person(given = c("Donald", "E."),
                         family = "Knuth"),
         year = "1998",
         edition = "2nd",
         publisher = "Addison-Wesley Professional")

bibentry(bibtype = "Article",
         key = "R:L_Ecuyer:1999",
         title = "Good Parameters and Implementations for Combined Multiple Recursive Random Number Generators",
         volume = "47",
         .issn = "1526-5463",
         doi = "10.1287/opre.47.1.159",
         number = "1",
         journal = "Operations Research",
         publisher = "Institute for Operations Research and the Management Sciences (INFORMS)",
         author = person(given = "Pierre",
                         family = "L'Ecuyer"),
         year = "1999",
         month = "feb",
         pages = "159--164")

bibentry(bibtype = "Article",
         key = "R:Marsaglia+Zaman:1994",
         title = "Some portable very-long-period random number generators",
         volume = "8",
         .issn = "0894-1866",
         doi = "10.1063/1.168514",
         number = "1",
         journal = "Computers in Physics",
         publisher = "AIP Publishing",
         author = c(person(given = "George",
                           family = "Marsaglia"),
                    person(given = "Arif",
                           family = "Zaman")),
         year = "1994",
         month = "jan",
         pages = "117--121")

bibentry(bibtype = "Article",
         key = "R:Mielke:1967",
         title = "Note on Some Squared Rank Tests with Existing Ties",
         volume = "9",
         .issn = "1537-2723",
         doi = "10.1080/10618600.2000.10474900",
         number = "2",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = person(given = "Paul W.",
                         family = "Mielke"),
         year = "1967",
         month = "may",
         pages = "312--314",
         .doi = "10.2307/1390947")

bibentry(bibtype = "Article",
         key = "R:Muller+Box:1958",
         title = "A Note on the Generation of Random Normal Deviates",
         volume = "29",
         .issn = "0003-4851",
         doi = "10.1214/aoms/1177706645",
         number = "2",
         journal = "The Annals of Mathematical Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = "Mervin E.",
                           family = "Muller"),
                    person(given = "G. E. P.",
                           family = "Box")),
         year = "1958",
         month = "jun",
         pages = "610--611")

bibentry(bibtype = "Article",
         key = "R:Sedgewick:1986",
         title = "A new upper bound for Shellsort",
         volume = "7",
         .issn = "0196-6774",
         doi = "10.1016/0196-6774(86)90001-5",
         number = "2",
         journal = "Journal of Algorithms",
         publisher = "Elsevier BV",
         author = person(given = "Robert",
                         family = "Sedgewick"),
         year = "1986",
         month = "jun",
         pages = "159--173")

bibentry(bibtype = "Article",
         key = "R:Simard+L_Ecuyer:2007",
         title = "TestU01: A C library for empirical testing of random number generators",
         volume = "33",
         .issn = "1557-7295",
         doi = "10.1145/1268776.1268777",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "Richard",
                           family = "Simard"),
                    person(given = "Pierre",
                           family = "L'Ecuyer")),
         year = "2007",
         month = "aug",
         pages = "1--40")

bibentry(bibtype = "Article",
         key = "R:Singleton:1969",
         title = "Algorithm 347: an efficient algorithm for sorting with minimal storage [M1]",
         volume = "12",
         .issn = "1557-7317",
         doi = "10.1145/362875.362901",
         number = "3",
         journal = "Communications of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "Richard C.",
                         family = "Singleton"),
         year = "1969",
         month = "mar",
         pages = "185--187")

bibentry(bibtype = "Article",
         key = "R:Sookne:1973",
         title = "Bessel functions I and J of complex argument and integer order",
         volume = "77B",
         .issn = "0098-8979",
         doi = "10.1007/BF00153065",
         number = "3 and 4",
         journal = "Journal of Research of the National Bureau of Standards, Section B: Mathematical Sciences",
         publisher = "National Institute of Standards and Technology (NIST)",
         author = person(given = "David J.",
                         family = "Sookne"),
         year = "1973",
         month = "jul",
         pages = "111",
         .doi = "10.1007/bf00153065")

bibentry(bibtype = "Article",
         key = "R:Sutherland+Wyatt+Olshen:1989",
         title = "Gait Analysis and the Bootstrap",
         volume = "17",
         .issn = "0090-5364",
         doi = "10.1080/01621459.1976.10480965",
         number = "4",
         journal = "The Annals of Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = "David H.",
                           family = "Sutherland"),
                    person(given = "Marilynn P.",
                           family = "Wyatt"),
                    person(given = "Richard A.",
                           family = "Olshen"),
                    person(given = "Edmund N.",
                           family = "Biden")),
         year = "1989",
         month = "dec",
         .doi = "10.2307/2286857")

bibentry(bibtype = "Article",
         key = "R:Temme:1976",
         title = "On the numerical evaluation of the ordinary bessel function of the second kind",
         volume = "21",
         .issn = "0021-9991",
         doi = "10.1016/0021-9991(76)90032-2",
         number = "3",
         journal = "Journal of Computational Physics",
         publisher = "Elsevier BV",
         author = person(given = "N.M",
                         family = "Temme"),
         year = "1976",
         month = "jul",
         pages = "343--350")

bibentry(bibtype = "Article",
         key = "R:Traub+Jenkins:1972",
         title = "Algorithm 419: zeros of a complex polynomial [C2]",
         volume = "15",
         .issn = "1557-7317",
         doi = "10.1145/361254.361262",
         number = "2",
         journal = "Communications of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "J. F.",
                           family = "Traub"),
                    person(given = "M. A.",
                           family = "Jenkins")),
         year = "1972",
         month = "feb",
         pages = "97--99")
