bibentry(bibtype = "Article",
         key = "R:Cohen:1980",
         title = "On the graphical display of the significant components in two-way contingency tables",
         volume = "9",
         .issn = "0361-0926",
         doi = "10.1080/03610928008827940",
         number = "10",
         journal = "Communications in Statistics - Theory and Methods",
         publisher = "Informa UK Limited",
         author = person(given = "Ayala",
                         family = "Cohen"),
         year = "1980",
         pages = "1025--1041")

bibentry(bibtype = "Article",
         key = "R:Gabriel:1971",
         title = "The Biplot Graphic Display of Matrices with Application to Principal Component Analysis",
         volume = "58",
         .issn = "1464-3510",
         doi = "10.1080/01621459.1976.10480965",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "K. R.",
                         family = "Gabriel"),
         year = "1971",
         pages = "453--467",
         .doi = "10.2307/2286857")

bibentry(bibtype = "Article",
         key = "R:Hochberg:1988",
         title = "A Sharper Bonferroni Procedure for Multiple Tests of Significance",
         volume = "75",
         .issn = "1464-3510",
         doi = "10.1093/biomet/26.4.404",
         number = "4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Yosef",
                         family = "Hochberg"),
         year = "1988",
         pages = "800--802",
         .doi = "10.2307/2331986")

bibentry(bibtype = "Article",
         key = "R:Hommel:1988",
         title = "A Stagewise Rejective Multiple Test Procedure Based on a Modified Bonferroni Test",
         volume = "75",
         .issn = "1464-3510",
         doi = "10.1080/01621459.1994.10476460",
         number = "2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "G.",
                         family = "Hommel"),
         year = "1988",
         pages = "383--386",
         .doi = "10.2307/2291215")

bibentry(bibtype = "Article",
         key = "R:Horst+Gorman+Presmanes_Hill:2022",
         title = "Palmer Archipelago Penguins Data in the palmerpenguins R Package - An Alternative to Anderson’s Irises",
         volume = "14",
         .issn = "2073-4859",
         doi = "10.1080/07350015.1993.10509934",
         number = "1",
         journal = "The R Journal",
         publisher = "The R Foundation",
         author = c(person(given = c("Allison", "M."),
                           family = "Horst",
                           comment = c(ORCID = "0000-0002-6047-5564")),
                    person(given = c("Kristen", "B."),
                           family = "Gorman",
                           comment = c(ORCID = "0000-0002-0258-9264")),
                    person(given = "Alison",
                           family = "Presmanes Hill",
                           comment = c(ORCID = "0000-0002-8082-1890"))),
         year = "2022",
         month = "jun",
         pages = "244--254",
         .doi = "10.2307/1391308")

bibentry(bibtype = "Misc",
         key = "R:Kaye+Turner+Gorman:2025",
         doi = "10.1093/biomet/65.2.243",
         author = c(person(given = "Ella",
                           family = "Kaye"),
                    person(given = "Heather",
                           family = "Turner"),
                    person(given = c("Kristen", "B."),
                           family = "Gorman"),
                    person(given = "Allison",
                           family = "Horst"),
                    person(given = "Alison",
                           family = "Hill")),
         title = "Preparing the Palmer Penguins Data for the datasets Package in R",
         publisher = "Zenodo",
         year = "2025",
         copyright = "Creative Commons Attribution 4.0 International",
         .doi = "10.2307/2335202")

bibentry(bibtype = "Article",
         key = "R:Meyer+Zeileis+Hornik:2006",
         title = "The Strucplot Framework: Visualizing Multi-way Contingency Tables withvcd",
         volume = "17",
         .issn = "1548-7660",
         doi = "10.18637/jss.v017.i03",
         number = "3",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "David",
                           family = "Meyer"),
                    person(given = "Achim",
                           family = "Zeileis"),
                    person(given = "Kurt",
                           family = "Hornik")),
         year = "2006")

bibentry(bibtype = "Article",
         key = "R:Pearson+Clopper:1934",
         title = "The Use of Confidence or Fiducial Limits Illustrated in the Case of the Binomial",
         volume = "26",
         .issn = "1464-3510",
         doi = "10.1093/biomet/65.2.243",
         number = "4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "E. S.",
                           family = "Pearson"),
                    person(given = "C. J.",
                           family = "Clopper")),
         year = "1934",
         pages = "404--413",
         .doi = "10.2307/2335202")
