bibentry(bibtype = "Book",
         key = "R:Box+Hunter+Hunter:2005",
         title = "Statistics for Experimenters: Design, Innovation, and Discovery",
         author = c(person(given = c("George", "Edward", "Pelham"),
                           family = "Box"),
                    person(given = c("J.", "Stuart"),
                           family = "Hunter"),
                    person(given = c("William", "G."),
                           family = "Hunter")),
         isbn = "978-0-471-71813-0",
         lccn = "2004063780",
         series = "Wiley Series in Probability and Statistics",
         year = "2005",
         publisher = "Wiley")

bibentry(bibtype = "Article",
         key = "R:Cohen:1980",
         title = "On the Graphical Display of the Significant Components in Two-way Contingency Tables",
         volume = "9",
         .issn = "0361-0926",
         doi = "10.1080/03610928008827940",
         number = "10",
         journal = "Communications in Statistics - Theory and Methods",
         publisher = "Informa UK Limited",
         author = person(given = "Ayala",
                         family = "Cohen"),
         year = "1980",
         pages = "1025--1041")

bibentry(bibtype = "Article",
         key = "R:Emerson:1998",
         author = person(given = c("J.", "W."),
                         family = "Emerson"),
         title = "Mosaic Displays in {S-PLUS}: A General Implementation and a Case Study",
         journal = "ASA Statistical Computing and Statistical Graphics Newsletter",
         year = "1998",
         volume = "9",
         number = "1",
         pages = "17--23")

bibentry(bibtype = "InProceedings",
         key = "R:Friendly:1992",
         author = person(given = "Michael",
                         family = "Friendly"),
         title = "Graphical Methods for Categorical Data",
         booktitle = "Proceedings of the Seventeenth Annual SAS User's Group International Conference",
         year = "1992",
         pages = "1367--1373",
         publisher = "SAS Publishing",
         url = "http://datavis.ca/papers/sugi/sugi17.pdf",
         publisherurl = "https://support.sas.com/resources/papers/proceedings-archive/SUGI92/Sugi-92-233\\%20Friendly.pdf")

bibentry(bibtype = "Article",
         key = "R:Friendly:1994",
         title = "Mosaic Displays for Multi-Way Contingency Tables",
         volume = "89",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1994.10476460",
         number = "425",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "Michael",
                         family = "Friendly"),
         year = "1994",
         month = "mar",
         pages = "190--200",
         .doi = "10.2307/2291215")

bibentry(bibtype = "Article",
         key = "R:Hartigan+Kleiner:1984",
         title = "A Mosaic of Television Ratings",
         volume = "38",
         .issn = "1537-2731",
         doi = "10.1080/00031305.1984.10482869",
         number = "1",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = c("J.", "A."),
                           family = "Hartigan"),
                    person(given = "Beat",
                           family = "Kleiner")),
         year = "1984",
         month = "feb",
         pages = "32--35",
         .doi = "10.2307/2683556")

bibentry(bibtype = "Article",
         key = "R:Hummel:1996",
         author = person(given = "J.",
                         family = "Hummel"),
         title = "Linked Bar Charts: Analysing Categorical Data Graphically",
         journal = "Computational Statistics",
         year = "1996",
         volume = "11",
         pages = "23--33")

bibentry(bibtype = "Article",
         key = "R:Meyer+Zeileis+Hornik:2006",
         title = "The Strucplot Framework: Visualizing Multi-way Contingency Tables withvcd",
         volume = "17",
         .issn = "1548-7660",
         doi = "10.18637/jss.v017.i03",
         number = "3",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "David",
                           family = "Meyer",
                           comment = c(ORCID = "0000-0002-5196-3048")),
                    person(given = "Achim",
                           family = "Zeileis",
                           comment = c(ORCID = "0000-0003-0918-3766")),
                    person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911"))),
         year = "2006")

bibentry(bibtype = "Article",
         key = "R:Murrell:1999",
         title = "Layouts: A Mechanism for Arranging Plots on a Page",
         volume = "8",
         .issn = "1537-2715",
         doi = "10.1080/10618600.1999.10474805",
         number = "1",
         journal = "Journal of Computational and Graphical Statistics",
         publisher = "Informa UK Limited",
         author = person(given = c("Paul", "R."),
                         family = "Murrell",
                         comment = c(ORCID = "0000-0002-3224-8858")),
         year = "1999",
         month = "mar",
         pages = "121--134",
         .doi = "10.2307/1390924")

bibentry(bibtype = "Book",
         key = "R:Murrell:2005",
         title = "{R} Graphics",
         author = person(given = "Paul",
                         family = "Murrell",
                         comment = c(ORCID = "0000-0002-3224-8858")),
         isbn = "9781420035025",
         lccn = "2005046278",
         series = "Chapman & Hall/CRC The R Series",
         year = "2005",
         publisher = "CRC Press")

bibentry(bibtype = "Article",
         key = "R:Schilling+Watkins:1994",
         title = "A Suggestion for Sunflower Plots",
         volume = "48",
         .issn = "1537-2731",
         doi = "10.1080/00031305.1994.10476086",
         number = "4",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Mark", "F."),
                           family = "Schilling"),
                    person(given = c("Ann", "E."),
                           family = "Watkins")),
         year = "1994",
         month = "nov",
         pages = "303--305",
         .doi = "10.2307/2684839")

bibentry(bibtype = "Book",
         key = "R:Wild+Seber:1999",
         title = "Chance Encounters: A First Course in Data Analysis and Inference",
         author = c(person(given = c("Christopher", "J."),
                           family = "Wild"),
                    person(given = c("George", "A.", "F."),
                           family = "Seber")),
         isbn = "0-471-32936-3",
         year = "1999",
         publisher = "John Wiley and Sons")
