bibentry(bibtype = "Article",
         key = "R:Eddy:1977a",
         title = "A New Convex Hull Algorithm for Planar Sets",
         volume = "3",
         .issn = "1557-7295",
         doi = "10.1145/355759.355766",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = c("William", "F."),
                         family = "Eddy"),
         year = "1977",
         month = "dec",
         pages = "398--403")

bibentry(bibtype = "Article",
         key = "R:Eddy:1977b",
         title = "\\I{Algorithm 523}: \\I{CONVEX}, A New Convex Hull Algorithm for Planar Sets [Z]",
         volume = "3",
         .issn = "1557-7295",
         doi = "10.1145/355759.355768",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = c("William", "F."),
                         family = "Eddy"),
         year = "1977",
         month = "dec",
         pages = "411--412")

bibentry(bibtype = "InCollection",
         key = "R:Emerson+Strenio:1983",
         author = c(person(given = c("J.", "D"),
                           family = "Emerson"),
                    person(given = "J.",
                           family = "Strenio")),
         title = "Boxplots and Batch Comparison",
         booktitle = "Understanding Robust and Exploratory Data Analysis",
         publisher = "Wiley",
         year = "1983",
         editor = c(person(given = "Frederick",
                           family = "Mosteller"),
                    person(given = c("David", "Caster"),
                           family = "Hoaglin"),
                    person(given = c("John", "Wilder"),
                           family = "Tukey")),
         chapter = "3")

bibentry(bibtype = "Article",
         key = "R:Freedman+Diaconis:1981",
         title = "On the Histogram as a Density Estimator: \\eqn{L_2}{L_2} theory",
         volume = "57",
         .issn = "1432-2064",
         doi = "10.1007/BF01025868",
         number = "4",
         journal = "Zeitschrift für Wahrscheinlichkeitstheorie und Verwandte Gebiete",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "David",
                           family = "Freedman"),
                    person(given = "Persi",
                           family = "Diaconis")),
         year = "1981",
         month = "dec",
         pages = "453--476",
         .doi = "10.1007/bf01025868")

bibentry(bibtype = "Article",
         key = "R:Mcgill+Tukey+Larsen:1978",
         title = "Variations of Box Plots",
         volume = "32",
         .issn = "1537-2731",
         doi = "10.1080/00031305.1978.10479236",
         number = "1",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = "Robert",
                           family = "Mcgill"),
                    person(given = c("John", "Wilder"),
                           family = "Tukey"),
                    person(given = c("Wayne", "A."),
                           family = "Larsen")),
         year = "1978",
         month = "feb",
         pages = "12--16",
         .doi = "10.2307/2683468")

bibentry(bibtype = "Article",
         key = "R:Murrell+Ihaka:2000",
         title = "An Approach to Providing Mathematical Annotation in Plots",
         volume = "9",
         .issn = "1537-2715",
         doi = "10.1080/10618600.2000.10474900",
         number = "3",
         journal = "Journal of Computational and Graphical Statistics",
         publisher = "Informa UK Limited",
         author = c(person(given = "Paul",
                           family = "Murrell",
                           comment = c(ORCID = "0000-0002-3224-8858")),
                    person(given = "Ross",
                           family = "Ihaka")),
         year = "2000",
         month = "sep",
         pages = "582--599",
         .doi = "10.2307/1390947")

bibentry(bibtype = "Article",
         key = "R:Murrell+Ripley:2006",
         author = c(person(given = "Paul",
                           family = "Murrell",
                           comment = c(ORCID = "0000-0002-3224-8858")),
                    person(given = "Brian",
                           family = "Ripley")),
         title = "Non-Standard Fonts in \\I{PostScript} and \\I{PDF} graphics",
         journal = "R News",
         year = "2006",
         volume = "6",
         number = "2",
         pages = "41--47",
         month = "May",
         url = "https://www.r-project.org/doc/Rnews/Rnews_2006-2.pdf")

bibentry(bibtype = "Article",
         key = "R:Scott:1979",
         title = "On Optimal and Data-based Histograms",
         volume = "66",
         .issn = "1464-3510",
         doi = "10.1093/biomet/66.3.605",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("David", "W."),
                         family = "Scott"),
         year = "1979",
         pages = "605--610",
         .doi = "10.2307/2335182")

bibentry(bibtype = "Article",
         key = "R:Sturges:1926",
         title = "The Choice of a Class Interval",
         volume = "21",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1926.10502161",
         number = "153",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = c("Herbert", "A."),
                         family = "Sturges"),
         year = "1926",
         month = "mar",
         pages = "65--66")

bibentry(bibtype = "Article",
         key = "R:Zeileis+Fisher+Hornik:2020",
         title = "colorspace: A Toolbox for Manipulating and Assessing Colors and Palettes",
         volume = "96",
         .issn = "1548-7660",
         doi = "10.18637/jss.v096.i01",
         number = "1",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "Achim",
                           family = "Zeileis",
                           comment = c(ORCID = "0000-0003-0918-3766")),
                    person(given = c("Jason", "C."),
                           family = "Fisher",
                           comment = c(ORCID = "0000-0001-9032-8912")),
                    person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "Ross",
                           family = "Ihaka"),
                    person(given = c("Claire", "D."),
                           family = "McWhite",
                           comment = c(ORCID = "0000-0001-7346-3047")),
                    person(given = "Paul",
                           family = "Murrell",
                           comment = c(ORCID = "0000-0002-3224-8858")),
                    person(given = "Reto",
                           family = "Stauffer",
                           comment = c(ORCID = "0000-0002-3798-5507")),
                    person(given = c("Claus", "O."),
                           family = "Wilke",
                           comment = c(ORCID = "0000-0002-7470-9261"))),
         year = "2020")

bibentry(bibtype = "Article",
         key = "R:Zeileis+Hornik+Murrell:2009",
         title = "Escaping \\I{RGBland}: Selecting Colors for Statistical Graphics",
         volume = "53",
         .issn = "0167-9473",
         doi = "10.1016/j.csda.2008.11.033",
         number = "9",
         journal = "Computational Statistics &amp; Data Analysis",
         publisher = "Elsevier BV",
         author = c(person(given = "Achim",
                           family = "Zeileis",
                           comment = c(ORCID = "0000-0003-0918-3766")),
                    person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "Paul",
                           family = "Murrell",
                           comment = c(ORCID = "0000-0002-3224-8858"))),
         year = "2009",
         month = "jul",
         pages = "3259--3270")

