bibentry(bibtype = "Article",
         key = "R:De_Matteis+Pagnutti:1993",
         title = "Long-range correlation analysis of the Wichmann-Hill random number generator",
         volume = "3",
         .issn = "1573-1375",
         doi = "10.1080/01621459.1927.10502953",
         number = "2",
         journal = "Statistics and Computing",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "A.",
                           family = "De Matteis"),
                    person(given = "S.",
                           family = "Pagnutti")),
         year = "1993",
         month = "jun",
         pages = "67--70",
         .doi = "10.2307/2276774")

bibentry(bibtype = "Article",
         key = "R:Eddy:1977a",
         title = "A New Convex Hull Algorithm for Planar Sets",
         volume = "3",
         .issn = "1557-7295",
         doi = "10.1145/355759.355766",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "William F.",
                         family = "Eddy"),
         year = "1977",
         month = "dec",
         pages = "398--403")

bibentry(bibtype = "Article",
         key = "R:Eddy:1977b",
         title = "Algorithm 523: CONVEX, A New Convex Hull Algorithm for Planar Sets [Z]",
         volume = "3",
         .issn = "1557-7295",
         doi = "10.1145/355759.355768",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "W. F.",
                         family = "Eddy"),
         year = "1977",
         month = "dec",
         pages = "411--412")

bibentry(bibtype = "Article",
         key = "R:Fisher+Ihaka+Zeileis:2020",
         title = "colorspace: A Toolbox for Manipulating and Assessing Colors and Palettes",
         volume = "96",
         .issn = "1548-7660",
         doi = "10.18637/jss.v096.i01",
         number = "1",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "Jason C.",
                           family = "Fisher"),
                    person(given = "Ross",
                           family = "Ihaka"),
                    person(given = "Achim",
                           family = "Zeileis"),
                    person(given = "Paul",
                           family = "Murrell"),
                    person(given = "Claus O.",
                           family = "Wilke"),
                    person(given = "Kurt",
                           family = "Hornik"),
                    person(given = "Claire D.",
                           family = "McWhite"),
                    person(given = "Reto",
                           family = "Stauffer")),
         year = "2020")

bibentry(bibtype = "Article",
         key = "R:Hornik+Zeileis+Murrell:2009",
         title = "Escaping RGBland: Selecting colors for statistical graphics",
         volume = "53",
         .issn = "0167-9473",
         doi = "10.1016/j.csda.2008.11.033",
         number = "9",
         journal = "Computational Statistics &amp; Data Analysis",
         publisher = "Elsevier BV",
         author = c(person(given = "Kurt",
                           family = "Hornik"),
                    person(given = "Achim",
                           family = "Zeileis"),
                    person(given = "Paul",
                           family = "Murrell")),
         year = "2009",
         month = "jul",
         pages = "3259--3270")

bibentry(bibtype = "Article",
         key = "R:Jones:1980",
         title = "Maximum Likelihood Fitting of ARMA Models to Time Series With Missing Observations",
         volume = "22",
         .issn = "1537-2723",
         doi = "10.1007/BF01025868",
         number = "3",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = person(given = "Richard H.",
                         family = "Jones"),
         year = "1980",
         month = "aug",
         pages = "389--395",
         .doi = "10.1007/bf01025868")

bibentry(bibtype = "Misc",
         key = "R:Gorman:2020a",
         doi = "10.1007/BF01025868",
         author = c(person(given = "Palmer Station Antarctica LTER"),
                    person(given = "Kristen",
                           family = "Gorman")),
         language = "en",
         title = "Structural size measurements and isotopic signatures of foraging among adult male and female Adélie penguins (Pygoscelis adeliae) nesting along the Palmer Archipelago near Palmer Station, 2007-2009",
         publisher = "Environmental Data Initiative",
         year = "2020",
         .doi = "10.1007/bf01025868")

bibentry(bibtype = "Misc",
         key = "R:Gorman:2020b",
         doi = "10.1090/s0025-5718-1965-0178586-1",
         author = c(person(given = "Palmer Station Antarctica LTER"),
                    person(given = "Kristen",
                           family = "Gorman")),
         language = "en",
         title = "Structural size measurements and isotopic signatures of foraging among adult male and female Gentoo penguin (Pygoscelis papua) nesting along the Palmer Archipelago near Palmer Station, 2007-2009",
         publisher = "Environmental Data Initiative",
         year = "2020",
         .doi = "10.2307/2003354")

bibentry(bibtype = "Misc",
         key = "R:Gorman:2020c",
         doi = "10.1080/01621459.1981.10477729",
         author = c(person(given = "Palmer Station Antarctica LTER"),
                    person(given = "Kristen",
                           family = "Gorman")),
         language = "en",
         title = "Structural size measurements and isotopic signatures of foraging among adult male and female Chinstrap penguin (Pygoscelis antarctica) nesting along the Palmer Archipelago near Palmer Station, 2007-2009",
         publisher = "Environmental Data Initiative",
         year = "2020",
         .doi = "10.2307/2287576")

bibentry(bibtype = "Article",
         key = "R:Murrell+Ripley:2006",
         author = c(person(given = "Paul",
                           family = "Murrell"),
                    person(given = "Brian",
                           family = "Ripley")),
         title = "Non-Standard Fonts in {PostScript} and {PDF} graphics",
         journal = "R News",
         year = "2006",
         volume = "6",
         number = "2",
         pages = "41--47",
         month = "May",
         url = "https://www.r-project.org/doc/Rnews/Rnews_2006-2.pdf")

bibentry(bibtype = "Article",
         key = "R:Ramage+Kinderman:1976",
         title = "Computer Generation of Normal Random Variables",
         volume = "71",
         .issn = "1537-274X",
         doi = "10.1080/00031305.1996.10473566",
         number = "356",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "J. G.",
                           family = "Ramage"),
                    person(given = "A. J.",
                           family = "Kinderman")),
         year = "1976",
         month = "dec",
         pages = "893--896",
         .doi = "10.2307/2684934")

bibentry(bibtype = "Article",
         key = "R:Sturges:1926",
         title = "The Choice of a Class Interval",
         volume = "21",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1926.10502161",
         number = "153",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "Herbert A.",
                         family = "Sturges"),
         year = "1926",
         month = "mar",
         pages = "65--66")
