bibentry(bibtype = "Book",
         key = "R:Chambers:2016",
         title = "Extending {R}",
         author = person(given = c("John", "M."),
                         family = "Chambers"),
         isbn = "9781498775717",
         lccn = "20160421",
         series = "Chapman & Hall/CRC The R Series",
         year = "2016",
         publisher = "CRC Press")
