bibentry(bibtype = "Book",
         key = "R:Agresti:1990",
         author = person("Alan", "Agresti"),
         title = "Categorical Data Analysis",
         year = "1990",
         publisher = "Wiley",
         address = "New York",
         isbn = "978-0471853015")

bibentry(bibtype = "Book",
         key = "R:Agresti:2002",
         author = person("Alan", "Agresti"),
         title = "Categorical Data Analysis",
         year = "2002",
         edition = "Second",
         publisher = "Wiley",
         address = "New York",
         isbn = "978-0471360933")

bibentry(bibtype = "Article",
         key = "R:Bartlett:1937a",
         title = "The Statistical Conception of Mental Factors",
         volume = "28",
         .issn = "0373-2460",
         doi = "10.1111/j.2044-8295.1937.tb00863.x",
         number = "1",
         journal = "British Journal of Psychology. General Section",
         publisher = "Wiley",
         author = person(given = c("Maurice", "Stevenson"),
                         family = "Bartlett"),
         year = "1937",
         month = "jul",
         pages = "97--104")

bibentry(bibtype = "Article",
         key = "R:Bartlett:1937b",
         volume = "160",
         .issn = "2053-9169",
         doi = "10.1098/rspa.1937.0109",
         number = "901",
         journal = "Proceedings of the Royal Society of London. Series A - Mathematical and Physical Sciences",
         publisher = "The Royal Society",
         year = "1937",
         month = "may",
         pages = "268--282",
         title = "Properties of Sufficiency and Statistical Tests",
         author = person(given = c("Maurice", "Stevenson"),
                         family = "Bartlett"))

bibentry(bibtype = "Article",
         key = "R:Bauer:1972",
         title = "Constructing Confidence Sets Using Rank Statistics",
         volume = "67",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1972.10481279",
         number = "339",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = c("David", "F."),
                         family = "Bauer"),
         year = "1972",
         month = "sep",
         pages = "687--690")

bibentry(bibtype = "Article",
         key = "R:Benjamini+Hochberg:1995",
         title = "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing",
         volume = "57",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1995.tb02031.x",
         number = "1",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "Yoav",
                           family = "Benjamini"),
                    person(given = "Yosef",
                           family = "Hochberg")),
         year = "1995",
         month = "jan",
         pages = "289--300")

bibentry(bibtype = "Article",
         key = "R:Benjamini+Yekutieli:2001",
         title = "The Control of the False Discovery Rate in Multiple Testing under Dependency",
         volume = "29",
         .issn = "0090-5364",
         doi = "10.1214/aos/1013699998",
         number = "4",
         journal = "The Annals of Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = "Yoav",
                           family = "Benjamini"),
                    person(given = "Daniel",
                           family = "Yekutieli")),
         year = "2001",
         month = "aug")

bibentry(bibtype = "Article",
         key = "R:Best+Roberts:1975",
         title = "{Algorithm AS 89}: The Upper Tail Probabilities of {Spearman}’s Rho",
         volume = "24",
         .issn = "0035-9254",
         doi = "10.2307/2347111",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("D.", "J."),
                           family = "Best"),
                    person(given = c("D.", "E."),
                           family = "Roberts")),
         year = "1975",
         pages = "377")

bibentry(bibtype = "Article",
         key = "R:Birnbaum+Tingey:1951",
         title = "One-Sided Confidence Contours for Probability Distribution Functions",
         volume = "22",
         .issn = "0003-4851",
         doi = "10.1214/aoms/1177729550",
         number = "4",
         journal = "The Annals of Mathematical Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = c("Z.", "W."),
                           family = "Birnbaum"),
                    person(given = c("Fred", "H."),
                           family = "Tingey")),
         year = "1951",
         month = "dec",
         pages = "592--596")

bibentry(bibtype = "Article",
         key = "R:Box+Pierce:1970",
         title = "Distribution of Residual Autocorrelations in Autoregressive-Integrated Moving Average Time Series Models",
         volume = "65",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1970.10481180",
         number = "332",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = c("George", "Edward", "Pelham"),
                           family = "Box"),
                    person(given = c("David", "A."),
                           family = "Pierce")),
         year = "1970",
         month = "dec",
         pages = "1509--1526",
         .doi = "10.2307/2284333")

bibentry(bibtype = "Book",
         key = "R:Brockwell+Davis:1991",
         title = "Time Series: Theory and Methods",
         author = c(person(given = c("Peter", "J."),
                           family = "Brockwell"),
                    person(given = c("Richard", "A."),
                           family = "Davis")),
         isbn = "9780387974293",
         lccn = "96224172",
         series = "Springer Series in Statistics",
         year = "1991",
         publisher = "Springer New York")

bibentry(bibtype = "Article",
         key = "R:Brown+Levy:1994",
         title = "Certification of {Algorithm 708}: Significant-digit Computation of the Incomplete {Beta}",
         volume = "20",
         .issn = "1557-7295",
         doi = "10.1145/192115.192155",
         number = "3",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = c("Barry", "W."),
                           family = "Brown"),
                    person(given = c("Lawrence", "B."),
                           family = "Levy")),
         year = "1994",
         month = "sep",
         pages = "393--397")

bibentry(bibtype = "Article",
         key = "R:Byrd+Lu+Nocedal:1995",
         title = "A Limited Memory Algorithm for Bound Constrained Optimization",
         volume = "16",
         .issn = "1095-7197",
         doi = "10.1137/0916069",
         number = "5",
         journal = "SIAM Journal on Scientific Computing",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = c(person(given = c("Richard", "H."),
                           family = "Byrd"),
                    person(given = "Peihuang",
                           family = "Lu"),
                    person(given = "Jorge",
                           family = "Nocedal"),
                    person(given = "Ciyou",
                           family = "Zhu")),
         year = "1995",
         month = "sep",
         pages = "1190--1208")

bibentry(bibtype = "Article",
         key = "R:Bélisle:1992",
         title = "Convergence Theorems for a Class of Simulated Annealing Algorithms on $\\mathbb{R}^d$",
         volume = "29",
         .issn = "1475-6072",
         doi = "10.2307/3214721",
         number = "4",
         journal = "Journal of Applied Probability",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = c("Claude", "J.", "P."),
                         family = "Bélisle"),
         year = "1992",
         month = "dec",
         pages = "885--895")

bibentry(bibtype = "Article",
         key = "R:Cailliez:1983",
         title = "The Analytical Solution of the Additive Constant Problem",
         volume = "48",
         .issn = "1860-0980",
         doi = "10.1007/BF02294026",
         number = "2",
         journal = "Psychometrika",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = "Francis",
                         family = "Cailliez"),
         year = "1983",
         month = "jun",
         pages = "305--308",
         .doi = "10.1007/bf02294026")

bibentry(bibtype = "Article",
         key = "R:Clarkson+Fan+Joe:1993",
         title = "A Remark on {Algorithm 643}: {FEXACT}: An Algorithm for Performing {Fisher}’s Exact Test in $r \\times c$ Contingency Tables",
         volume = "19",
         .issn = "1557-7295",
         doi = "10.1145/168173.168412",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = c("Douglas", "B."),
                           family = "Clarkson"),
                    person(given = "Yuan-an",
                           family = "Fan"),
                    person(given = "Harry",
                           family = "Joe")),
         year = "1993",
         month = "dec",
         pages = "484--488")

bibentry(bibtype = "Article",
         key = "R:Cleveland:1979",
         title = "Robust Locally Weighted Regression and Smoothing Scatterplots",
         volume = "74",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1979.10481038",
         number = "368",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = c("William", "S."),
                         family = "Cleveland"),
         year = "1979",
         month = "dec",
         pages = "829--836")

bibentry(bibtype = "Article",
         key = "R:Cleveland:1981",
         title = "{LOWESS}: A Program for Smoothing Scatterplots by Robust Locally Weighted Regression",
         volume = "35",
         .issn = "0003-1305",
         doi = "10.2307/2683591",
         number = "1",
         journal = "The American Statistician",
         publisher = "JSTOR",
         author = person(given = c("William", "S."),
                         family = "Cleveland"),
         year = "1981",
         month = "feb",
         pages = "54")

bibentry(bibtype = "Article",
         key = "R:Cleveland+Cleveland+McRae:1990",
         author = c(person(given = c("Robert", "B."),
                           family = "Cleveland"),
                    person(given = c("William", "S."),
                           family = "Cleveland"),
                    person(given = c("Jean", "E."),
                           family = "McRae"),
                    person(given = "Irma",
                           family = "Terpenning")),
         journal = "Journal of Official Statistics",
         pages = "3--73",
         title = "{STL}: A Seasonal-Trend Decomposition Procedure Based on {Loess}",
         volume = "6",
         year = "1990")

bibentry(bibtype = "Article",
         key = "R:Clopper+Pearson:1934",
         title = "The Use of Confidence or Fiducial Limits Illustrated in the Case of the Binomial",
         volume = "26",
         .issn = "1464-3510",
         doi = "10.1093/biomet/26.4.404",
         number = "4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = c("C.", "J."),
                           family = "Clopper"),
                    person(given = c("Egon", "Sharpe"),
                           family = "Pearson")),
         year = "1934",
         pages = "404--413",
         .doi = "10.2307/2331986")

bibentry(bibtype = "Article",
         key = "R:Conover+Johnson+Johnson:1981",
         title = "A Comparative Study of Tests for Homogeneity of Variances, with Applications to the Outer Continental Shelf Bidding Data",
         volume = "23",
         .issn = "1537-2723",
         doi = "10.1080/00401706.1981.10487680",
         number = "4",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = c(person(given = c("W.", "J."),
                           family = "Conover"),
                    person(given = c("Mark", "E."),
                           family = "Johnson"),
                    person(given = c("Myrle", "M."),
                           family = "Johnson")),
         year = "1981",
         month = "nov",
         pages = "351--361",
         .doi = "10.2307/1268225")

bibentry(bibtype = "Article",
         key = "R:Cooley+Tukey:1965",
         title = "An Algorithm for the Machine Calculation of Complex {Fourier} Series",
         volume = "19",
         .issn = "1088-6842",
         doi = "10.1090/s0025-5718-1965-0178586-1",
         number = "90",
         journal = "Mathematics of Computation",
         publisher = "American Mathematical Society (AMS)",
         author = c(person(given = c("James", "W."),
                           family = "Cooley"),
                    person(given = c("John", "Wilder"),
                           family = "Tukey")),
         year = "1965",
         pages = "297--301",
         .doi = "10.2307/2003354")

bibentry(bibtype = "Article",
         key = "R:Copenhaver+Holland:1988",
         title = "Computation of the Distribution of the Maximum Studentized Range Statistic with Application to Multiple Significance Testing of Simple Effects",
         volume = "30",
         .issn = "1563-5163",
         doi = "10.1080/00949658808811082",
         number = "1",
         journal = "Journal of Statistical Computation and Simulation",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Margaret", "Diponzio"),
                           family = "Copenhaver"),
                    person(given = "Burt",
                           family = "Holland")),
         year = "1988",
         month = "aug",
         pages = "1--15")

bibentry(bibtype = "Article",
         key = "R:Cran+Martin+Thomas:1977",
         title = "{Remark AS R19} and {Algorithm AS 109}: A Remark on Algorithms {AS 63}: The Incomplete {Beta} Integral {AS 64}: Inverse of the Incomplete {Beta} Function Ratio",
         volume = "26",
         .issn = "0035-9254",
         doi = "10.2307/2346887",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("G.", "W."),
                           family = "Cran"),
                    person(given = c("K.", "J."),
                           family = "Martin"),
                    person(given = c("G.", "E."),
                           family = "Thomas")),
         year = "1977",
         pages = "111")

bibentry(bibtype = "Article",
         key = "R:Diaconis+Mosteller:1989",
         title = "Methods for Studying Coincidences",
         volume = "84",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1989.10478847",
         number = "408",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "Persi",
                           family = "Diaconis"),
                    person(given = "Frederick",
                           family = "Mosteller")),
         year = "1989",
         month = "dec",
         pages = "853--861")

bibentry(bibtype = "Article",
         key = "R:Didonato+Morris:1992",
         title = "{Algorithm 708}: Significant Digit Computation of the Incomplete {Beta} Function Ratios",
         volume = "18",
         .issn = "1557-7295",
         doi = "10.1145/131766.131776",
         number = "3",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = c("Armido", "R."),
                           family = "Didonato"),
                    person(given = c("Alfred", "H."),
                           family = "Morris")),
         year = "1992",
         month = "sep",
         pages = "360--373")

bibentry(bibtype = "Article",
         key = "R:Dougherty+Edelman+Hyman:1989",
         title = "Nonnegativity-, Monotonicity-, or Convexity-preserving Cubic and Quintic {Hermite} Interpolation",
         volume = "52",
         .issn = "1088-6842",
         doi = "10.1090/S0025-5718-1989-0962209-1",
         number = "186",
         journal = "Mathematics of Computation",
         publisher = "American Mathematical Society (AMS)",
         author = c(person(given = c("Randall", "L."),
                           family = "Dougherty"),
                    person(given = c("Alan", "S."),
                           family = "Edelman"),
                    person(given = c("James", "M."),
                           family = "Hyman")),
         year = "1989",
         pages = "471--494",
         .doi = "10.1090/s0025-5718-1989-0962209-1")

bibentry(bibtype = "Article",
         key = "R:Feller:1948",
         title = "On the {Kolmogorov}-{Smirnov} Limit Theorems for Empirical Distributions",
         volume = "19",
         .issn = "0003-4851",
         doi = "10.1214/aoms/1177730243",
         number = "2",
         journal = "The Annals of Mathematical Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = person(given = "W.",
                         family = "Feller"),
         year = "1948",
         month = "jun",
         pages = "177--189")

bibentry(bibtype = "Article",
         key = "R:Fisher:1935",
         title = "The Logic of Inductive Inference",
         volume = "98",
         .issn = "0952-8385",
         doi = "10.2307/2342435",
         number = "1",
         journal = "Journal of the Royal Statistical Society",
         publisher = "JSTOR",
         author = person(given = c("Ronald", "A."),
                         family = "Fisher"),
         year = "1935",
         pages = "39--82")

bibentry(bibtype = "Article",
         key = "R:Fisher:1962",
         title = "Confidence Limits for a Cross-Product Ratio",
         volume = "4",
         .issn = "0004-9581",
         doi = "10.1111/j.1467-842X.1962.tb00285.x",
         number = "1",
         journal = "Australian Journal of Statistics",
         publisher = "Wiley",
         author = person(given = c("Ronald", "A."),
                         family = "Fisher"),
         year = "1962",
         month = "apr",
         pages = "41",
         .doi = "10.1111/j.1467-842x.1962.tb00285.x")

bibentry(bibtype = "Book",
         key = "R:Fisher:1970",
         author = person(given = c("Ronald", "A."),
                         family = "Fisher"),
         title = "Statistical Methods for Research Workers",
         year = "1970",
         publisher = "Oliver & Boyd")

bibentry(bibtype = "Article",
         key = "R:Fletcher+Reeves:1964",
         title = "Function Minimization by Conjugate Gradients",
         volume = "7",
         .issn = "1460-2067",
         doi = "10.1093/comjnl/7.2.149",
         number = "2",
         journal = "The Computer Journal",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "R.",
                           family = "Fletcher"),
                    person(given = c("C.", "M."),
                           family = "Reeves")),
         year = "1964",
         month = "feb",
         pages = "149--154")

bibentry(bibtype = "Article",
         key = "R:Forgy:1965",
         author = person(given = c("E.", "W."),
                         family = "Forgy"),
         title = "Cluster Analysis of Multivariate Data: Efficiency vs Interpretability of Classifications",
         journal = "Biometrics",
         year = "1965",
         volume = "12",
         pages = "768--769")

bibentry(bibtype = "Article",
         key = "R:Frick:1990",
         title = "{Algorithm AS R84}: A Remark on {Algorithm AS 226}: Computing Non-Central {Beta} Probabilities",
         volume = "39",
         .issn = "0035-9254",
         doi = "10.2307/2347780",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "H.",
                         family = "Frick"),
         year = "1990",
         pages = "311")

bibentry(bibtype = "Article",
         key = "R:Friedman+Stuetzle:1981",
         title = "Projection Pursuit Regression",
         volume = "76",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1981.10477729",
         number = "376",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Jerome", "H."),
                           family = "Friedman"),
                    person(given = "Werner",
                           family = "Stuetzle")),
         year = "1981",
         month = "dec",
         pages = "817--823",
         .doi = "10.2307/2287576")

bibentry(bibtype = "Article",
         key = "R:Fritsch+Carlson:1980",
         title = "Monotone Piecewise Cubic Interpolation",
         volume = "17",
         .issn = "1095-7170",
         doi = "10.1137/0717021",
         number = "2",
         journal = "SIAM Journal on Numerical Analysis",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = c(person(given = c("F.", "N."),
                           family = "Fritsch"),
                    person(given = c("R.", "E."),
                           family = "Carlson")),
         year = "1980",
         month = "apr",
         pages = "238--246")

bibentry(bibtype = "Article",
         key = "R:Gabriel+Odoroff:1990",
         title = "Biplots in Biomedical Research",
         volume = "9",
         .issn = "1097-0258",
         doi = "10.1002/sim.4780090502",
         number = "5",
         journal = "Statistics in Medicine",
         publisher = "Wiley",
         author = c(person(given = c("K.", "Ruben"),
                           family = "Gabriel"),
                    person(given = c("Charles", "L."),
                           family = "Odoroff")),
         year = "1990",
         month = "may",
         pages = "469--485")

bibentry(bibtype = "Article",
         key = "R:Gabriel:1971",
         title = "The Biplot Graphic Display of Matrices with Application to Principal Component Analysis",
         volume = "58",
         .issn = "1464-3510",
         doi = "10.1093/biomet/58.3.453",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("K.", "R."),
                         family = "Gabriel"),
         year = "1971",
         pages = "453--467",
         .doi = "10.2307/2334381")

bibentry(bibtype = "Article",
         key = "R:Gardner+Harvey+Phillips:1980",
         title = "{Algorithm AS 154}: An Algorithm for Exact Maximum Likelihood Estimation of Autoregressive-Moving Average Models by Means of {Kalman} Filtering",
         volume = "29",
         .issn = "0035-9254",
         doi = "10.2307/2346910",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "G.",
                           family = "Gardner"),
                    person(given = c("A.", "C."),
                           family = "Harvey"),
                    person(given = c("G.", "D.", "A."),
                           family = "Phillips")),
         year = "1980",
         pages = "311")

bibentry(bibtype = "Article",
         key = "R:Gower:1966",
         title = "Some Distance Properties of Latent Root and Vector Methods Used in Multivariate Analysis",
         volume = "53",
         .issn = "0006-3444",
         doi = "10.2307/2333639",
         number = "3/4",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = c("J.", "C."),
                         family = "Gower"),
         year = "1966",
         month = "dec",
         pages = "325")

bibentry(bibtype = "Article",
         key = "R:Haberman:1972",
         title = "{Algorithm AS 51}: Log-Linear Fit for Contingency Tables",
         volume = "21",
         .issn = "0035-9254",
         doi = "10.2307/2346506",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("S.", "J."),
                         family = "Haberman"),
         year = "1972",
         pages = "218")

bibentry(bibtype = "Article",
         key = "R:Hartigan+Wong:1979",
         title = "{Algorithm AS 136}: A $K$-Means Clustering Algorithm",
         volume = "28",
         .issn = "0035-9254",
         doi = "10.2307/2346830",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("J.", "A."),
                           family = "Hartigan"),
                    person(given = c("M.", "A."),
                           family = "Wong")),
         year = "1979",
         pages = "100")

bibentry(bibtype = "Article",
         key = "R:Harvey+McKenzie:1982",
         title = "{Algorithm AS 182}: Finite Sample Prediction from {ARIMA} Processes",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347987",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("A.", "C."),
                           family = "Harvey"),
                    person(given = c("C.", "R."),
                           family = "McKenzie")),
         year = "1982",
         pages = "180")

bibentry(bibtype = "Article",
         key = "R:Harville:1974",
         title = "Bayesian Inference for Variance Components Using Only Error Contrasts",
         volume = "61",
         .issn = "1464-3510",
         doi = "10.1093/biomet/61.2.383",
         number = "2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("David", "A."),
                         family = "Harville"),
         year = "1974",
         pages = "383--385",
         .doi = "10.2307/2334370")

bibentry(bibtype = "Article",
         key = "R:Hendrickson+White:1964",
         title = "{PROMAX}}: A Quick Method for Rotation to Oblique Simple Structure",
         volume = "17",
         .issn = "0950-561X",
         doi = "10.1111/j.2044-8317.1964.tb00244.x",
         number = "1",
         journal = "British Journal of Statistical Psychology",
         publisher = "Wiley",
         author = c(person(given = c("Alan", "E."),
                           family = "Hendrickson"),
                    person(given = c("Paul", "Owen"),
                           family = "White")),
         year = "1964",
         month = "may",
         pages = "65--70")

bibentry(bibtype = "Article",
         key = "R:Hill:1970",
         title = "{ACM} {Algorithm 395}: Student’s $t$-Distribution",
         volume = "13",
         .issn = "1557-7317",
         doi = "10.1145/355598.355599",
         number = "10",
         journal = "Communications of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = c("G.", "W."),
                         family = "Hill"),
         year = "1970",
         month = "oct",
         pages = "617--619")

bibentry(bibtype = "Article",
         key = "R:Hill:1981",
         title = "Remark on “{Algorithm 396}: Student’s $t$-Quantiles [S14]”",
         volume = "7",
         .issn = "1557-7295",
         doi = "10.1145/355945.355956",
         number = "2",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = c("G.", "W."),
                         family = "Hill"),
         year = "1981",
         month = "jun",
         pages = "250--251")

bibentry(bibtype = "Article",
         key = "R:Hinkley:1975",
         title = "On Power Transformations to Symmetry",
         volume = "62",
         .issn = "1464-3510",
         doi = "10.1093/biomet/62.1.101",
         number = "1",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("David", "V."),
                         family = "Hinkley"),
         year = "1975",
         pages = "101--111",
         .doi = "10.2307/2334491")

bibentry(bibtype = "Article",
         key = "R:Hochberg:1988",
         title = "A Sharper {Bonferroni} Procedure for Multiple Tests of Significance",
         volume = "75",
         .issn = "1464-3510",
         doi = "10.1093/biomet/75.4.800",
         number = "4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Yosef",
                         family = "Hochberg"),
         year = "1988",
         pages = "800--802",
         .doi = "10.2307/2336325")

bibentry(bibtype = "Article",
         key = "R:Holm:1979",
         author = person(given = "Sture",
                         family = "Holm"),
         title = "A Simple Sequentially Rejective Multiple Test Procedure",
         journal = "Scandinavian Journal of Statistics",
         year = "1979",
         volume = "6",
         pages = "65--70",
         url = "https://www.jstor.org/stable/4615733")

bibentry(bibtype = "Article",
         key = "R:Holt:2004",
         title = "Forecasting Seasonals and Trends by Exponentially Weighted Moving Averages",
         volume = "20",
         .issn = "0169-2070",
         doi = "10.1016/j.ijforecast.2003.09.015",
         number = "1",
         journal = "International Journal of Forecasting",
         publisher = "Elsevier BV",
         author = person(given = c("Charles", "C."),
                         family = "Holt"),
         year = "2004",
         month = "jan",
         pages = "5--10")

bibentry(bibtype = "Article",
         key = "R:Hommel:1988",
         title = "A Stagewise Rejective Multiple Test Procedure Based on a Modified {Bonferroni} Test",
         volume = "75",
         .issn = "1464-3510",
         doi = "10.1093/biomet/75.2.383",
         number = "2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "G.",
                         family = "Hommel"),
         year = "1988",
         pages = "383--386",
         .doi = "10.2307/2336190")

bibentry(bibtype = "Article",
         key = "R:Hope:1968",
         title = "A Simplified {Monte Carlo} Significance Test Procedure",
         volume = "30",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1968.tb00759.x",
         number = "3",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("Adery C.", "A."),
                         family = "Hope"),
         year = "1968",
         month = "sep",
         pages = "582--598")

bibentry(bibtype = "Article",
         key = "R:Hotelling:1936",
         title = "Relations Between Two Sets of Variates",
         volume = "28",
         .issn = "1464-3510",
         doi = "10.1093/biomet/28.3-4.321",
         number = "3--4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Harold",
                         family = "Hotelling"),
         year = "1936",
         month = "dec",
         pages = "321--377")

bibentry(bibtype = "Article",
         key = "R:Hyman:1983",
         title = "Accurate Monotonicity Preserving Cubic Interpolation",
         volume = "4",
         .issn = "2168-3417",
         doi = "10.1137/0904045",
         number = "4",
         journal = "SIAM Journal on Scientific and Statistical Computing",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = person(given = c("James", "M."),
                         family = "Hyman"),
         year = "1983",
         month = "dec",
         pages = "645--654")

bibentry(bibtype = "Article",
         key = "R:Hyndman+Fan:1996",
         title = "Sample Quantiles in Statistical Packages",
         volume = "50",
         .issn = "1537-2731",
         doi = "10.1080/00031305.1996.10473566",
         number = "4",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Rob", "J."),
                           family = "Hyndman"),
                    person(given = "Yanan",
                           family = "Fan")),
         year = "1996",
         month = "nov",
         pages = "361--365",
         .doi = "10.2307/2684934")

bibentry(bibtype = "Article",
         key = "R:Härdle+Steiger:1995",
         title = "{Algorithm AS 296}: Optimal Median Smoothing",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986349",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "Wolfgang",
                           family = "Härdle"),
                    person(given = "W.",
                           family = "Steiger")),
         year = "1995",
         pages = "258")

bibentry(bibtype = "Article",
         key = "R:Johnstone+Velleman:1985",
         title = "The Resistant Line and Related Regression Methods",
         volume = "80",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1985.10478222",
         number = "392",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Iain", "M."),
                           family = "Johnstone"),
                    person(given = c("Paul", "F."),
                           family = "Velleman")),
         year = "1985",
         month = "dec",
         pages = "1041--1054",
         .doi = "10.2307/2288572")

bibentry(bibtype = "Article",
         key = "R:Jones:1980",
         title = "Maximum Likelihood Fitting of {ARMA} Models to Time Series With Missing Observations",
         volume = "22",
         .issn = "1537-2723",
         doi = "10.1080/00401706.1980.10486171",
         number = "3",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = person(given = c("Richard", "H."),
                         family = "Jones"),
         year = "1980",
         month = "aug",
         pages = "389--395",
         .doi = "10.2307/1268324")

bibentry(bibtype = "Article",
         key = "R:Kaiser:1958",
         title = "The Varimax Criterion for Analytic Rotation in Factor Analysis",
         volume = "23",
         .issn = "1860-0980",
         doi = "10.1007/BF02289233",
         number = "3",
         journal = "Psychometrika",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = c("Henry", "F."),
                         family = "Kaiser"),
         year = "1958",
         month = "sep",
         pages = "187--200",
         .doi = "10.1007/bf02289233")

bibentry(bibtype = "Article",
         key = "R:Kendall:1938",
         title = "A New Measure of Rank Correlation",
         volume = "30",
         .issn = "1464-3510",
         doi = "10.1093/biomet/30.1-2.81",
         number = "1--2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("Maurice", "George"),
                         family = "Kendall"),
         year = "1938",
         month = "jun",
         pages = "81--93")

bibentry(bibtype = "Article",
         key = "R:Kendall:1945",
         title = "The Treatment of Ties in Ranking Problems",
         volume = "33",
         .issn = "1464-3510",
         doi = "10.1093/biomet/33.3.239",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = c("Maurice", "George"),
                         family = "Kendall"),
         year = "1945",
         pages = "239--251")

bibentry(bibtype = "Article",
         key = "R:Lam:1995",
         title = "{Remark AS R95}: A Remark on {Algorithm AS 226}: Computing Non-Central {Beta} Probabilities",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986147",
         number = "4",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("Ming", "Long"),
                         family = "Lam"),
         year = "1995",
         pages = "551")

bibentry(bibtype = "Article",
         key = "R:Langford:2006",
         title = "Quartiles in Elementary Statistics",
         volume = "14",
         .issn = "1069-1898",
         doi = "10.1080/10691898.2006.11910589",
         number = "3",
         journal = "Journal of Statistics Education",
         publisher = "Informa UK Limited",
         author = person(given = "Eric",
                         family = "Langford"),
         year = "2006",
         month = "jan")

bibentry(bibtype = "Article",
         key = "R:Lenth:1987",
         title = "{Algorithm AS 226}: Computing Noncentral {Beta} Probabilities",
         volume = "36",
         .issn = "0035-9254",
         doi = "10.2307/2347558",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("Russell", "V."),
                         family = "Lenth"),
         year = "1987",
         pages = "241")

bibentry(bibtype = "Article",
         key = "R:Lenth:1989",
         title = "{Algorithm AS 243}: Cumulative Distribution Function of the Non-Central $t$ Distribution",
         volume = "38",
         .issn = "0035-9254",
         doi = "10.2307/2347693",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("Russell", "V."),
                         family = "Lenth"),
         year = "1989",
         pages = "185")

bibentry(bibtype = "Article",
         key = "R:Ljung+Box:1978",
         title = "On a Measure of Lack of Fit in Time Series Models",
         volume = "65",
         .issn = "1464-3510",
         doi = "10.1093/biomet/65.2.297",
         number = "2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = c("G.", "M."),
                           family = "Ljung"),
                    person(given = c("George", "Edward", "Pelham"),
                           family = "Box")),
         year = "1978",
         month = "aug",
         pages = "297--303",
         .doi = "10.2307/2335207")

bibentry(bibtype = "Article",
         key = "R:Makkonen+Pajari:2014",
         title = "Defining Sample Quantiles by the True Rank Probability",
         volume = "2014",
         .issn = "1687-9538",
         doi = "10.1155/2014/326579",
         journal = "Journal of Probability and Statistics",
         publisher = "Wiley",
         author = c(person(given = "Lasse",
                           family = "Makkonen",
                           comment = c(ORCID = "0000-0002-3924-7882")),
                    person(given = "Matti",
                           family = "Pajari")),
         year = "2014",
         pages = "1--6")

bibentry(bibtype = "Article",
         key = "R:Mardia:1978",
         title = "Some Properties of Classical Multi-dimensional Scaling",
         volume = "7",
         .issn = "1532-415X",
         doi = "10.1080/03610927808827707",
         number = "13",
         journal = "Communications in Statistics - Theory and Methods",
         publisher = "Informa UK Limited",
         author = person(given = c("K.", "V."),
                         family = "Mardia"),
         year = "1978",
         month = "jan",
         pages = "1233--1241")

bibentry(bibtype = "Article",
         key = "R:Marsaglia+Tsang+Wang:2003",
         title = "Evaluating {Kolmogorov}’s Distribution",
         volume = "8",
         .issn = "1548-7660",
         doi = "10.18637/jss.v008.i18",
         number = "18",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "George",
                           family = "Marsaglia"),
                    person(given = c("Wai", "Wan"),
                           family = "Tsang"),
                    person(given = "Jingbo",
                           family = "Wang")),
         year = "2003")

bibentry(bibtype = "Article",
         key = "R:McQuitty:1966",
         title = "Similarity Analysis by Reciprocal Pairs for Discrete and Continuous Data",
         volume = "26",
         .issn = "1552-3888",
         doi = "10.1177/001316446602600402",
         number = "4",
         journal = "Educational and Psychological Measurement",
         publisher = "SAGE Publications",
         author = person(given = c("Louis", "L."),
                         family = "McQuitty"),
         year = "1966",
         month = "dec",
         pages = "825--831")

bibentry(bibtype = "Article",
         key = "R:Mehta+Patel:1983",
         title = "A Network Algorithm for Performing {Fisher}’s Exact Test in $r \\times c$ Contingency Tables",
         volume = "78",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1983.10477989",
         number = "382",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Cyrus", "R."),
                           family = "Mehta"),
                    person(given = c("Nitin", "R."),
                           family = "Patel")),
         year = "1983",
         month = "jun",
         pages = "427--434")

bibentry(bibtype = "Article",
         key = "R:Mehta+Patel:1986",
         title = "{Algorithm 643}: {FEXACT}: A {FORTRAN} Subroutine for {Fisher}’s Exact Test on Unordered $r \\times c$ Contingency Tables",
         volume = "12",
         .issn = "1557-7295",
         doi = "10.1145/6497.214326",
         number = "2",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = c("Cyrus", "R."),
                           family = "Mehta"),
                    person(given = c("Nitin", "R."),
                           family = "Patel")),
         year = "1986",
         month = "jun",
         pages = "154--161")

bibentry(bibtype = "Article",
         key = "R:Mielke:1967",
         title = "Note on Some Squared Rank Tests with Existing Ties",
         volume = "9",
         .issn = "1537-2723",
         doi = "10.1080/00401706.1967.10490465",
         number = "2",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = person(given = c("Paul", "W."),
                         family = "Mielke"),
         year = "1967",
         month = "may",
         pages = "312--314",
         .doi = "10.2307/1266427")

bibentry(bibtype = "Article",
         key = "R:Murtagh+Legendre:2014",
         title = "{Ward}’s Hierarchical Agglomerative Clustering Method: Which Algorithms Implement {Ward}’s Criterion?",
         volume = "31",
         .issn = "1432-1343",
         doi = "10.1007/s00357-014-9161-z",
         number = "3",
         journal = "Journal of Classification",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "Fionn",
                           family = "Murtagh"),
                    person(given = "Pierre",
                           family = "Legendre")),
         year = "2014",
         month = "oct",
         pages = "274--295")

bibentry(bibtype = "Article",
         key = "R:Nelder+Mead:1965",
         title = "A Simplex Method for Function Minimization",
         volume = "7",
         .issn = "1460-2067",
         doi = "10.1093/comjnl/7.4.308",
         number = "4",
         journal = "The Computer Journal",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = c("J.", "A."),
                           family = "Nelder"),
                    person(given = "R.",
                           family = "Mead")),
         year = "1965",
         month = "jan",
         pages = "308--313")

bibentry(bibtype = "Article",
         key = "R:Newcombe:1998a",
         author = person(given = c("Robert", "G."),
                         family = "Newcombe"),
         title = "Two-sided Confidence Intervals for the Single Proportion: Comparison of Seven Methods",
         journal = "Statistics in Medicine",
         volume = "17",
         number = "8",
         pages = "857--872",
         doi = "10.1002/(SICI)1097-0258(19980430)17:8<857::AID-SIM777>3.0.CO;2-E",
         year = "1998")

bibentry(bibtype = "Article",
         key = "R:Newcombe:1998b",
         author = person(given = c("Robert", "G."),
                         family = "Newcombe"),
         title = "Interval Estimation for the Difference Between Independent Proportions: Comparison of Eleven Methods",
         journal = "Statistics in Medicine",
         volume = "17",
         number = "8",
         pages = "873--890",
         doi = "10.1002/(SICI)1097-0258(19980430)17:8<873::AID-SIM779>3.0.CO;2-I",
         year = "1998")

bibentry(bibtype = "Article",
         key = "R:Odeh+Evans:1974",
         title = "{Algorithm AS 70}: The Percentage Points of the Normal Distribution",
         volume = "23",
         .issn = "0035-9254",
         doi = "10.2307/2347061",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("R.", "E."),
                           family = "Odeh"),
                    person(given = c("J.", "O."),
                           family = "Evans")),
         year = "1974",
         pages = "96")

bibentry(bibtype = "Article",
         key = "R:Patefield:1981",
         title = "{Algorithm AS 159}: An Efficient Method of Generating Random $R \\times C$ Tables with Given Row and Column Totals",
         volume = "30",
         .issn = "0035-9254",
         doi = "10.2307/2346669",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("W.", "M."),
                         family = "Patefield"),
         year = "1981",
         pages = "91")

bibentry(bibtype = "Article",
         key = "R:Perron:1988",
         title = "Trends and Random Walks in Macroeconomic Time Series",
         volume = "12",
         .issn = "0165-1889",
         doi = "10.1016/0165-1889(88)90043-7",
         number = "2--3",
         journal = "Journal of Economic Dynamics and Control",
         publisher = "Elsevier BV",
         author = person(given = "Pierre",
                         family = "Perron"),
         year = "1988",
         month = "jun",
         pages = "297--332")

bibentry(bibtype = "Article",
         key = "R:Ripley:2002",
         author = person(given = c("Brian", "D."),
                         family = "Ripley"),
         title = "Time Series in {R} 1.5.0",
         journal = "R News",
         year = "2002",
         volume = "2",
         number = "2",
         pages = "2--7",
         month = "June",
         url = "https://CRAN.R-project.org/doc/Rnews/Rnews_2002-1.pdf")

bibentry(bibtype = "Article",
         key = "R:Royston:1982a",
         title = "An Extension of {Shapiro} and {Wilk}’s $W$ Test for Normality to Large Samples",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347973",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("J.", "P."),
                         family = "Royston"),
         year = "1982",
         pages = "115")

bibentry(bibtype = "Article",
         key = "R:Royston:1982b",
         title = "{Algorithm AS 181}: The $W$ Test for Normality",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347986",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("J.", "P."),
                         family = "Royston"),
         year = "1982",
         pages = "176")

bibentry(bibtype = "Article",
         key = "R:Royston:1995",
         title = "{Remark AS R94}: A Remark on {Algorithm AS 181}: The $W$-test for Normality",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986146",
         number = "4",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Patrick",
                         family = "Royston"),
         year = "1995",
         pages = "547")

bibentry(bibtype = "Article",
         key = "R:Sarkar+Chang:1997",
         title = "The Simes Method for Multiple Hypothesis Testing with Positively Dependent Test Statistics",
         volume = "92",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1997.10473682",
         number = "440",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Sanat", "K."),
                           family = "Sarkar"),
                    person(given = "Chung-Kuei",
                           family = "Chang")),
         year = "1997",
         month = "dec",
         pages = "1601--1608",
         .doi = "10.2307/2965431")

bibentry(bibtype = "Article",
         key = "R:Sarkar:1998",
         title = "Some Probability Inequalities for Ordered $\\mathrm{MTP}_2$ Random Variables: A Proof of the {Simes} Conjecture",
         volume = "26",
         .issn = "0090-5364",
         doi = "10.1214/aos/1028144846",
         number = "2",
         journal = "The Annals of Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = person(given = c("Sanat", "K."),
                         family = "Sarkar"),
         year = "1998",
         month = "apr")

bibentry(bibtype = "Article",
         key = "R:Schnabel+Koonatz+Weiss:1985",
         title = "A Modular System of Algorithms for Unconstrained Minimization",
         volume = "11",
         .issn = "1557-7295",
         doi = "10.1145/6187.6192",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = c("Robert", "B."),
                           family = "Schnabel"),
                    person(given = c("John", "E."),
                           family = "Koonatz"),
                    person(given = c("Barry", "E."),
                           family = "Weiss")),
         year = "1985",
         month = "dec",
         pages = "419--440")

bibentry(bibtype = "Article",
         key = "R:Schröer+Trenkler:1995",
         title = "Exact and Randomization Distributions of {Kolmogorov}-{Smirnov} Tests Two or Three Samples",
         volume = "20",
         .issn = "0167-9473",
         doi = "10.1016/0167-9473(94)00040-P",
         number = "2",
         journal = "Computational Statistics & Data Analysis",
         publisher = "Elsevier BV",
         author = c(person(given = "Gunar",
                           family = "Schröer"),
                    person(given = "Dietrich",
                           family = "Trenkler")),
         year = "1995",
         month = "aug",
         pages = "185--202",
         .doi = "10.1016/0167-9473(94)00040-p")

bibentry(bibtype = "Article",
         key = "R:Shaffer:1995",
         title = "Multiple Hypothesis Testing",
         volume = "46",
         .issn = "1545-2085",
         doi = "10.1146/annurev.ps.46.020195.003021",
         number = "1",
         journal = "Annual Review of Psychology",
         publisher = "Annual Reviews",
         author = person(given = c("J", "P"),
                         family = "Shaffer"),
         year = "1995",
         month = "jan",
         pages = "561--584")

bibentry(bibtype = "Article",
         key = "R:Shea:1988",
         title = "{Algorithm AS 239}: Chi-Squared and Incomplete {Gamma} Integral",
         volume = "37",
         .issn = "0035-9254",
         doi = "10.2307/2347328",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("B.", "L."),
                         family = "Shea"),
         year = "1988",
         pages = "466")

bibentry(bibtype = "Article",
         key = "R:Sheather+Jones:1991",
         title = "A Reliable Data-Based Bandwidth Selection Method for Kernel Density Estimation",
         volume = "53",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1991.tb01857.x",
         number = "3",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = c("S.", "J."),
                           family = "Sheather"),
                    person(given = c("M.", "C."),
                           family = "Jones")),
         year = "1991",
         month = "jul",
         pages = "683--690")

bibentry(bibtype = "Article",
         key = "R:Switzer:1976",
         title = "Confidence Procedures for Two-Sample Problems",
         volume = "63",
         .issn = "1464-3510",
         doi = "10.1093/biomet/63.1.13",
         number = "1",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Paul",
                         family = "Switzer"),
         year = "1976",
         pages = "13--25")

bibentry(bibtype = "Article",
         key = "R:Thomson:1938",
         title = "Methods of Estimating Mental Factors",
         volume = "141",
         .issn = "1476-4687",
         doi = "10.1038/141246a0",
         number = "3562",
         journal = "Nature",
         publisher = "Springer Science and Business Media LLC",
         author = person(given = c("Godfrey", "H."),
                         family = "Thomson"),
         year = "1938",
         month = "feb",
         pages = "246--246")

bibentry(bibtype = "Article",
         key = "R:Thomson:1990",
         volume = "330",
         .issn = "2054-0272",
         doi = "10.1098/rsta.1990.0041",
         number = "1615",
         journal = "Philosophical Transactions of the Royal Society of London. Series A, Mathematical and Physical Sciences",
         publisher = "The Royal Society",
         year = "1990",
         month = "apr",
         pages = "601--616",
         title = "Time Series Analysis of {Holocene} Climate Data",
         author = person(given = c("David", "J."),
                         family = "Thomson"))

bibentry(bibtype = "Book",
         key = "R:Tukey:1977",
         title = "Exploratory Data Analysis",
         author = person(given = c("John", "Wilder"),
                         family = "Tukey"),
         number = "2",
         isbn = "9780201076165",
         lccn = "76005080",
         series = "Addison-Wesley series in behavioral science",
         year = "1977",
         publisher = "Addison-Wesley Publishing Company")

bibentry(bibtype = "Book",
         key = "R:Velleman+Hoaglin:1981",
         title = "Applications, Basics, and Computing of Exploratory Data Analysis",
         author = c(person(given = c("Paul", "F."),
                           family = "Velleman"),
                    person(given = c("David", "Caster"),
                           family = "Hoaglin")),
         isbn = "9780878722730",
         lccn = "80016193",
         series = "Duxbury series in statistics and decision sciences",
         year = "1981",
         publisher = "Duxbury Press")

bibentry(bibtype = "Article",
         key = "R:Welch:1951",
         title = "On the Comparison of Several Mean Values: An Alternative Approach",
         volume = "38",
         .issn = "0006-3444",
         doi = "10.2307/2332579",
         number = "3/4",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = c("B.", "L."),
                         family = "Welch"),
         year = "1951",
         month = "dec",
         pages = "330")

bibentry(bibtype = "Article",
         key = "R:Whittle:1963",
         title = "On the Fitting of Multivariate Autoregressions, and the Approximate Canonical Factorization of a Spectral Density Matrix",
         volume = "50",
         .issn = "0006-3444",
         doi = "10.2307/2333753",
         number = "1/2",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = "P.",
                         family = "Whittle"),
         year = "1963",
         month = "jun",
         pages = "129")

bibentry(bibtype = "Article",
         key = "R:Wichura:1988",
         title = "{Algorithm AS 241}: The Percentage Points of the Normal Distribution",
         volume = "37",
         .issn = "0035-9254",
         doi = "10.2307/2347330",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("Michael", "J."),
                         family = "Wichura"),
         year = "1988",
         pages = "477")

bibentry(bibtype = "Article",
         key = "R:Wilkinson+Rogers:1973",
         title = "Symbolic Description of Factorial Models for Analysis of Variance",
         volume = "22",
         .issn = "0035-9254",
         doi = "10.2307/2346786",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = c("G.", "N."),
                           family = "Wilkinson"),
                    person(given = c("C.", "E."),
                           family = "Rogers")),
         year = "1973",
         pages = "392")

bibentry(bibtype = "Article",
         key = "R:Williams:1987",
         title = "Generalized Linear Model Diagnostics Using the Deviance and Single Case Deletions",
         volume = "36",
         .issn = "0035-9254",
         doi = "10.2307/2347550",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = c("D.", "A."),
                         family = "Williams"),
         year = "1987",
         pages = "181")

bibentry(bibtype = "Article",
         key = "R:Wilson:1927",
         title = "Probable Inference, the Law of Succession, and Statistical Inference",
         volume = "22",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1927.10502953",
         number = "158",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = c("Edwin", "B."),
                         family = "Wilson"),
         year = "1927",
         month = "jun",
         pages = "209--212",
         .doi = "10.2307/2276774")

bibentry(bibtype = "Article",
         key = "R:Winters:1960",
         title = "Forecasting Sales by Exponentially Weighted Moving Averages",
         volume = "6",
         .issn = "1526-5501",
         doi = "10.1287/mnsc.6.3.324",
         number = "3",
         journal = "Management Science",
         publisher = "Institute for Operations Research and the Management Sciences (INFORMS)",
         author = person(given = c("Peter", "R."),
                         family = "Winters"),
         year = "1960",
         month = "apr",
         pages = "324--342")

bibentry(bibtype = "Article",
         key = "R:Wright:1992",
         title = "Adjusted $P$-Values for Simultaneous Inference",
         volume = "48",
         .issn = "0006-341X",
         doi = "10.2307/2532694",
         number = "4",
         journal = "Biometrics",
         publisher = "JSTOR",
         author = person(given = c("S.", "Paul"),
                         family = "Wright"),
         year = "1992",
         month = "dec",
         pages = "1005")

bibentry(bibtype = "Book",
         key = "R:Belsley+Kuh+Welsch:1980",
         author = c(person(given = c("David", "A."),
                           family = "Belsley"),
                    person(given = "Edwin",
                           family = "Kuh"),
                    person(given = c("Roy", "E."),
                           family = "Welsch")),
         title = "Regression Diagnostics: Identifying Influential Data and Sources of Collinearity",
         publisher = "John Wiley & Sons",
         year = "1980",
         doi = "10.1002/0471725153")

bibentry(bibtype = "Book",
         key = "R:Blom:1958",
         author = person(given = "Gunnar",
                         family = "Blom"),
         title = "Statistical Estimates and Transformed Beta-Variables",
         publisher = "Wiley",
         year = "1958")

bibentry(bibtype = "Book",
         key = "R:Brockwell+Davis:1996",
         author = c(person(given = c("Peter", "J."),
                           family = "Brockwell"),
                    person(given = c("Richard", "A."),
                           family = "Davis")),
         title = "Introduction to Time Series and Forecasting",
         publisher = "Springer",
         year = "1996",
         series = "Springer Texts in Statistics",
         address = "New York, NY",
         doi = "10.1007/978-1-4757-2526-1")

bibentry(bibtype = "Book",
         key = "R:Forsythe+Malcolm+Moler:1977",
         author = c(person(given = c("George", "Elmer"),
                           family = "Forsythe"),
                    person(given = c("Michael", "A."),
                           family = "Malcolm"),
                    person(given = c("Cleve", "B."),
                           family = "Moler")),
         title = "Computer Methods for Mathematical Computations",
         publisher = "Prentice Hall",
         year = "1977",
         isbn = "978-0131653320")

bibentry(bibtype = "Book",
         key = "R:Hajek+Sidak+Sen:1999",
         title = "Theory of Rank Tests",
         author = c(person(given = "Jaroslav",
                           family = "Hajek"),
                    person(given = "Zbynek",
                           family = "Sidak"),
                    person(given = c("Pranab", "K."),
                           family = "Sen")),
         isbn = "9780080519104",
         series = "Probability and Mathematical Statistics",
         year = "1999",
         publisher = "Academic Press")

bibentry(bibtype = "Book",
         key = "R:Hand+Taylor:1987",
         author = c(person(given = c("D.", "J."),
                           family = "Hand"),
                    person(given = c("C.", "C."),
                           family = "Taylor")),
         title = "Multivariate Analysis of Variance and Repeated Measures: A Practical Approach for Behavioural Scientists",
         publisher = "Chapman & Hall/CRC",
         year = "1987")

bibentry(bibtype = "Book",
         key = "R:Hollander+Wolfe:1973",
         author = c(person(given = "Myles",
                           family = "Hollander"),
                    person(given = c("Douglas", "A."),
                           family = "Wolfe")),
         title = "Nonparametric Statistical Methods",
         publisher = "John Wiley & Sons",
         year = "1973",
         address = "New York")

bibentry(bibtype = "Book",
         key = "R:Krzanowski+Marriott:1994",
         author = c(person(given = c("W.", "J."),
                           family = "Krzanowski"),
                    person(given = c("F.", "H.", "C."),
                           family = "Marriott")),
         title = "Multivariate Analysis Part I: Distributions, Ordination and Inference.",
         publisher = "Hodder Arnold",
         year = "1994",
         isbn = "978-0340593264")

bibentry(bibtype = "Book",
         key = "R:Krzanowski:1988",
         author = person(given = c("W.", "J."),
                         family = "Krzanowski"),
         title = "Principles of Multivariate Analysis: A User’s Perspective",
         publisher = "Oxford University Press",
         year = "1988",
         month = "sep",
         isbn = "978-0198522119")

bibentry(bibtype = "Book",
         key = "R:Percival+Walden:1998",
         author = c(person(given = c("Donald", "B."),
                           family = "Percival"),
                    person(given = c("Andrew", "T."),
                           family = "Walden")),
         title = "Spectral Analysis for Physical Applications",
         publisher = "Cambridge University Press",
         year = "1998")

bibentry(bibtype = "Book",
         key = "R:Silverman:1986",
         author = person(given = c("Bernhard", "Walter"),
                         family = "Silverman"),
         title = "Density Estimation for Statistics and Data Analysis",
         publisher = "Chapman & Hall",
         year = "1986")

bibentry(bibtype = "Book",
         key = "R:Venables+Ripley:2002",
         author = c(person(given = c("William", "N."),
                           family = "Venables"),
                    person(given = c("Brian", "D."),
                           family = "Ripley")),
         title = "Modern Applied Statistics with {S}",
         publisher = "Springer",
         year = "2002",
         series = "Statistics and Computing",
         address = "New York, NY",
         doi = "10.1007/978-0-387-21706-2")

bibentry(bibtype = "Book",
         key = "R:Conover:1971",
         title = "Practical Nonparametric Statistics",
         author = person(given = "W.J.",
                         family = "Conover"),
         isbn = "9780471168515",
         lccn = "lc74126223",
         year = "1971",
         publisher = "Wiley")

bibentry(bibtype = "Misc",
         key = "R:Wicklin:2017",
         author = person(given = "R.",
                         family = "Wicklin"),
         title = "Sample Quantiles: A Comparison of 9 Definitions",
         howpublished = "{SAS} Blog",
         year = "2017",
         url = "https://blogs.sas.com/content/iml/2017/05/24/definitions-sample-quantiles.htm")

bibentry(bibtype = "Book",
         key = "R:Bloomfield:1976",
         author = person(given = "P.",
                         family = "Bloomfield"),
         title = "Fourier Analysis of Time Series: An Introduction",
         publisher = "Wiley",
         year = "1976")

bibentry(bibtype = "Book",
         key = "R:Scott:1992",
         author = person(given = c("David", "W."),
                         family = "Scott"),
         title = "Multivariate Density Estimation. Theory, Practice and Visualization",
         publisher = "Wiley",
         year = "1992",
         address = "New York")

bibentry(bibtype = "Misc",
         key = "R:Lloyd:1957",
         author = person(given = c("S.", "P."),
                         family = "Lloyd"),
         title = "Least Squares Quantization in {PCM}",
         howpublished = "Technical Note, Bell Laboratories",
         year = "1957")

bibentry(bibtype = "Article",
         key = "R:Lloyd:1982",
         author = person(given = c("S.", "P."),
                         family = "Lloyd"),
         journal = "IEEE Transactions on Information Theory",
         title = "Least Squares Quantization in {PCM}",
         year = "1982",
         volume = "28",
         number = "2",
         pages = "129--137",
         doi = "10.1109/TIT.1982.1056489")

bibentry(bibtype = "InCollection",
         key = "R:MacQueen:1967",
         author = person(given = "J.",
                         family = "MacQueen"),
         title = "Some Methods for Classification and Analysis of Multivariate Observations.",
         booktitle = "Proceedings of the Fifth Berkeley Symposium on Mathematical Statistics and Probability",
         publisher = "University of California Press",
         year = "1967",
         editor = c(person(given = c("Lucien", "M."),
                           family = "Le Cam"),
                    person(given = "Jerzy",
                           family = "Neyman")),
         number = "1",
         pages = "281--297",
         address = "Berkeley, CA")

bibentry(bibtype = "Book",
         key = "R:Durbin:1973",
         author = person(given = "J.",
                         family = "Durbin"),
         title = "Distribution Theory for Tests Based on the Sample Distribution Function",
         publisher = "Society for Industrial and Applied Mathematics",
         year = "1973",
         doi = "10.1137/1.9781611970586")

bibentry(bibtype = "MastersThesis",
         key = "R:Schröer:1991",
         author = person(given = "Gunar",
                         family = "Schröer"),
         title = "{Computergestützte statistische Inferenz am Beispiel der Kolmogorov-Smirnov Tests}",
         school = "Universität Osnabrück",
         year = "1991")

bibentry(bibtype = "Misc",
         key = "R:Viehmann:2021",
         title = "Numerically More Stable Computation of the $p$-Values for the Two-Sample {Kolmogorov}-{Smirnov} Test",
         author = person(given = "Thomas",
                         family = "Viehmann"),
         year = "2021",
         doi = "10.48550/arXiv.2102.08037")

bibentry(bibtype = "Book",
         key = "R:Agresti:2007",
         author = person(given = "Alan",
                         family = "Agresti"),
         title = "An Introduction to Categorical Data Analysis",
         publisher = "John Wiley & Sons",
         year = "2007",
         address = "New York",
         edition = "2nd",
         doi = "10.1002/0470114754")

bibentry(bibtype = "Book",
         key = "R:Nash:1990",
         author = person(given = c("John", "C."),
                         family = "Nash"),
         title = "Compact Numerical Methods for Computers. Linear Algebra and Function Minimisation",
         publisher = "CRC Press",
         year = "1990",
         isbn = "9780852743195")

bibentry(bibtype = "Book",
         key = "R:Nocedal+Wright:1999",
         author = c(person(given = "Jorge",
                           family = "Nocedal"),
                    person(given = "Stephen",
                           family = "Wright")),
         title = "Numerical Optimization",
         publisher = "Springer",
         year = "1999",
         series = "Springer Series in Operations Research and Financial Engineering")

bibentry(bibtype = "Book",
         key = "R:Banerjee+Dolado+Galbraith:1993",
         author = c(person(given = "Anindya",
                           family = "Banerjee"),
                    person(given = c("Juan", "J."),
                           family = "Dolado"),
                    person(given = c("John", "W."),
                           family = "Galbraith"),
                    person(given = "David",
                           family = "Hendry")),
         title = "Co-integration, Error Correction, and the Econometric Analysis of Non-Stationary Data",
         publisher = "Oxford University Press",
         year = "1993",
         month = "05",
         isbn = "9780198288107",
         doi = "10.1093/0198288107.001.0001")

bibentry(bibtype = "Book",
         key = "R:Dunn+Smyth:2018",
         author = c(person(given = c("Peter", "K."),
                           family = "Dunn"),
                    person(given = c("Gordon", "K."),
                           family = "Smyth")),
         title = "Generalized Linear Models with Examples in {R}",
         publisher = "Springer",
         year = "2018",
         series = "Springer Texts in Statistics",
         address = "New York, NY",
         doi = "10.1007/978-1-4419-0118-7")

bibentry(bibtype = "Book",
         key = "R:Cook+Weisberg:1982",
         author = c(person(given = "S.",
                           family = "Cook"),
                    person(given = c("R.", "Dennis"),
                           family = "Weisberg")),
         title = "Residuals and Influence in Regression",
         publisher = "Chapman & Hall",
         year = "1982",
         isbn = "978-0412242809",
         address = "London")

bibentry(bibtype = "Book",
         key = "R:McCullagh+Nelder:1989",
         author = c(person(given = "P.",
                           family = "McCullagh"),
                    person(given = c("John", "A."),
                           family = "Nelder")),
         title = "Generalized Linear Models",
         publisher = "Chapman and Hall/CRC",
         year = "1989",
         isbn = "978-0412317606",
         address = "London")

bibentry(bibtype = "InCollection",
         key = "R:Davison+Snell:1991",
         author = c(person(given = "Anthony",
                           family = "Davison"),
                    person(given = c("E.", "J."),
                           family = "Snell")),
         title = "Residuals and Diagnostics",
         booktitle = "Statistical Theory and Modelling. In Honour of Sir David Cox, FRS",
         publisher = "Chapman & Hall",
         year = "1991",
         editor = c(person(given = c("D.", "V."),
                           family = "Hinkley"),
                    person(given = "N.",
                           family = "Reid"),
                    person(given = c("E.", "J."),
                           family = "Snell")))

bibentry(bibtype = "Book",
         key = "R:Jöreskog:1963",
         author = person(given = c("Karl", "G."),
                         family = "Jöreskog"),
         title = "Statistical Estimation in Factor Analysis",
         publisher = "Almqvist and Wicksell",
         year = "1963")

bibentry(bibtype = "Book",
         key = "R:Lawley+Maxwell:1971",
         author = c(person(given = c("D.", "N."),
                           family = "Lawley"),
                    person(given = c("Albert", "Ernest"),
                           family = "Maxwell")),
         title = "Factor Analysis as a Statistical Method",
         publisher = "Butterworth & Co Publishers Ltd",
         year = "1971",
         isbn = "978-0408701525",
         edition = "2nd")
