bibentry(bibtype = "Article",
         key = "R:Bartlett:1937a",
         title = "The Statistical Conception of Mental Factors",
         volume = "28",
         .issn = "0373-2460",
         doi = "10.1111/j.2044-8295.1937.tb00863.x",
         number = "1",
         journal = "British Journal of Psychology. General Section",
         publisher = "Wiley",
         author = person(given = "M. S.",
                         family = "Bartlett"),
         year = "1937",
         month = "jul",
         pages = "97--104")

bibentry(bibtype = "Article",
         key = "R:Bartlett:1937b",
         volume = "160",
         .issn = "2053-9169",
         doi = "10.1098/rspa.1937.0109",
         number = "901",
         journal = "Proceedings of the Royal Society of London. Series A - Mathematical and Physical Sciences",
         publisher = "The Royal Society",
         year = "1937",
         month = "may",
         pages = "268--282",
         title = "Properties of Sufficiency and Statistical Tests",
         author = person(given = c("Maurice", "Stevenson"),
                         family = "Bartlett"))

bibentry(bibtype = "Article",
         key = "R:Bauer:1972",
         title = "Constructing Confidence Sets Using Rank Statistics",
         volume = "67",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1972.10481279",
         number = "339",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "David F.",
                         family = "Bauer"),
         year = "1972",
         month = "sep",
         pages = "687--690")

bibentry(bibtype = "Article",
         key = "R:Benjamini+Hochberg:1995",
         title = "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing",
         volume = "57",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1995.tb02031.x",
         number = "1",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "Yoav",
                           family = "Benjamini"),
                    person(given = "Yosef",
                           family = "Hochberg")),
         year = "1995",
         month = "jan",
         pages = "289--300")

bibentry(bibtype = "Article",
         key = "R:Benjamini+Yekutieli:2001",
         title = "The control of the false discovery rate in multiple testing under dependency",
         volume = "29",
         .issn = "0090-5364",
         doi = "10.1214/aos/1013699998",
         number = "4",
         journal = "The Annals of Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = "Yoav",
                           family = "Benjamini"),
                    person(given = "Daniel",
                           family = "Yekutieli")),
         year = "2001",
         month = "aug")

bibentry(bibtype = "Article",
         key = "R:Best+Roberts:1975",
         title = "Algorithm AS 89: The Upper Tail Probabilities of Spearman’s Rho",
         volume = "24",
         .issn = "0035-9254",
         doi = "10.2307/2347111",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "D. J.",
                           family = "Best"),
                    person(given = "D. E.",
                           family = "Roberts")),
         year = "1975",
         pages = "377")

bibentry(bibtype = "Article",
         key = "R:Birnbaum+Tingey:1951",
         title = "One-Sided Confidence Contours for Probability Distribution Functions",
         volume = "22",
         .issn = "0003-4851",
         doi = "10.1214/aoms/1177729550",
         number = "4",
         journal = "The Annals of Mathematical Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = c(person(given = "Z. W.",
                           family = "Birnbaum"),
                    person(given = "Fred H.",
                           family = "Tingey")),
         year = "1951",
         month = "dec",
         pages = "592--596")

bibentry(bibtype = "Article",
         key = "R:Box+Pierce:1970",
         title = "Distribution of Residual Autocorrelations in Autoregressive-Integrated Moving Average Time Series Models",
         volume = "65",
         .issn = "1537-274X",
         doi = "10.1080/00031305.1984.10482869",
         number = "332",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "G. E. P.",
                           family = "Box"),
                    person(given = "David A.",
                           family = "Pierce")),
         year = "1970",
         month = "dec",
         pages = "1509--1526",
         .doi = "10.2307/2683556")

bibentry(bibtype = "Article",
         key = "R:Brown+Levy:1994",
         title = "Certification of Algorithm 708: Significant-digit Computation of the Incomplete Beta",
         volume = "20",
         .issn = "1557-7295",
         doi = "10.1145/192115.192155",
         number = "3",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "Barry W.",
                           family = "Brown"),
                    person(given = "Lawrence B.",
                           family = "Levy")),
         year = "1994",
         month = "sep",
         pages = "393--397")

bibentry(bibtype = "Article",
         key = "R:Bélisle:1992",
         title = "Convergence theorems for a class of simulated annealing algorithms on ℝd",
         volume = "29",
         .issn = "1475-6072",
         doi = "10.2307/3214721",
         number = "4",
         journal = "Journal of Applied Probability",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = "Claude J. P.",
                         family = "Bélisle"),
         year = "1992",
         month = "dec",
         pages = "885--895")

bibentry(bibtype = "Article",
         key = "R:Cailliez:1983",
         title = "The Analytical Solution of the Additive Constant Problem",
         volume = "48",
         .issn = "1860-0980",
         doi = "10.1090/s0025-5718-1965-0178586-1",
         number = "2",
         journal = "Psychometrika",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = "Francis",
                         family = "Cailliez"),
         year = "1983",
         month = "jun",
         pages = "305--308",
         .doi = "10.2307/2003354")

bibentry(bibtype = "Article",
         key = "R:Carlson+Fritsch:1980",
         title = "Monotone Piecewise Cubic Interpolation",
         volume = "17",
         .issn = "1095-7170",
         doi = "10.1137/0717021",
         number = "2",
         journal = "SIAM Journal on Numerical Analysis",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = c(person(given = "R. E.",
                           family = "Carlson"),
                    person(given = "F. N.",
                           family = "Fritsch")),
         year = "1980",
         month = "apr",
         pages = "238--246")

bibentry(bibtype = "Article",
         key = "R:Chang+Sarkar:1997",
         title = "The Simes Method for Multiple Hypothesis Testing with Positively Dependent Test Statistics",
         volume = "92",
         .issn = "1537-274X",
         doi = "10.1093/biomet/75.4.800",
         number = "440",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "Chung-Kuei",
                           family = "Chang"),
                    person(given = "Sanat K.",
                           family = "Sarkar")),
         year = "1997",
         month = "dec",
         pages = "1601--1608",
         .doi = "10.2307/2336325")

bibentry(bibtype = "Article",
         key = "R:Clarkson+Joe+Fan:1993",
         title = "A remark on algorithm 643: FEXACT: an algorithm for performing Fisher’s exact test in r x c contingency tables",
         volume = "19",
         .issn = "1557-7295",
         doi = "10.1145/168173.168412",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "Douglas B.",
                           family = "Clarkson"),
                    person(given = "Harry",
                           family = "Joe"),
                    person(given = "Yuan-an",
                           family = "Fan")),
         year = "1993",
         month = "dec",
         pages = "484--488")

bibentry(bibtype = "Article",
         key = "R:Cleveland:1979",
         title = "Robust Locally Weighted Regression and Smoothing Scatterplots",
         volume = "74",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1979.10481038",
         number = "368",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "William S.",
                         family = "Cleveland"),
         year = "1979",
         month = "dec",
         pages = "829--836")

bibentry(bibtype = "Article",
         key = "R:Cleveland:1981",
         title = "LOWESS: A Program for Smoothing Scatterplots by Robust Locally Weighted Regression",
         volume = "35",
         .issn = "0003-1305",
         doi = "10.2307/2683591",
         number = "1",
         journal = "The American Statistician",
         publisher = "JSTOR",
         author = person(given = "William S.",
                         family = "Cleveland"),
         year = "1981",
         month = "feb",
         pages = "54")

bibentry(bibtype = "Article",
         key = "R:Conover+Johnson+Johnson:1981",
         title = "A Comparative Study of Tests for Homogeneity of Variances, with Applications to the Outer Continental Shelf Bidding Data",
         volume = "23",
         .issn = "1537-2723",
         doi = "10.1090/S0025-5718-1989-0962209-1",
         number = "4",
         journal = "Technometrics",
         publisher = "Informa UK Limited",
         author = c(person(given = "W. J.",
                           family = "Conover"),
                    person(given = "Mark E.",
                           family = "Johnson"),
                    person(given = "Myrle M.",
                           family = "Johnson")),
         year = "1981",
         month = "nov",
         pages = "351--361",
         .doi = "10.1090/s0025-5718-1989-0962209-1")

bibentry(bibtype = "Article",
         key = "R:Cooley+Tukey:1965",
         title = "An algorithm for the machine calculation of complex Fourier series",
         volume = "19",
         .issn = "1088-6842",
         doi = "10.1093/biomet/26.4.404",
         number = "90",
         journal = "Mathematics of Computation",
         publisher = "American Mathematical Society (AMS)",
         author = c(person(given = "James W.",
                           family = "Cooley"),
                    person(given = "John W.",
                           family = "Tukey")),
         year = "1965",
         pages = "297--301",
         .doi = "10.2307/2331986")

bibentry(bibtype = "Article",
         key = "R:Copenhaver+Holland:1988",
         title = "Computation of the distribution of the maximum studentized range statistic with application to multiple significance testing of simple effects",
         volume = "30",
         .issn = "1563-5163",
         doi = "10.1080/00949658808811082",
         number = "1",
         journal = "Journal of Statistical Computation and Simulation",
         publisher = "Informa UK Limited",
         author = c(person(given = "Margaret Diponzio",
                           family = "Copenhaver"),
                    person(given = "Burt",
                           family = "Holland")),
         year = "1988",
         month = "aug",
         pages = "1--15")

bibentry(bibtype = "Article",
         key = "R:Diaconis+Mosteller:1989",
         title = "Methods for Studying Coincidences",
         volume = "84",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1989.10478847",
         number = "408",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "Persi",
                           family = "Diaconis"),
                    person(given = "Frederick",
                           family = "Mosteller")),
         year = "1989",
         month = "dec",
         pages = "853--861")

bibentry(bibtype = "Article",
         key = "R:Didonato+Morris:1992",
         title = "Algorithm 708: Significant Digit Computation of the Incomplete Beta Function Ratios",
         volume = "18",
         .issn = "1557-7295",
         doi = "10.1145/131766.131776",
         number = "3",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "Armido R.",
                           family = "Didonato"),
                    person(given = "Alfred H.",
                           family = "Morris")),
         year = "1992",
         month = "sep",
         pages = "360--373")

bibentry(bibtype = "Article",
         key = "R:Evans+Odeh:1974",
         title = "Algorithm AS 70: The Percentage Points of the Normal Distribution",
         volume = "23",
         .issn = "0035-9254",
         doi = "10.2307/2347061",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "J. O.",
                           family = "Evans"),
                    person(given = "R. E.",
                           family = "Odeh")),
         year = "1974",
         pages = "96")

bibentry(bibtype = "Article",
         key = "R:Feller:1948",
         title = "On the Kolmogorov-Smirnov Limit Theorems for Empirical Distributions",
         volume = "19",
         .issn = "0003-4851",
         doi = "10.1214/aoms/1177730243",
         number = "2",
         journal = "The Annals of Mathematical Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = person(given = "W.",
                         family = "Feller"),
         year = "1948",
         month = "jun",
         pages = "177--189")

bibentry(bibtype = "Article",
         key = "R:Fisher:1935",
         title = "The Logic of Inductive Inference",
         volume = "98",
         .issn = "0952-8385",
         doi = "10.2307/2342435",
         number = "1",
         journal = "Journal of the Royal Statistical Society",
         publisher = "JSTOR",
         author = person(given = "R. A.",
                         family = "Fisher"),
         year = "1935",
         pages = "39")

bibentry(bibtype = "Article",
         key = "R:Fisher:1962",
         title = "CONFIDENCE LIMITS FOR A CROSS‐PRODUCT RATIO",
         volume = "4",
         .issn = "0004-9581",
         doi = "10.1090/s0025-5718-1965-0178586-1",
         number = "1",
         journal = "Australian Journal of Statistics",
         publisher = "Wiley",
         author = person(given = "Sir Ronald A.",
                         family = "Fisher"),
         year = "1962",
         month = "apr",
         pages = "41--41",
         .doi = "10.2307/2003354")

bibentry(bibtype = "Article",
         key = "R:Fletcher:1964",
         title = "Function minimization by conjugate gradients",
         volume = "7",
         .issn = "1460-2067",
         doi = "10.1093/comjnl/7.2.149",
         number = "2",
         journal = "The Computer Journal",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "R.",
                         family = "Fletcher"),
         year = "1964",
         month = "feb",
         pages = "149--154")

bibentry(bibtype = "Article",
         key = "R:Freedman+Diaconis:1981",
         title = "On the histogram as a density estimator:L 2 theory",
         volume = "57",
         .issn = "1432-2064",
         doi = "10.1016/0167-9473(94)00040-P",
         number = "4",
         journal = "Zeitschrift f�r Wahrscheinlichkeitstheorie und Verwandte Gebiete",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "David",
                           family = "Freedman"),
                    person(given = "Persi",
                           family = "Diaconis")),
         year = "1981",
         month = "dec",
         pages = "453--476",
         .doi = "10.1016/0167-9473(94)00040-p")

bibentry(bibtype = "Article",
         key = "R:Frick:1990",
         title = "Algorithm AS R84: A Remark on Algorithm AS 226: Computing Non-Central Beta Probabilities",
         volume = "39",
         .issn = "0035-9254",
         doi = "10.2307/2347780",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "H.",
                         family = "Frick"),
         year = "1990",
         pages = "311")

bibentry(bibtype = "Article",
         key = "R:Friedman+Stuetzle:1981",
         title = "Projection Pursuit Regression",
         volume = "76",
         .issn = "1537-274X",
         doi = "10.1080/00031305.1994.10476086",
         number = "376",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "Jerome H.",
                           family = "Friedman"),
                    person(given = "Werner",
                           family = "Stuetzle")),
         year = "1981",
         month = "dec",
         pages = "817--823",
         .doi = "10.2307/2684839")

bibentry(bibtype = "Article",
         key = "R:Friendly:1994",
         title = "Mosaic Displays for Multi-Way Contingency Tables",
         volume = "89",
         .issn = "1537-274X",
         doi = "10.1080/10618600.2000.10474900",
         number = "425",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "Michael",
                         family = "Friendly"),
         year = "1994",
         month = "mar",
         pages = "190--200",
         .doi = "10.2307/1390947")

bibentry(bibtype = "Article",
         key = "R:Gower:1966",
         title = "Some Distance Properties of Latent Root and Vector Methods Used in Multivariate Analysis",
         volume = "53",
         .issn = "0006-3444",
         doi = "10.2307/2333639",
         number = "3/4",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = "J. C.",
                         family = "Gower"),
         year = "1966",
         month = "dec",
         pages = "325")

bibentry(bibtype = "Article",
         key = "R:Haberman:1972",
         title = "Algorithm AS 51: Log-Linear Fit for Contingency Tables",
         volume = "21",
         .issn = "0035-9254",
         doi = "10.2307/2346506",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "S. J.",
                         family = "Haberman"),
         year = "1972",
         pages = "218")

bibentry(bibtype = "Article",
         key = "R:Hardle+Steiger:1995",
         title = "Algorithm AS 296: Optimal Median Smoothing",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986349",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "W.",
                           family = "Hardle"),
                    person(given = "W.",
                           family = "Steiger")),
         year = "1995",
         pages = "258")

bibentry(bibtype = "Article",
         key = "R:Harvey+McKenzie:1982",
         title = "Algorithm AS 182: Finite Sample Prediction from ARIMA Processes",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347987",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "A. C.",
                           family = "Harvey"),
                    person(given = "C. R.",
                           family = "McKenzie")),
         year = "1982",
         pages = "180")

bibentry(bibtype = "Article",
         key = "R:Hill:1970",
         title = "ACM Algorithm 395: Student’s t-distribution",
         volume = "13",
         .issn = "1557-7317",
         doi = "10.1145/355598.355599",
         number = "10",
         journal = "Communications of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "G. W.",
                         family = "Hill"),
         year = "1970",
         month = "oct",
         pages = "617--619")

bibentry(bibtype = "Article",
         key = "R:Hill:1981",
         title = "Remark on “Algorithm 396: Student’s t-Quantiles [S14]”",
         volume = "7",
         .issn = "1557-7295",
         doi = "10.1145/355945.355956",
         number = "2",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "G. W.",
                         family = "Hill"),
         year = "1981",
         month = "jun",
         pages = "250--251")

bibentry(bibtype = "Article",
         key = "R:Hinkley:1975",
         title = "On Power Transformations to Symmetry",
         volume = "62",
         .issn = "1464-3510",
         doi = "10.1080/01621459.1976.10480965",
         number = "1",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "David V.",
                         family = "Hinkley"),
         year = "1975",
         pages = "101--111",
         .doi = "10.2307/2286857")

bibentry(bibtype = "Article",
         key = "R:Holt:2004",
         title = "Forecasting seasonals and trends by exponentially weighted moving averages",
         volume = "20",
         .issn = "0169-2070",
         doi = "10.1016/j.ijforecast.2003.09.015",
         number = "1",
         journal = "International Journal of Forecasting",
         publisher = "Elsevier BV",
         author = person(given = "Charles C.",
                         family = "Holt"),
         year = "2004",
         month = "jan",
         pages = "5--10")

bibentry(bibtype = "Article",
         key = "R:Hope:1968",
         title = "A Simplified Monte Carlo Significance Test Procedure",
         volume = "30",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1968.tb00759.x",
         number = "3",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Adery C. A.",
                         family = "Hope"),
         year = "1968",
         month = "sep",
         pages = "582--598")

bibentry(bibtype = "Article",
         key = "R:Hotelling:1936",
         title = "Relations Between Two Sets of Variates",
         volume = "28",
         .issn = "1464-3510",
         doi = "10.1093/biomet/28.3-4.321",
         number = "3--4",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "H.",
                         family = "Hotelling"),
         year = "1936",
         month = "dec",
         pages = "321--377")

bibentry(bibtype = "Article",
         key = "R:Hyman:1983",
         title = "Accurate Monotonicity Preserving Cubic Interpolation",
         volume = "4",
         .issn = "2168-3417",
         doi = "10.1137/0904045",
         number = "4",
         journal = "SIAM Journal on Scientific and Statistical Computing",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = person(given = "James M.",
                         family = "Hyman"),
         year = "1983",
         month = "dec",
         pages = "645--654")

bibentry(bibtype = "Article",
         key = "R:Hyman+Dougherty+Edelman:1989",
         title = "Nonnegativity-, monotonicity-, or convexity-preserving cubic and quintic Hermite interpolation",
         volume = "52",
         .issn = "1088-6842",
         doi = "10.1080/00031305.1984.10482869",
         number = "186",
         journal = "Mathematics of Computation",
         publisher = "American Mathematical Society (AMS)",
         author = c(person(given = "James M.",
                           family = "Hyman"),
                    person(given = "Randall L.",
                           family = "Dougherty"),
                    person(given = "Alan S.",
                           family = "Edelman")),
         year = "1989",
         pages = "471--494",
         .doi = "10.2307/2683556")

bibentry(bibtype = "Article",
         key = "R:Hyndman+Fan:1996",
         title = "Sample Quantiles in Statistical Packages",
         volume = "50",
         .issn = "1537-2731",
         doi = "10.1016/0167-9473(94)00040-P",
         number = "4",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = "Rob J.",
                           family = "Hyndman"),
                    person(given = "Yanan",
                           family = "Fan")),
         year = "1996",
         month = "nov",
         pages = "361--365",
         .doi = "10.1016/0167-9473(94)00040-p")

bibentry(bibtype = "Article",
         key = "R:Ihaka+Murrell:2000",
         title = "An Approach to Providing Mathematical Annotation in Plots",
         volume = "9",
         .issn = "1537-2715",
         doi = "10.1093/biomet/66.3.605",
         number = "3",
         journal = "Journal of Computational and Graphical Statistics",
         publisher = "Informa UK Limited",
         author = c(person(given = "Ross",
                           family = "Ihaka"),
                    person(given = "Paul",
                           family = "Murrell")),
         year = "2000",
         month = "sep",
         pages = "582--599",
         .doi = "10.2307/2335182")

bibentry(bibtype = "Article",
         key = "R:Jones+Sheather:1991",
         title = "A Reliable Data-Based Bandwidth Selection Method for Kernel Density Estimation",
         volume = "53",
         .issn = "1467-9868",
         doi = "10.1111/j.2517-6161.1991.tb01857.x",
         number = "3",
         journal = "Journal of the Royal Statistical Society Series B: Statistical Methodology",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "M. C.",
                           family = "Jones"),
                    person(given = "S. J.",
                           family = "Sheather")),
         year = "1991",
         month = "jul",
         pages = "683--690")

bibentry(bibtype = "Article",
         key = "R:Kaiser:1958",
         title = "The Varimax Criterion for Analytic Rotation in Factor Analysis",
         volume = "23",
         .issn = "1860-0980",
         doi = "10.1007/BF02289233",
         number = "3",
         journal = "Psychometrika",
         publisher = "Cambridge University Press (CUP)",
         author = person(given = "Henry F.",
                         family = "Kaiser"),
         year = "1958",
         month = "sep",
         pages = "187--200",
         .doi = "10.1007/bf02289233")

bibentry(bibtype = "Article",
         key = "R:Kendall:1938",
         title = "A New Measure of Rank Correlation",
         volume = "30",
         .issn = "1464-3510",
         doi = "10.1093/biomet/30.1-2.81",
         number = "1--2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "M. G.",
                         family = "Kendall"),
         year = "1938",
         month = "jun",
         pages = "81--93")

bibentry(bibtype = "Article",
         key = "R:Kendall:1945",
         title = "The Treatment of Ties in Ranking Problems",
         volume = "33",
         .issn = "1464-3510",
         doi = "10.1093/biomet/33.3.239",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "M. G.",
                         family = "Kendall"),
         year = "1945",
         pages = "239--251")

bibentry(bibtype = "Article",
         key = "R:Kleiner+Hartigan:1984",
         title = "A Mosaic of Television Ratings",
         volume = "38",
         .issn = "1537-2731",
         doi = "10.1093/biomet/66.3.605",
         number = "1",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = "Beat",
                           family = "Kleiner"),
                    person(given = "J. A.",
                           family = "Hartigan")),
         year = "1984",
         month = "feb",
         pages = "32--35",
         .doi = "10.2307/2335182")

bibentry(bibtype = "Article",
         key = "R:Koonatz+Schnabel+Weiss:1985",
         title = "A modular system of algorithms for unconstrained minimization",
         volume = "11",
         .issn = "1557-7295",
         doi = "10.1145/6187.6192",
         number = "4",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "John E.",
                           family = "Koonatz"),
                    person(given = "Robert B.",
                           family = "Schnabel"),
                    person(given = "Barry E.",
                           family = "Weiss")),
         year = "1985",
         month = "dec",
         pages = "419--440")

bibentry(bibtype = "Article",
         key = "R:Lam:1995",
         title = "Remark AS R95: A Remark on Algorithm AS 226: Computing Non-Central Beta Probabilities",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986147",
         number = "4",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Ming Long",
                         family = "Lam"),
         year = "1995",
         pages = "551")

bibentry(bibtype = "Article",
         key = "R:Langford:2006",
         title = "Quartiles in Elementary Statistics",
         volume = "14",
         .issn = "1069-1898",
         doi = "10.1080/10691898.2006.11910589",
         number = "3",
         journal = "Journal of Statistics Education",
         publisher = "Informa UK Limited",
         author = person(given = "Eric",
                         family = "Langford"),
         year = "2006",
         month = "jan")

bibentry(bibtype = "Article",
         key = "R:Lenth:1987",
         title = "Algorithm AS 226: Computing Noncentral Beta Probabilities",
         volume = "36",
         .issn = "0035-9254",
         doi = "10.2307/2347558",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Russell V.",
                         family = "Lenth"),
         year = "1987",
         pages = "241")

bibentry(bibtype = "Article",
         key = "R:Lenth:1989",
         title = "Algorithm AS 243: Cumulative Distribution Function of the Non-Central t Distribution",
         volume = "38",
         .issn = "0035-9254",
         doi = "10.2307/2347693",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Russell V.",
                         family = "Lenth"),
         year = "1989",
         pages = "185")

bibentry(bibtype = "Article",
         key = "R:Ljung+Box:1978",
         title = "On a Measure of Lack of Fit in Time Series Models",
         volume = "65",
         .issn = "1464-3510",
         doi = "10.1080/01621459.1994.10476460",
         number = "2",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "G. M.",
                           family = "Ljung"),
                    person(given = "G. E. P.",
                           family = "Box")),
         year = "1978",
         month = "aug",
         pages = "297--303",
         .doi = "10.2307/2291215")

bibentry(bibtype = "Article",
         key = "R:Makkonen+Pajari:2014",
         title = "Defining Sample Quantiles by the True Rank Probability",
         volume = "2014",
         .issn = "1687-9538",
         doi = "10.1155/2014/326579",
         journal = "Journal of Probability and Statistics",
         publisher = "Wiley",
         author = c(person(given = "Lasse",
                           family = "Makkonen",
                           comment = c(ORCID = "0000-0002-3924-7882")),
                    person(given = "Matti",
                           family = "Pajari")),
         year = "2014",
         pages = "1--6")

bibentry(bibtype = "Article",
         key = "R:Mardia:1978",
         title = "Some properties of clasical multi-dimesional scaling",
         volume = "7",
         .issn = "1532-415X",
         doi = "10.1080/03610927808827707",
         number = "13",
         journal = "Communications in Statistics - Theory and Methods",
         publisher = "Informa UK Limited",
         author = person(given = "K.V.",
                         family = "Mardia"),
         year = "1978",
         month = "jan",
         pages = "1233--1241")

bibentry(bibtype = "Article",
         key = "R:Marsaglia+Tsang+Wang:2003",
         title = "Evaluating Kolmogorov’s Distribution",
         volume = "8",
         .issn = "1548-7660",
         doi = "10.18637/jss.v008.i18",
         number = "18",
         journal = "Journal of Statistical Software",
         publisher = "Foundation for Open Access Statistic",
         author = c(person(given = "George",
                           family = "Marsaglia"),
                    person(given = "Wai Wan",
                           family = "Tsang"),
                    person(given = "Jingbo",
                           family = "Wang")),
         year = "2003")

bibentry(bibtype = "Article",
         key = "R:McQuitty:1966",
         title = "Similarity Analysis by Reciprocal Pairs for Discrete and Continuous Data",
         volume = "26",
         .issn = "1552-3888",
         doi = "10.1177/001316446602600402",
         number = "4",
         journal = "Educational and Psychological Measurement",
         publisher = "SAGE Publications",
         author = person(given = "Louis L.",
                         family = "McQuitty"),
         year = "1966",
         month = "dec",
         pages = "825--831")

bibentry(bibtype = "Article",
         key = "R:Mcgill+Larsen+Tukey:1978",
         title = "Variations of Box Plots",
         volume = "32",
         .issn = "1537-2731",
         doi = "10.1093/biomet/58.3.453",
         number = "1",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = "Robert",
                           family = "Mcgill"),
                    person(given = "Wayne A.",
                           family = "Larsen"),
                    person(given = "John W.",
                           family = "Tukey")),
         year = "1978",
         month = "feb",
         pages = "12--16",
         .doi = "10.2307/2334381")

bibentry(bibtype = "Article",
         key = "R:Mead+Nelder:1965",
         title = "A Simplex Method for Function Minimization",
         volume = "7",
         .issn = "1460-2067",
         doi = "10.1093/comjnl/7.4.308",
         number = "4",
         journal = "The Computer Journal",
         publisher = "Oxford University Press (OUP)",
         author = c(person(given = "R.",
                           family = "Mead"),
                    person(given = "J. A.",
                           family = "Nelder")),
         year = "1965",
         month = "jan",
         pages = "308--313")

bibentry(bibtype = "Article",
         key = "R:Mehta+Patel:1983",
         title = "A Network Algorithm for Performing Fisher’s Exact Test inr×cContingency Tables",
         volume = "78",
         .issn = "1537-274X",
         doi = "10.1080/01621459.1983.10477989",
         number = "382",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = c(person(given = "Cyrus R.",
                           family = "Mehta"),
                    person(given = "Nitin R.",
                           family = "Patel")),
         year = "1983",
         month = "jun",
         pages = "427--434")

bibentry(bibtype = "Article",
         key = "R:Murdoch:2010",
         title = "Source References",
         volume = "2",
         .issn = "2073-4859",
         doi = "10.1090/s0025-5718-1965-0178586-1",
         number = "2",
         journal = "The R Journal",
         publisher = "The R Foundation",
         author = person(given = "Duncan",
                         family = "Murdoch"),
         year = "2010",
         pages = "16",
         .doi = "10.2307/2003354")

bibentry(bibtype = "Article",
         key = "R:Murdoch+Hornik:2011",
         title = "Watch Your Spelling!",
         volume = "3",
         .issn = "2073-4859",
         doi = "10.1007/BF02294026",
         number = "2",
         journal = "The R Journal",
         publisher = "The R Foundation",
         author = c(person(given = "Duncan",
                           family = "Murdoch"),
                    person(given = "Kurt",
                           family = "Hornik")),
         year = "2011",
         pages = "22",
         .doi = "10.1007/bf02294026")

bibentry(bibtype = "Article",
         key = "R:Murrell:1999",
         title = "Layouts: A Mechanism for Arranging Plots on a Page",
         volume = "8",
         .issn = "1537-2715",
         doi = "10.1080/01621459.1994.10476460",
         number = "1",
         journal = "Journal of Computational and Graphical Statistics",
         publisher = "Informa UK Limited",
         author = person(given = "Paul R.",
                         family = "Murrell"),
         year = "1999",
         month = "mar",
         pages = "121--134",
         .doi = "10.2307/2291215")

bibentry(bibtype = "Article",
         key = "R:Murtagh+Legendre:2014",
         title = "Ward’s Hierarchical Agglomerative Clustering Method: Which Algorithms Implement Ward’s Criterion?",
         volume = "31",
         .issn = "1432-1343",
         doi = "10.1007/s00357-014-9161-z",
         number = "3",
         journal = "Journal of Classification",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "Fionn",
                           family = "Murtagh"),
                    person(given = "Pierre",
                           family = "Legendre")),
         year = "2014",
         month = "oct",
         pages = "274--295")

bibentry(bibtype = "Article",
         key = "R:Newcombe:1998a",
         author = person(given = c("Robert", "G."),
                         family = "Newcombe"),
         title = "Two-sided Confidence Intervals for the Single Proportion: Comparison of Seven Methods",
         journal = "Statistics in Medicine",
         volume = "17",
         number = "8",
         pages = "857--872",
         doi = "10.1002/(SICI)1097-0258(19980430)17:8<857::AID-SIM777>3.0.CO;2-E",
         year = "1998")

bibentry(bibtype = "Article",
         key = "R:Newcombe:1998b",
         author = person(given = c("Robert", "G."),
                         family = "Newcombe"),
         title = "Interval Estimation for the Difference Between Independent Proportions: Comparison of Eleven Methods",
         journal = "Statistics in Medicine",
         volume = "17",
         number = "8",
         pages = "873--890",
         doi = "10.1002/(SICI)1097-0258(19980430)17:8<873::AID-SIM779>3.0.CO;2-I",
         year = "1998")

bibentry(bibtype = "Article",
         key = "R:Nocedal+Lu+Zhu:1995",
         title = "A Limited Memory Algorithm for Bound Constrained Optimization",
         volume = "16",
         .issn = "1095-7197",
         doi = "10.1137/0916069",
         number = "5",
         journal = "SIAM Journal on Scientific Computing",
         publisher = "Society for Industrial & Applied Mathematics (SIAM)",
         author = c(person(given = "Jorge",
                           family = "Nocedal"),
                    person(given = "Peihuang",
                           family = "Lu"),
                    person(given = "Ciyou",
                           family = "Zhu"),
                    person(given = "Richard H.",
                           family = "Byrd")),
         year = "1995",
         month = "sep",
         pages = "1190--1208")

bibentry(bibtype = "Article",
         key = "R:Odoroff+Gabriel:1990",
         title = "Biplots in Biomedical Research",
         volume = "9",
         .issn = "1097-0258",
         doi = "10.1002/sim.4780090502",
         number = "5",
         journal = "Statistics in Medicine",
         publisher = "Wiley",
         author = c(person(given = "Charles L.",
                           family = "Odoroff"),
                    person(given = "K. Ruben",
                           family = "Gabriel")),
         year = "1990",
         month = "may",
         pages = "469--485")

bibentry(bibtype = "Article",
         key = "R:Patefield:1981",
         title = "Algorithm AS 159: An Efficient Method of Generating Random R × C Tables with Given Row and Column Totals",
         volume = "30",
         .issn = "0035-9254",
         doi = "10.2307/2346669",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "W. M.",
                         family = "Patefield"),
         year = "1981",
         pages = "91")

bibentry(bibtype = "Article",
         key = "R:Patel+Mehta:1986",
         title = "ALGORITHM 643: FEXACT: a FORTRAN subroutine for Fisher’s exact test on unordered r x c contingency tables",
         volume = "12",
         .issn = "1557-7295",
         doi = "10.1145/6497.214326",
         number = "2",
         journal = "ACM Transactions on Mathematical Software",
         publisher = "Association for Computing Machinery (ACM)",
         author = c(person(given = "Nitin R.",
                           family = "Patel"),
                    person(given = "Cyrus R.",
                           family = "Mehta")),
         year = "1986",
         month = "jun",
         pages = "154--161")

bibentry(bibtype = "Article",
         key = "R:Perron:1988",
         title = "Trends and Random Walks in Macroeconomic Time Series",
         volume = "12",
         .issn = "0165-1889",
         doi = "10.1016/0165-1889(88)90043-7",
         number = "2--3",
         journal = "Journal of Economic Dynamics and Control",
         publisher = "Elsevier BV",
         author = person(given = "Pierre",
                         family = "Perron"),
         year = "1988",
         month = "jun",
         pages = "297--332")

bibentry(bibtype = "Article",
         key = "R:Phillips+Harvey+Gardner:1980",
         title = "Algorithm AS 154: An Algorithm for Exact Maximum Likelihood Estimation of Autoregressive-Moving Average Models by Means of Kalman Filtering",
         volume = "29",
         .issn = "0035-9254",
         doi = "10.2307/2346910",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "G. D. A.",
                           family = "Phillips"),
                    person(given = "A. C.",
                           family = "Harvey"),
                    person(given = "G.",
                           family = "Gardner")),
         year = "1980",
         pages = "311")

bibentry(bibtype = "Article",
         key = "R:Royston:1982a",
         title = "An Extension of Shapiro and Wilk’s W Test for Normality to Large Samples",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347973",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "J. P.",
                         family = "Royston"),
         year = "1982",
         pages = "115")

bibentry(bibtype = "Article",
         key = "R:Royston:1982b",
         title = "Algorithm AS 181: The W Test for Normality",
         volume = "31",
         .issn = "0035-9254",
         doi = "10.2307/2347986",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "J. P.",
                         family = "Royston"),
         year = "1982",
         pages = "176")

bibentry(bibtype = "Article",
         key = "R:Royston:1995",
         title = "Remark AS R94: A Remark on Algorithm AS 181: The W-test for Normality",
         volume = "44",
         .issn = "0035-9254",
         doi = "10.2307/2986146",
         number = "4",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Patrick",
                         family = "Royston"),
         year = "1995",
         pages = "547")

bibentry(bibtype = "Article",
         key = "R:Sarkar:1998",
         title = "Some probability inequalities for ordered $\\rm MTP\\sb 2$ random variables: a proof of the Simes conjecture",
         volume = "26",
         .issn = "0090-5364",
         doi = "10.1214/aos/1028144846",
         number = "2",
         journal = "The Annals of Statistics",
         publisher = "Institute of Mathematical Statistics",
         author = person(given = "Sanat K.",
                         family = "Sarkar"),
         year = "1998",
         month = "apr")

bibentry(bibtype = "Article",
         key = "R:Schilling+Watkins:1994",
         title = "A Suggestion for Sunflower Plots",
         volume = "48",
         .issn = "1537-2731",
         doi = "10.1090/S0025-5718-1989-0962209-1",
         number = "4",
         journal = "The American Statistician",
         publisher = "Informa UK Limited",
         author = c(person(given = "Mark F.",
                           family = "Schilling"),
                    person(given = "Ann E.",
                           family = "Watkins")),
         year = "1994",
         month = "nov",
         pages = "303--305",
         .doi = "10.1090/s0025-5718-1989-0962209-1")

bibentry(bibtype = "Article",
         key = "R:Scott:1979",
         title = "On Optimal and Data-based Histograms",
         volume = "66",
         .issn = "1464-3510",
         doi = "10.1080/00031305.1974.10479053",
         number = "3",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "David W.",
                         family = "Scott"),
         year = "1979",
         pages = "605--610",
         .doi = "10.2307/2683520")

bibentry(bibtype = "Article",
         key = "R:Shaffer:1995",
         title = "Multiple Hypothesis Testing",
         volume = "46",
         .issn = "1545-2085",
         doi = "10.1146/annurev.ps.46.020195.003021",
         number = "1",
         journal = "Annual Review of Psychology",
         publisher = "Annual Reviews",
         author = person(given = "J P",
                         family = "Shaffer"),
         year = "1995",
         month = "jan",
         pages = "561--584")

bibentry(bibtype = "Article",
         key = "R:Shea:1988",
         title = "Algorithm AS 239: Chi-Squared and Incomplete Gamma Integral",
         volume = "37",
         .issn = "0035-9254",
         doi = "10.2307/2347328",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "B. L.",
                         family = "Shea"),
         year = "1988",
         pages = "466")

bibentry(bibtype = "Article",
         key = "R:Switzer:1976",
         title = "Confidence procedures for two-sample problems",
         volume = "63",
         .issn = "1464-3510",
         doi = "10.1093/biomet/63.1.13",
         number = "1",
         journal = "Biometrika",
         publisher = "Oxford University Press (OUP)",
         author = person(given = "Paul",
                         family = "Switzer"),
         year = "1976",
         pages = "13--25")

bibentry(bibtype = "Article",
         key = "R:Thomas+Cran+Martin:1977",
         title = "Remark AS R19 and Algorithm AS 109: A Remark on Algorithms: AS 63: The Incomplete Beta Integral AS 64: Inverse of the Incomplete Beta Function Ratio",
         volume = "26",
         .issn = "0035-9254",
         doi = "10.2307/2346887",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "G. E.",
                           family = "Thomas"),
                    person(given = "G. W.",
                           family = "Cran"),
                    person(given = "K. J.",
                           family = "Martin")),
         year = "1977",
         pages = "111")

bibentry(bibtype = "Article",
         key = "R:Thomson:1990",
         volume = "330",
         .issn = "2054-0272",
         doi = "10.1098/rsta.1990.0041",
         number = "1615",
         journal = "Philosophical Transactions of the Royal Society of London. Series A, Mathematical and Physical Sciences",
         publisher = "The Royal Society",
         year = "1990",
         month = "apr",
         pages = "601--616",
         title = "Time Series Analysis of Holocene Climate Data",
         author = person(given = c("David", "J."),
                         family = "Thomson"))

bibentry(bibtype = "Article",
         key = "R:Thomson:1938",
         title = "Methods of Estimating Mental Factors",
         volume = "141",
         .issn = "1476-4687",
         doi = "10.1038/141246a0",
         number = "3562",
         journal = "Nature",
         publisher = "Springer Science and Business Media LLC",
         author = person(given = "Godfrey H.",
                         family = "Thomson"),
         year = "1938",
         month = "feb",
         pages = "246--246")

bibentry(bibtype = "Article",
         key = "R:Welch:1951",
         title = "On the Comparison of Several Mean Values: An Alternative Approach",
         volume = "38",
         .issn = "0006-3444",
         doi = "10.2307/2332579",
         number = "3/4",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = "B. L.",
                         family = "Welch"),
         year = "1951",
         month = "dec",
         pages = "330")

bibentry(bibtype = "Article",
         key = "R:White+Hendrickson:1964",
         title = "PROMAX: A QUICK METHOD FOR ROTATION TO OBLIQUE SIMPLE STRUCTURE",
         volume = "17",
         .issn = "0950-561X",
         doi = "10.1111/j.2044-8317.1964.tb00244.x",
         number = "1",
         journal = "British Journal of Statistical Psychology",
         publisher = "Wiley",
         author = c(person(given = "Paul Owen",
                           family = "White"),
                    person(given = "Alan E.",
                           family = "Hendrickson")),
         year = "1964",
         month = "may",
         pages = "65--70")

bibentry(bibtype = "Article",
         key = "R:Whittle:1963",
         title = "On the Fitting of Multivariate Autoregressions, and the Approximate Canonical Factorization of a Spectral Density Matrix",
         volume = "50",
         .issn = "0006-3444",
         doi = "10.2307/2333753",
         number = "1/2",
         journal = "Biometrika",
         publisher = "JSTOR",
         author = person(given = "P.",
                         family = "Whittle"),
         year = "1963",
         month = "jun",
         pages = "129")

bibentry(bibtype = "Article",
         key = "R:Wichura:1988",
         title = "Algorithm AS 241: The Percentage Points of the Normal Distribution",
         volume = "37",
         .issn = "0035-9254",
         doi = "10.2307/2347330",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "Michael J.",
                         family = "Wichura"),
         year = "1988",
         pages = "477")

bibentry(bibtype = "Article",
         key = "R:Wilkinson+Rogers:1973",
         title = "Symbolic Description of Factorial Models for Analysis of Variance",
         volume = "22",
         .issn = "0035-9254",
         doi = "10.2307/2346786",
         number = "3",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "G. N.",
                           family = "Wilkinson"),
                    person(given = "C. E.",
                           family = "Rogers")),
         year = "1973",
         pages = "392")

bibentry(bibtype = "Article",
         key = "R:Williams:1987",
         title = "Generalized Linear Model Diagnostics Using the Deviance and Single Case Deletions",
         volume = "36",
         .issn = "0035-9254",
         doi = "10.2307/2347550",
         number = "2",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = person(given = "D. A.",
                         family = "Williams"),
         year = "1987",
         pages = "181")

bibentry(bibtype = "Article",
         key = "R:Wilson:1927",
         title = "Probable Inference, the Law of Succession, and Statistical Inference",
         volume = "22",
         .issn = "1537-274X",
         doi = "10.1111/j.1467-842X.1962.tb00285.x",
         number = "158",
         journal = "Journal of the American Statistical Association",
         publisher = "Informa UK Limited",
         author = person(given = "Edwin B.",
                         family = "Wilson"),
         year = "1927",
         month = "jun",
         pages = "209--212",
         .doi = "10.1111/j.1467-842x.1962.tb00285.x")

bibentry(bibtype = "Article",
         key = "R:Winters:1960",
         title = "Forecasting Sales by Exponentially Weighted Moving Averages",
         volume = "6",
         .issn = "1526-5501",
         doi = "10.1287/mnsc.6.3.324",
         number = "3",
         journal = "Management Science",
         publisher = "Institute for Operations Research and the Management Sciences (INFORMS)",
         author = person(given = "Peter R.",
                         family = "Winters"),
         year = "1960",
         month = "apr",
         pages = "324--342")

bibentry(bibtype = "Article",
         key = "R:Wong+Hartigan:1979",
         title = "Algorithm AS 136: A K-Means Clustering Algorithm",
         volume = "28",
         .issn = "0035-9254",
         doi = "10.2307/2346830",
         number = "1",
         journal = "Applied Statistics",
         publisher = "JSTOR",
         author = c(person(given = "M. A.",
                           family = "Wong"),
                    person(given = "J. A.",
                           family = "Hartigan")),
         year = "1979",
         pages = "100")

bibentry(bibtype = "Article",
         key = "R:Wright:1992",
         title = "Adjusted P-Values for Simultaneous Inference",
         volume = "48",
         .issn = "0006-341X",
         doi = "10.2307/2532694",
         number = "4",
         journal = "Biometrics",
         publisher = "JSTOR",
         author = person(given = "S. Paul",
                         family = "Wright"),
         year = "1992",
         month = "dec",
         pages = "1005")
