bibentry(bibtype = "Manual",
         key = "R:Francois:2012",
         title = "parser: Detailed {R} source code parser",
         author = person(given = "Romain",
                         family = "Francois"),
         year = "2012",
         note = "R package version 0.0-16",
         url = "https://github.com/halpo/parser")

bibentry(bibtype = "InProceedings",
         key = "R:Leisch:2002",
         author = person(given = "Friedrich",
                         family = "Leisch",
                         comment = c(ORCID = "0000-0001-7278-1983")),
         title = "Sweave: Dynamic Generation of Statistical Reports Using Literate Data Analysis",
         booktitle = "Compstat 2002 --- Proceedings in Computational Statistics",
         pages = "575--580",
         year = "2002",
         editor = c(person(given = c("Wolfgang", "Karl"),
                           family = "Härdle",
                           comment = c(ORCID = "0000-0001-5600-3014")),
                    person(given = "Bernd",
                           family = "Rönz")),
         publisher = "Physica Verlag, Heidelberg",
         isbn = "3-7908-1517-9",
         url = "https://doi.org/10.57938/9f6e8c91-0b5a-4353-9802-f20479f0f5e2")

bibentry(bibtype = "Article",
         key = "R:Hornik+Murdoch:2011",
         title = "Watch Your Spelling!",
         volume = "3",
         .issn = "2073-4859",
         doi = "10.32614/RJ-2011-014",
         number = "2",
         journal = "The R Journal",
         publisher = "The R Foundation",
         author = c(person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "Duncan",
                           family = "Murdoch")),
         year = "2011",
         pages = "22")

bibentry(bibtype = "Book",
         key = "R:Nijenhuis+Wilf:1978",
         author = c(person(given = "Albert",
                           family = "Nijenhuis"),
                    person(given = c("Herbert", "S."),
                           family = "Wilf")),
         title = "Combinatorial Algorithms for Computers and Calculators",
         publisher = "Academic Press",
         year = "1978",
         isbn = "978-0125192606")

bibentry(bibtype = "Misc",
         key = "R:Wikipedia_contributors:2024",
         author = person(given = "Wikipedia contributors"),
         title = "Roman numerals --- {Wikipedia}{,} The Free Encyclopedia",
         year = "2024",
         url = "https://en.wikipedia.org/w/index.php?title=Roman_numerals&oldid=1188781837",
         note = "Accessed 2024-02-22")

