#-*- Makefile -*-
include ../../gnuwin32/MkRules

SOURCES = adler32.c compress.c crc32.c deflate.c gzio.c infblock.c \
  infcodes.c inffast.c inflate.c inftrees.c infutil.c trees.c uncompr.c \
  zutil.c
OBJECTS = $(SOURCES:.c=.o)

CFLAGS=-O3

libz.a: $(OBJECTS)

clean:
	$(RM) *.o *~
distclean: clean
	$(RM) libz.a
