#-*- Makefile -*-
include ../../gnuwin32/MkRules

DEFS=-DWIN32 -DHAVE_CONFIG_H
ifdef LEA_MALLOC
DEFS+=-DLEA_MALLOC
endif

CPPFLAGS=-I. -I../../include $(DEFS)

all: libxdr.a

libxdr.a: xdr.o xdr_float.o xdr_stdio.o xdr_mem.o

clean:
	$(RM) *.o *~
distclean: clean
	$(RM) libxdr.a
