#!/bin/sh
#  doc2dvi -- 'check' man pages (help files) by  'LaTeX'..
#
# Example (in $RHOME):  
#    etc/doc2dvi src/library/base/man/Normal
#    etc/doc2dvi `grep -l 'KEYWORD(distr' src/library/base/man/* |sort|uniq`
#
Pwd=`dirname $0`
RHOME=${Pwd}/..
D2L=${Pwd}/doc2latex
#
call_dir=`pwd`

if [ -f doc.tex ]  
then 
    echo "'doc.tex' already exists -- renaming it to  doc.tex.Older"
    echo " -------- "
    mv doc.tex doc.tex.Older
fi
$D2L $@ > doc.tex
if [ ! -f Man0.tex ]; then ln -s ${RHOME}/mansrc/latex/Man0.tex . ; fi
if [ ! -f Rdoc.sty ]; then
 sed 's/markright{#1}/markboth{#1}{#1}/' ${RHOME}/mansrc/latex/Rdoc.sty > doc.sty
fi
latex Man0
if [ -x `/usr/bin/which xdvi` ]
then  xdvi Man0 & 
fi
echo ''
echo 'doc2dvi: You may want to clean up by'
echo '    rm Man0.* doc.sty doc.tex'
echo ''
