#!/bin/sh
#
# ${RHOME}/etc/build-help
# Usage:  build-help [pkg] [lib]
# Install all help files, INDEX and TITLE for package pkg to library lib
# (defaults are `${RHOME}/src/library/base' and the default library,
# `${RHOME}/library', respectively). 

RHOME=`dirname $0`/..		# relative
RHOME=`cd ${RHOME}; pwd`	# absolute

if [ "$1" ]
then
    if test -d $1
    then
	pkg=$1
    else
	echo "Package \`${1}' does not exist"
	exit 1
    fi
else
    pkg="${RHOME}/src/library/base"
fi

if [ "$2" ]
then
    if mkdir -p $2
    then
	lib=`cd $2; pwd`
    else
	echo "Cannot write to \`$2'"
	exit 1
    fi
else
    lib=${RHOME}/library
fi    

if cd ${pkg}/man;
then
    pkg=`basename ${pkg}`
else
    echo "There are no man pages in \`${pkg}'"
    exit 1
fi    

DEST=${lib}/${pkg}/help
FILES=`ls *.Rd`

echo " >>> Building help pages for package \`${pkg}'"
for file in ${FILES}
do
    name=`basename $file .Rd`
    ${RHOME}/etc/Rdconv -t nroff ${file} \
	| nroff -ms 2> /dev/null \
	| ${RHOME}/etc/help.pretty > ${DEST}/${name}	
    echo "  ${name}"
done




