#!/bin/sh
#
# ${RHOME}/etc/build-alllatex
# Should work from anywhere in the R source tree.

RHOME=`dirname $0`/..		# relative
RHOME=`cd ${RHOME}; pwd`	# absolute
export RHOME

PKGS=`cd ${RHOME}/src/library; ls | sed '
/^\./d
/CVS/d
/LIB*/d
/Makefile/d
/profile/d'`

cd ${RHOME}/src/library
for pkg in ${PKGS}
do
    ${RHOME}/etc/build-help --latex ${pkg}
done
