#!/bin/sh
#
# ${RHOME}/etc/build-help
# Usage:  build-help [pkg] [lib]
# Install all help files, INDEX and TITLE for package pkg to library lib
# (defaults are `${RHOME}/src/library/base' and the default library,
# `${RHOME}/library', respectively). 

RHOME=`dirname $0`/..		# relative
RHOME=`cd ${RHOME}; pwd`	# absolute

if [ "$1" ]
then
    if test -d $1
    then
	pkg=$1
    else
	echo "Package \`${1}' does not exist"
	exit 1
    fi
else
    pkg="${RHOME}/src/library/base"
fi

if [ "$2" ]
then
    if mkdir -p $2
    then
	lib=`cd $2; pwd`
    else
	echo "Cannot write to \`$2'"
	exit 1
    fi
else
    lib=${RHOME}/library
fi    

if cd ${pkg}/man;
then
    pkg=`basename ${pkg}`
else
    echo "There are no man pages in \`${pkg}'"
    exit 1
fi    

DEST=${lib}/${pkg}/help
if mkdir -p ${DEST}
then
   cp /dev/null ${DEST}/AnIndex
else    
   echo "Cannot write to \`${DEST}'"
   exit 1
fi

FILES=`ls *.Rd`

echo -n " >>> Building help index for package \`${pkg}' ..."
(
    for file in ${FILES}
    do
	name=`basename ${file} .Rd`
	## In the base library, each help file should have an alias for
	## all topics it provides documentation for (the help file name
	## may differ from ANY object (eg `Special')
	if [ ${pkg} != "base" ]
	then
	    echo "${name}	${name}"
	fi
	ALIASES=`grep '^\\\\alias' ${file} |
	    sed 's/\\\\alias{\(.*\)} *$/\1/; '`
	for alias in ${ALIASES}
	do
	    echo "${alias}	${name}"
	done
    done
) | sort -d -f | uniq >> ${DEST}/AnIndex
echo " done."

echo " >>> Building help pages for package \`${pkg}'"
for file in ${FILES}
do
    name=`basename $file .Rd`
    ${RHOME}/etc/Rdconv -t nroff ${file} \
	| nroff -ms 2> /dev/null > ${DEST}/${name}	
    echo "  ${name}"
done
