#!/bin/sh
#
# ${RHOME}/etc/build-allhelp
# Should work from anywhere in the R source tree.

# FIXME when the new directory structure is here!

RHOME=`dirname $0`/..		# relative
RHOME=`cd ${RHOME}; pwd`	# absolute
PKGS=`cd ${RHOME}/src/library; ls | sed '
/^\./d
/CVS/d
/LIB*/d
/Makefile/d
/profile/d'`

mkdir -p ${RHOME}/help
cp /dev/null ${RHOME}/help/LibIndex

cd ${RHOME}/src/library
for pkg in ${PKGS}
do
    ${RHOME}/etc/build-help ${pkg}
done
