#!/bin/sh
#
# ${RHOME}/etc/COMPILE

MAKEOPTS=

for i in $*; do
  case ${i} in
    *.[cfr])
      make -f ${RHOME}/etc/Makeconf ${MAKEOPTS} ${i%.*}.o
      ;;
    -D*|*=*)
      MAKEOPTS="${MAKEOPTS} ${i}"
      ;;
    *)
      echo "ERROR:  don't know how to compile ${i}"
      exit 1
      ;;
  esac
done

### Local Variables: ***
### mode: sh ***
### sh-indent: 2 ***
### End: ***
