#!/bin/sh

case $# in
0) echo "usage: tasks [ -open | -closed ]" ;;
esac

case $1 in

*open)

	gawk '
	/^TASK/				{task = $0}
	/^STATUS/ && $2~/[Oo]pen/	{print task; doprint=1}
	doprint
	/^-------/			{doprint=0}' TASKS

	;;

*closed)
	gawk '
	$0~/^TASK/			{task = $0}
	$0~/^STATUS/ && $2~/[Cc]losed/	{print task; doprint=1}
	doprint
	/^-------/			{doprint=0}' TASKS

	;;
esac
