void psx11_Circle(double, double, double, int, int);
void psx11_Clip(double, double, double, double);
void psx11_Close(void);
void psx11_EndPath(void);
void psx11_LineTo(double, double);
void psx11_MoveTo(double, double);
void psx11_NewPlot(int, int, double, double, int, int, rcolor, int, rcolor);
int  psx11_Open(char*, int);
void psx11_Polygon(int, double*, double*, int, int);
void psx11_PrintPlot(void);
void psx11_Rect(double, double, double, double, int, int);
void psx11_SavePlot(char *);
void psx11_SetColor(int);
void psx11_SetFont(int, int);
void psx11_SetLinetype(int);
void psx11_StartPath(void);
void psx11_Text(double, double, char*, double, double, double);
