#!/bin/sh
#
#
manDIR=../../src/library/base/man
manFiles=`cd ${manDIR}; ls * | sed '/~/d'`
#Dbg echo "manFiles=«${manFiles}»" >&2

ECHO=/usr/ucb/echo
if [ ! -f $ECHO ]; then ECHO=/bin/echo; fi
ECHOn="${ECHO} -n" 

for f in $*
do $ECHOn '###--- >> '"$f"
    if [ -r ${manDIR}/"$f" ]
    then $ECHOn ' << ---'; extrExamp ${manDIR}/$f 
    else
      ##-- really  INefficient !! -- use perl, use "database"  Files <-> ALIAS 
	gr=`cd ${manDIR}; grep -l "ALIAS($f)" $manFiles`
	#Dbg (echo ; echo "$f: '$gr'") >&2
	if [ -n "$gr" ]
	then gr=`echo $gr`
	     echo " >>> '$gr'"
    	else echo " @@ NO file @@"
	fi
    fi
done

