#! /bin/sh
#---------- this file is  NOT used anymore ! -- 'make' is "smarter"..
CORE=../../../library/core

if [ ! -f $CORE ]
then
	echo "error: $CORE library does not exist"
	exit 1
fi

# Step One: extract all builtins and interpreted functions
(
grep :=  $CORE | sed '
s/ *:=.*//
s/"//g
/^#/d
/^	/d
/.*<-$/d
'
grep 'PP_' ../../main/names.c | sed '
/	1[0-9],	/d
/,1[0-9],	/d
/\?/d
s/",.*//
s/"//
s/{ *//
/.*<-$/d
'
) | sed 's/^[ 	]*//' | sort -d -f | uniq > ALL_FUNCTIONS

# Step Two: Extract all documented functions
(
ls ../man
grep ALIAS ../man/* | sed '
s/.*:ALIAS(//
s/)$//
'
) | sed 's/^[ 	]*//' | sort -d -f | uniq > DOCUMENTED

diff ALL_FUNCTIONS DOCUMENTED | grep '^<' | sed '
s/^< //
' > UNDOCUMENTED
