#!/bin/sh
#
MANdir=$1 ; if [ -z "$MANdir" ]; then MANdir=../../src/library/base/man; fi

FILES="`ls -A $MANdir | sed '/CVS/d;/~$/d;/\.bak$/d;/\.orig$/d'`"
#
for f in ${FILES}
do
    # SunOS 4:  grep -s : 'silent', only "error status"
    if grep -s '^EXAMPLES(' > /dev/null $f
    then i=0 # Whoah, horrible code.... need a dummy statement rather use if NOT
    else echo $f | sed "s#${DIR}/##"
    fi
done
