#!/bin/sh
# Shell installer for RAqua
# RAqua is a bundle app that contains the R.bin bundle app
# ${R_HOME}/src/modules/aqua/AquaInstall

cd ../../../
make install rhome=/Applications/RAqua.app/R.bin.app/Contents mandir=/Applications/RAqua.app/R.bin.app/Contents bindir=/Applications/RAqua.app/R.bin.app/Contents
here=`pwd`;
cp src/modules/aqua/R.fix /Applications/RAqua.app/R.bin.app/Contents/
cd /Applications/RAqua.app/R.bin.app/Contents
mv RESOURCES R_RESOURCES
mv bin MacOS
ln -s MacOS bin
./R.fix
rm R.fix
cd ${here}
cp -R src/modules/aqua/Contents/Resources /Applications/RAqua.app/R.bin.app/Contents
cp src/modules/aqua/Contents/PkgInfo /Applications/RAqua.app/R.bin.app/Contents
cp src/modules/aqua/Contents/Info.plist /Applications/RAqua.app/R.bin.app/Contents

cp -R src/modules/aqua/RAqua/Contents/Resources /Applications/RAqua.app/Contents
cp src/modules/aqua/RAqua/Contents/PkgInfo /Applications/RAqua.app/Contents
cp src/modules/aqua/RAqua/Contents/Info.plist /Applications/RAqua.app/Contents
gcc src/modules/aqua/RAqua/Contents/MacOS/aqualaunch.c 
mkdir /Applications/RAqua.app/Contents/MacOS
mv a.out /Applications/RAqua.app/Contents/MacOS/RAqua


echo "Note: execute this script one time only!"
echo "type >>  /Applications/RAqua.app/Contents/MacOS/RAqua << to run R"
