#-*- Makefile -*-
include ../gnuwin32/MkRules

CFLAGS=$(OPTFLAGS) -I../include -DHAVE_CONFIG_H -DR_DLL_BUILD
FFLAGS=$(OPTFLAGS)
CSOURCES=$(wildcard *.c)
FSOURCES1=$(filter-out blas.f, $(wildcard *.f))
OBJS=$(CSOURCES:.c=.o) $(FSOURCES1:.f=.o)

all: makeMakedeps ../gnuwin32/libappl.a

../gnuwin32/libappl.a: $(OBJS)

# Dependencies
DEPS=$(CSOURCES:.c=.d)


makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
