#-*- Makefile -*-
include ../../gnuwin32/MkRules

CFLAGS=$(OPTFLAGS)
OBJS = compat.o triostr.o trio.o trionan.o
TARGETLIB = libtrio.a

all: $(TARGETLIB)

$(TARGETLIB): $(OBJS)

distclean clean:
	$(RM) *~ core $(OBJS) $(TARGETLIB)
