#-*- Makefile -*-
include ../../gnuwin32/MkRules

# triop.h says this does not work, but useful to debug wchar conversions.
trio-CPPFLAGS=-DTRIO_FEATURE_WIDECHAR=1

# trionan.c and triostr.c are included by trio.o
OBJS = compat.o trio.o
TARGETLIB = libtrio.a

all: $(TARGETLIB)

$(TARGETLIB): $(OBJS)

clean:
	@$(RM) *~ $(OBJS)
distclean: clean
	@$(RM) $(TARGETLIB)
