	"R_approx",	R_approx,   
	"ch2inv",	ch2inv,
	"chol",	chol,
/*	"dbksl",	dbksl, */
	"bakslv",	bakslv,
	"bincode",	bincode,
	"bincode2",	bincode2,
	"bincount",	bincount,
	"cg",	cg,
	"ch",	ch,
	"rg",	rg,
	"rs",	rs,
	"cumsum",	R_cumsum,
/*	"distance",	R_distance,  */
	"R_distance",	R_distance,  
	"dpbfa",	dpbfa,
	"dpbsl",	dpbsl,
	"dpoco",	dpoco,
	"dpodi",	dpodi,
	"dpofa",	dpofa,
	"dposl",	dposl,
	"dqrcf",	dqrcf,
	"dqrdc",	dqrdc,
	"idamax",	idamax,
/*	"dqrdca",	dqrdca, */
	"dqrdc2",	dqrdc2,
	"dqrls",	dqrls,
	"dqrsl",	dqrsl,
	"dqrqty",	dqrqty,
	"dqrqy",	dqrqy,
	"dqrrsd",	dqrrsd,
	"chisqsim",	chisqsim,
	"dqrxb",	dqrxb,
	"dsvdc",	dsvdc,
	"dtrsl",	dtrsl,
	"dtrco",	dtrco,
	"fft_factor",	fft_factor,
	"fft_work",	fft_work,
	"fdhess",	fdhess,
    "fmin",	Brent_fmin,
	"lminfl",	lminfl,
	"loglin",	loglin,
	"lowess",	lowess,
	"massdist",	massdist,
	"optif9",	optif9,
	"R_pretty",	R_pretty,   
	"rowsum",	R_rowsum,
	"zeroin",	R_zeroin,
	"spline_coef",	spline_coef,
	"spline_eval",	spline_eval,
	"stemleaf",	stemleaf,
	"str_signif",	str_signif,
/*	"tabulate",	tabulate, */
	"R_tabulate",	R_tabulate, 
	