/*#define R_PLATFORM	"Macintosh"
#define R_CPU		"ppc"
#define R_VENDOR	"apple"
#define R_OS		"MacOS"
*/
#define R_MAJOR		"1"
#define R_MINOR		"2.2"
#define R_STATUS	"beta"
#define R_STATUS_REV	"3.0"
#define R_DAY		"6"
#define R_MONTH		"February"
#define R_YEAR		"2001"
