#-*- Makefile -*-
include ../../gnuwin32/MkRules

all: makeMakedeps ../../gnuwin32/Rlibxml.a

OPTFLAGS=-O2 -Wall -pedantic
CFLAGS=$(OPTFLAGS) -I../../include -DHAVE_CONFIG_H -fnative-struct

CSOURCES=nanoftp.c nanohttp.c
OBJS=$(CSOURCES:.c=.o)

../../gnuwin32/Rlibxml.a: $(OBJS)

clean:
	$(RM) Makedeps *.d *.o

# Dependencies
DEPS=$(CSOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
