#-*- Makefile -*-

Rsharedir = ../share
Rlocaledir = $(Rsharedir)/locale

DOMAIN = R
CATALOGS = en.gmo # no use on Windows en@quot.gmo en@boldquot.gmo

all:
	@mkdir -p $(Rsharedir)
	@catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
	  dir=$(Rlocaledir)/$$lang/LC_MESSAGES; \
	  mkdir -p $$dir; \
	  cp -p $$cat $$dir/$(DOMAIN).mo; \
	  echo "installing $$cat as $$dir/$(DOMAIN).mo"; \
	done

clean:
	rm -rf $(Rlocaledir)
