#-*- Makefile -*-
include ../gnuwin32/MkRules

all: makeMakedeps libnmath.a

CFLAGS=$(OPTFLAGS) -I../include -DHAVE_CONFIG_H -DR_DLL_BUILD
FFLAGS=$(OPTFLAGS)
CSOURCES=$(wildcard *.c)
OBJS=$(CSOURCES:.c=.o)

libnmath.a: $(OBJS)

# Dependencies
DEPS=$(CSOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
