#-*- Makefile -*-
include ../gnuwin32/MkRules

all: makeMakedeps ../gnuwin32/libmath.a

CFLAGS=$(OPTFLAGS) -I../include -DHAVE_CONFIG_H
FFLAGS=$(OPTFLAGS)
CSOURCES=$(wildcard *.c)
FSOURCES=$(wildcard *.f)
OBJS=$(CSOURCES:.c=.o) $(FSOURCES:.f=.o)

../gnuwin32/libmath.a: $(OBJS)

# Dependencies
DEPS=$(CSOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
