#!/bin/sh
#
# ${RHOME}/tools/GETCONFIG

echo "/* src/include/Rconfig.h.  Generated automatically */"
echo "#ifndef R_VERSION_H"
echo "#define R_VERSION_H"
echo
echo "#ifndef _CONFIG_H"
echo
us=`sed -n /HAVE_F77_UNDERSCORE/p config.h | sed -n 1p | sed -e s/\ HAVE_F77_UNDERSCORE.\*//`
if [ "${us}" = "#define" ] ; then
  echo "#define F77_SYMBOL(x)	x ## _"
else
  echo "#define F77_SYMBOL(x)	x"
fi
echo
ieeea=`sed -n /HAVE_ISNAN/p config.h | sed -n 1p | sed -e s/\ HAVE_ISNAN.\*//`
ieeeb=`sed -n /HAVE_FINITE/p config.h | sed -n 1p | sed -e s/\ HAVE_FINITE.\*//`
if [ "${ieeea}" = "#define" -a "${ieeeb}" = "#define" ] ; then
  echo "#define IEEE_754 1"
else
  echo "/* #undef IEEE_754 */"
fi
endian=`grep "WORDS_BIGENDIAN" config.h`
echo "${endian}"
echo
echo "#endif"
echo "#endif"
