#-*- Makefile -*-

include ../../gnuwin32/MkRules

all: makeMakedeps libbz2.a

CFLAGS=-Wall -I../../include -O3

CSOURCES= blocksort.c huffman.c crctable.c randtable.c compress.c \
          decompress.c bzlib.c
OBJS=$(CSOURCES:.c=.o)

libbz2.a: $(OBJS)

clean:
	$(RM) *.o *~ libbz2.a *.d Makedeps

# Dependencies
DEPS=$(CSOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
