install:
	@echo making include links
	@rm -f ../../include/S.h
	@rm -f ../../include/S_compat.h
	@rm -f ../../include/f2c.h
	@rm -f ../../include/Fortran.h
	@rm -f ../../include/Blas.h
	@rm -f ../../include/Linpack.h
	@ln S.h S_compat.h f2c.h Fortran.h Blas.h Linpack.h ../../include

clean:
	@echo cleaning in src/include

realclean:
	@echo cleaning in src/include
	@rm -f ../../include/S.h
	@rm -f ../../include/S_compat.h
	@rm -f ../../include/f2c.h
	@rm -f ../../include/Fortran.h
	@rm -f ../../include/Blas.h
	@rm -f ../../include/Linpack.h
